[package]
name = "acyclic-actors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Public Actors v1 contract and validation"
readme = "README.md"

[dependencies]
acyclic-protify-proc-macro = { version = "=0.2.0", path = "../../vendor/protify-proc-macro-0.1.4" }
http-body = "1.1.0"
prost.workspace = true
protify = { version = "=0.1.4", default-features = false, features = ["std"] }
prost-reflect = { workspace = true, features = ["serde"] }
serde_json.workspace = true
serde.workspace = true
serde_bytes.workspace = true
ts-rs = "=12.0.1"
thiserror.workspace = true
tokio = { version = "1.48.0", default-features = false, features = ["macros", "sync"] }
tokio-util = { version = "=0.7.19", features = ["rt"] }
tonic-prost.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest.workspace = true
tonic = { version = "=0.14.6", default-features = false, features = ["codegen", "router", "transport", "tls-ring", "tls-webpki-roots"] }
tracing.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
tonic = { version = "=0.14.6", default-features = false, features = ["codegen"] }
tonic-web-wasm-client = "=0.9.2"
url = "=2.5.8"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
acyclic-workers = { path = "../workers", version = "=0.2.0" }
tokio.workspace = true
rcgen = "0.14.10"
tracing-subscriber.workspace = true

[build-dependencies]
acyclic-protify-proc-macro = { version = "=0.2.0", path = "../../vendor/protify-proc-macro-0.1.4" }
prost = "=0.14.4"
protoc-bin-vendored = "=3.3.0"
protify = { version = "=0.1.4", default-features = false, features = ["std"] }
tonic-prost-build = "=0.14.6"
ts-rs = "=12.0.1"
thiserror.workspace = true

[lints]
workspace = true
