[package]
name = "acyclic-conformance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
acyclic-fs = { path = "../filesystem" }
acyclic-inference = { path = "../inference" }
acyclic-machines = { path = "../machines" }
acyclic-objects = { path = "../objects" }
acyclic-stream = { path = "../stream" }
bytes.workspace = true
futures.workspace = true
blake3.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
acyclic-memory = { path = "../memory" }

[lints]
workspace = true
