[package]
name = "sdk-generation"
version = "0.1.0"
edition = "2021"
rust-version = "1.98"
publish = false
default-run = "sdk-generation"

[workspace]

[dependencies]
sdk-docs = { path = "../sdk-docs" }
cargo_metadata = "=0.23.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
