<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machines/v1/machines.proto

namespace Acyclic\Machines\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Identifies a checkpoint for a mutation.
 *
 * Generated from protobuf message <code>acyclic.machines.v1.CheckpointMutationRequest</code>
 */
class CheckpointMutationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The protocol value carried by CheckpointMutationRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ProtocolVersion protocol = 1;</code>
     */
    protected $protocol = null;
    /**
     * The idempotency key value carried by CheckpointMutationRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.IdempotencyKey idempotency_key = 2;</code>
     */
    protected $idempotency_key = null;
    /**
     * The checkpoint value carried by CheckpointMutationRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.CheckpointId checkpoint = 3;</code>
     */
    protected $checkpoint = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Machines\V1\ProtocolVersion $protocol
     *           The protocol value carried by CheckpointMutationRequest.
     *     @type \Acyclic\Machines\V1\IdempotencyKey $idempotency_key
     *           The idempotency key value carried by CheckpointMutationRequest.
     *     @type \Acyclic\Machines\V1\CheckpointId $checkpoint
     *           The checkpoint value carried by CheckpointMutationRequest.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Machines\V1\Machines::initOnce();
        parent::__construct($data);
    }

    /**
     * The protocol value carried by CheckpointMutationRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ProtocolVersion protocol = 1;</code>
     * @return \Acyclic\Machines\V1\ProtocolVersion|null
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    public function hasProtocol()
    {
        return isset($this->protocol);
    }

    public function clearProtocol()
    {
        unset($this->protocol);
    }

    /**
     * The protocol value carried by CheckpointMutationRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ProtocolVersion protocol = 1;</code>
     * @param \Acyclic\Machines\V1\ProtocolVersion $var
     * @return $this
     */
    public function setProtocol(\Acyclic\Machines\V1\ProtocolVersion|null $var)
    {
        $this->protocol = $var;

        return $this;
    }

    /**
     * The idempotency key value carried by CheckpointMutationRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.IdempotencyKey idempotency_key = 2;</code>
     * @return \Acyclic\Machines\V1\IdempotencyKey|null
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    public function hasIdempotencyKey()
    {
        return isset($this->idempotency_key);
    }

    public function clearIdempotencyKey()
    {
        unset($this->idempotency_key);
    }

    /**
     * The idempotency key value carried by CheckpointMutationRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.IdempotencyKey idempotency_key = 2;</code>
     * @param \Acyclic\Machines\V1\IdempotencyKey $var
     * @return $this
     */
    public function setIdempotencyKey(\Acyclic\Machines\V1\IdempotencyKey|null $var)
    {
        $this->idempotency_key = $var;

        return $this;
    }

    /**
     * The checkpoint value carried by CheckpointMutationRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.CheckpointId checkpoint = 3;</code>
     * @return \Acyclic\Machines\V1\CheckpointId|null
     */
    public function getCheckpoint()
    {
        return $this->checkpoint;
    }

    public function hasCheckpoint()
    {
        return isset($this->checkpoint);
    }

    public function clearCheckpoint()
    {
        unset($this->checkpoint);
    }

    /**
     * The checkpoint value carried by CheckpointMutationRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.CheckpointId checkpoint = 3;</code>
     * @param \Acyclic\Machines\V1\CheckpointId $var
     * @return $this
     */
    public function setCheckpoint(\Acyclic\Machines\V1\CheckpointId|null $var)
    {
        $this->checkpoint = $var;

        return $this;
    }

}

