<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machines/v1/machines.proto

namespace Acyclic\Machines\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Requests admission of a machine with lifecycle and budget policy.
 *
 * Generated from protobuf message <code>acyclic.machines.v1.CreateMachineRequest</code>
 */
class CreateMachineRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The protocol value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ProtocolVersion protocol = 1;</code>
     */
    protected $protocol = null;
    /**
     * The idempotency key value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.IdempotencyKey idempotency_key = 2;</code>
     */
    protected $idempotency_key = null;
    /**
     * The image value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.Image image = 3;</code>
     */
    protected $image = null;
    /**
     * The compatibility value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.CompatibilityPolicy compatibility = 4;</code>
     */
    protected $compatibility = null;
    /**
     * The suspension value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.SuspensionPolicy suspension = 6;</code>
     */
    protected $suspension = null;
    /**
     * The expiration value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ExpirationPolicy expiration = 7;</code>
     */
    protected $expiration = null;
    /**
     * The network policy digest value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>bytes network_policy_digest = 8;</code>
     */
    protected $network_policy_digest = '';
    /**
     * The budgets value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.Budgets budgets = 9;</code>
     */
    protected $budgets = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Machines\V1\ProtocolVersion $protocol
     *           The protocol value carried by CreateMachineRequest.
     *     @type \Acyclic\Machines\V1\IdempotencyKey $idempotency_key
     *           The idempotency key value carried by CreateMachineRequest.
     *     @type \Acyclic\Machines\V1\Image $image
     *           The image value carried by CreateMachineRequest.
     *     @type \Acyclic\Machines\V1\CompatibilityPolicy $compatibility
     *           The compatibility value carried by CreateMachineRequest.
     *     @type \Acyclic\Machines\V1\SuspensionPolicy $suspension
     *           The suspension value carried by CreateMachineRequest.
     *     @type \Acyclic\Machines\V1\ExpirationPolicy $expiration
     *           The expiration value carried by CreateMachineRequest.
     *     @type string $network_policy_digest
     *           The network policy digest value carried by CreateMachineRequest.
     *     @type \Acyclic\Machines\V1\Budgets $budgets
     *           The budgets value carried by CreateMachineRequest.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Machines\V1\Machines::initOnce();
        parent::__construct($data);
    }

    /**
     * The protocol value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ProtocolVersion protocol = 1;</code>
     * @return \Acyclic\Machines\V1\ProtocolVersion|null
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    public function hasProtocol()
    {
        return isset($this->protocol);
    }

    public function clearProtocol()
    {
        unset($this->protocol);
    }

    /**
     * The protocol value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ProtocolVersion protocol = 1;</code>
     * @param \Acyclic\Machines\V1\ProtocolVersion $var
     * @return $this
     */
    public function setProtocol(\Acyclic\Machines\V1\ProtocolVersion|null $var)
    {
        $this->protocol = $var;

        return $this;
    }

    /**
     * The idempotency key value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.IdempotencyKey idempotency_key = 2;</code>
     * @return \Acyclic\Machines\V1\IdempotencyKey|null
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    public function hasIdempotencyKey()
    {
        return isset($this->idempotency_key);
    }

    public function clearIdempotencyKey()
    {
        unset($this->idempotency_key);
    }

    /**
     * The idempotency key value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.IdempotencyKey idempotency_key = 2;</code>
     * @param \Acyclic\Machines\V1\IdempotencyKey $var
     * @return $this
     */
    public function setIdempotencyKey(\Acyclic\Machines\V1\IdempotencyKey|null $var)
    {
        $this->idempotency_key = $var;

        return $this;
    }

    /**
     * The image value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.Image image = 3;</code>
     * @return \Acyclic\Machines\V1\Image|null
     */
    public function getImage()
    {
        return $this->image;
    }

    public function hasImage()
    {
        return isset($this->image);
    }

    public function clearImage()
    {
        unset($this->image);
    }

    /**
     * The image value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.Image image = 3;</code>
     * @param \Acyclic\Machines\V1\Image $var
     * @return $this
     */
    public function setImage(\Acyclic\Machines\V1\Image|null $var)
    {
        $this->image = $var;

        return $this;
    }

    /**
     * The compatibility value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.CompatibilityPolicy compatibility = 4;</code>
     * @return \Acyclic\Machines\V1\CompatibilityPolicy|null
     */
    public function getCompatibility()
    {
        return $this->compatibility;
    }

    public function hasCompatibility()
    {
        return isset($this->compatibility);
    }

    public function clearCompatibility()
    {
        unset($this->compatibility);
    }

    /**
     * The compatibility value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.CompatibilityPolicy compatibility = 4;</code>
     * @param \Acyclic\Machines\V1\CompatibilityPolicy $var
     * @return $this
     */
    public function setCompatibility(\Acyclic\Machines\V1\CompatibilityPolicy|null $var)
    {
        $this->compatibility = $var;

        return $this;
    }

    /**
     * The suspension value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.SuspensionPolicy suspension = 6;</code>
     * @return \Acyclic\Machines\V1\SuspensionPolicy|null
     */
    public function getSuspension()
    {
        return $this->suspension;
    }

    public function hasSuspension()
    {
        return isset($this->suspension);
    }

    public function clearSuspension()
    {
        unset($this->suspension);
    }

    /**
     * The suspension value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.SuspensionPolicy suspension = 6;</code>
     * @param \Acyclic\Machines\V1\SuspensionPolicy $var
     * @return $this
     */
    public function setSuspension(\Acyclic\Machines\V1\SuspensionPolicy|null $var)
    {
        $this->suspension = $var;

        return $this;
    }

    /**
     * The expiration value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ExpirationPolicy expiration = 7;</code>
     * @return \Acyclic\Machines\V1\ExpirationPolicy|null
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    public function hasExpiration()
    {
        return isset($this->expiration);
    }

    public function clearExpiration()
    {
        unset($this->expiration);
    }

    /**
     * The expiration value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ExpirationPolicy expiration = 7;</code>
     * @param \Acyclic\Machines\V1\ExpirationPolicy $var
     * @return $this
     */
    public function setExpiration(\Acyclic\Machines\V1\ExpirationPolicy|null $var)
    {
        $this->expiration = $var;

        return $this;
    }

    /**
     * The network policy digest value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>bytes network_policy_digest = 8;</code>
     * @return string
     */
    public function getNetworkPolicyDigest()
    {
        return $this->network_policy_digest;
    }

    /**
     * The network policy digest value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>bytes network_policy_digest = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setNetworkPolicyDigest(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->network_policy_digest = $var;

        return $this;
    }

    /**
     * The budgets value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.Budgets budgets = 9;</code>
     * @return \Acyclic\Machines\V1\Budgets|null
     */
    public function getBudgets()
    {
        return $this->budgets;
    }

    public function hasBudgets()
    {
        return isset($this->budgets);
    }

    public function clearBudgets()
    {
        unset($this->budgets);
    }

    /**
     * The budgets value carried by CreateMachineRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.Budgets budgets = 9;</code>
     * @param \Acyclic\Machines\V1\Budgets $var
     * @return $this
     */
    public function setBudgets(\Acyclic\Machines\V1\Budgets|null $var)
    {
        $this->budgets = $var;

        return $this;
    }

}

