<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machines/v1/machines.proto

namespace Acyclic\Machines\V1;

use UnexpectedValueException;

/**
 * An enum in the Machines v1 wire contract.
 *
 * Protobuf type <code>acyclic.machines.v1.ExpirationKind</code>
 */
class ExpirationKind
{
    /**
     * Generated from protobuf enum <code>EXPIRATION_KIND_UNSPECIFIED = 0;</code>
     */
    const EXPIRATION_KIND_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>EXPIRATION_KIND_NEVER = 1;</code>
     */
    const EXPIRATION_KIND_NEVER = 1;
    /**
     * Generated from protobuf enum <code>EXPIRATION_KIND_MAX_AGE = 2;</code>
     */
    const EXPIRATION_KIND_MAX_AGE = 2;
    /**
     * Generated from protobuf enum <code>EXPIRATION_KIND_AT = 3;</code>
     */
    const EXPIRATION_KIND_AT = 3;
    /**
     * Generated from protobuf enum <code>EXPIRATION_KIND_IDLE = 4;</code>
     */
    const EXPIRATION_KIND_IDLE = 4;

    private static $valueToName = [
        self::EXPIRATION_KIND_UNSPECIFIED => 'EXPIRATION_KIND_UNSPECIFIED',
        self::EXPIRATION_KIND_NEVER => 'EXPIRATION_KIND_NEVER',
        self::EXPIRATION_KIND_MAX_AGE => 'EXPIRATION_KIND_MAX_AGE',
        self::EXPIRATION_KIND_AT => 'EXPIRATION_KIND_AT',
        self::EXPIRATION_KIND_IDLE => 'EXPIRATION_KIND_IDLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

