<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machines/v1/machines.proto

namespace Acyclic\Machines\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A message in the Machines v1 wire contract.
 *
 * Generated from protobuf message <code>acyclic.machines.v1.ForkedMachines</code>
 */
class ForkedMachines extends \Google\Protobuf\Internal\Message
{
    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>repeated .acyclic.machines.v1.MachineState machines = 1;</code>
     */
    private $machines;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Machines\V1\MachineState[] $machines
     *           A field in the Machines v1 wire contract.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Machines\V1\Machines::initOnce();
        parent::__construct($data);
    }

    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>repeated .acyclic.machines.v1.MachineState machines = 1;</code>
     * @return RepeatedField<\Acyclic\Machines\V1\MachineState>
     */
    public function getMachines()
    {
        return $this->machines;
    }

    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>repeated .acyclic.machines.v1.MachineState machines = 1;</code>
     * @param \Acyclic\Machines\V1\MachineState[] $var
     * @return $this
     */
    public function setMachines(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Acyclic\Machines\V1\MachineState::class);
        $this->machines = $arr;

        return $this;
    }

}

