<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machines/v1/machines.proto

namespace Acyclic\Machines\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Reports image capabilities and compatibility revision.
 *
 * Generated from protobuf message <code>acyclic.machines.v1.ImageQualification</code>
 */
class ImageQualification extends \Google\Protobuf\Internal\Message
{
    /**
     * The image value carried by ImageQualification.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.Image image = 1;</code>
     */
    protected $image = null;
    /**
     * The capabilities value carried by ImageQualification.
     *
     * Generated from protobuf field <code>repeated .acyclic.machines.v1.Capability capabilities = 2;</code>
     */
    private $capabilities;
    /**
     * The compatibility revision value carried by ImageQualification.
     *
     * Generated from protobuf field <code>bytes compatibility_revision = 3;</code>
     */
    protected $compatibility_revision = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Machines\V1\Image $image
     *           The image value carried by ImageQualification.
     *     @type int[] $capabilities
     *           The capabilities value carried by ImageQualification.
     *     @type string $compatibility_revision
     *           The compatibility revision value carried by ImageQualification.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Machines\V1\Machines::initOnce();
        parent::__construct($data);
    }

    /**
     * The image value carried by ImageQualification.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.Image image = 1;</code>
     * @return \Acyclic\Machines\V1\Image|null
     */
    public function getImage()
    {
        return $this->image;
    }

    public function hasImage()
    {
        return isset($this->image);
    }

    public function clearImage()
    {
        unset($this->image);
    }

    /**
     * The image value carried by ImageQualification.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.Image image = 1;</code>
     * @param \Acyclic\Machines\V1\Image $var
     * @return $this
     */
    public function setImage(\Acyclic\Machines\V1\Image|null $var)
    {
        $this->image = $var;

        return $this;
    }

    /**
     * The capabilities value carried by ImageQualification.
     *
     * Generated from protobuf field <code>repeated .acyclic.machines.v1.Capability capabilities = 2;</code>
     * @return RepeatedField<int> one of the values in {@see \Acyclic\Machines\V1\Capability}
     */
    public function getCapabilities()
    {
        return $this->capabilities;
    }

    /**
     * The capabilities value carried by ImageQualification.
     *
     * Generated from protobuf field <code>repeated .acyclic.machines.v1.Capability capabilities = 2;</code>
     * @param int[] $var one of the values in {@see \Acyclic\Machines\V1\Capability}
     * @return $this
     */
    public function setCapabilities(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Acyclic\Machines\V1\Capability::class);
        $this->capabilities = $arr;

        return $this;
    }

    /**
     * The compatibility revision value carried by ImageQualification.
     *
     * Generated from protobuf field <code>bytes compatibility_revision = 3;</code>
     * @return string
     */
    public function getCompatibilityRevision()
    {
        return $this->compatibility_revision;
    }

    /**
     * The compatibility revision value carried by ImageQualification.
     *
     * Generated from protobuf field <code>bytes compatibility_revision = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCompatibilityRevision(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->compatibility_revision = $var;

        return $this;
    }

}

