<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machines/v1/machines.proto

namespace Acyclic\Machines\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A message in the Machines v1 wire contract.
 *
 * Generated from protobuf message <code>acyclic.machines.v1.ListMachinesRequest</code>
 */
class ListMachinesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ProtocolVersion protocol = 1;</code>
     */
    protected $protocol = null;
    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.MachineId after = 2;</code>
     */
    protected $after = null;
    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>uint32 limit = 3;</code>
     */
    protected $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Machines\V1\ProtocolVersion $protocol
     *           A field in the Machines v1 wire contract.
     *     @type \Acyclic\Machines\V1\MachineId $after
     *           A field in the Machines v1 wire contract.
     *     @type int $limit
     *           A field in the Machines v1 wire contract.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Machines\V1\Machines::initOnce();
        parent::__construct($data);
    }

    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ProtocolVersion protocol = 1;</code>
     * @return \Acyclic\Machines\V1\ProtocolVersion|null
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    public function hasProtocol()
    {
        return isset($this->protocol);
    }

    public function clearProtocol()
    {
        unset($this->protocol);
    }

    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ProtocolVersion protocol = 1;</code>
     * @param \Acyclic\Machines\V1\ProtocolVersion $var
     * @return $this
     */
    public function setProtocol(\Acyclic\Machines\V1\ProtocolVersion|null $var)
    {
        $this->protocol = $var;

        return $this;
    }

    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.MachineId after = 2;</code>
     * @return \Acyclic\Machines\V1\MachineId|null
     */
    public function getAfter()
    {
        return $this->after;
    }

    public function hasAfter()
    {
        return isset($this->after);
    }

    public function clearAfter()
    {
        unset($this->after);
    }

    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.MachineId after = 2;</code>
     * @param \Acyclic\Machines\V1\MachineId $var
     * @return $this
     */
    public function setAfter(\Acyclic\Machines\V1\MachineId|null $var)
    {
        $this->after = $var;

        return $this;
    }

    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>uint32 limit = 3;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>uint32 limit = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->limit = $var;

        return $this;
    }

}

