<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machines/v1/machines.proto

namespace Acyclic\Machines\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Returns a bounded page of machine states and a continuation token.
 *
 * Generated from protobuf message <code>acyclic.machines.v1.MachinePage</code>
 */
class MachinePage extends \Google\Protobuf\Internal\Message
{
    /**
     * The machines value carried by MachinePage.
     *
     * Generated from protobuf field <code>repeated .acyclic.machines.v1.MachineState machines = 1;</code>
     */
    private $machines;
    /**
     * The next value carried by MachinePage.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.MachineId next = 2;</code>
     */
    protected $next = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Machines\V1\MachineState[] $machines
     *           The machines value carried by MachinePage.
     *     @type \Acyclic\Machines\V1\MachineId $next
     *           The next value carried by MachinePage.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Machines\V1\Machines::initOnce();
        parent::__construct($data);
    }

    /**
     * The machines value carried by MachinePage.
     *
     * Generated from protobuf field <code>repeated .acyclic.machines.v1.MachineState machines = 1;</code>
     * @return RepeatedField<\Acyclic\Machines\V1\MachineState>
     */
    public function getMachines()
    {
        return $this->machines;
    }

    /**
     * The machines value carried by MachinePage.
     *
     * Generated from protobuf field <code>repeated .acyclic.machines.v1.MachineState machines = 1;</code>
     * @param \Acyclic\Machines\V1\MachineState[] $var
     * @return $this
     */
    public function setMachines(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Acyclic\Machines\V1\MachineState::class);
        $this->machines = $arr;

        return $this;
    }

    /**
     * The next value carried by MachinePage.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.MachineId next = 2;</code>
     * @return \Acyclic\Machines\V1\MachineId|null
     */
    public function getNext()
    {
        return $this->next;
    }

    public function hasNext()
    {
        return isset($this->next);
    }

    public function clearNext()
    {
        unset($this->next);
    }

    /**
     * The next value carried by MachinePage.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.MachineId next = 2;</code>
     * @param \Acyclic\Machines\V1\MachineId $var
     * @return $this
     */
    public function setNext(\Acyclic\Machines\V1\MachineId|null $var)
    {
        $this->next = $var;

        return $this;
    }

}

