<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machines/v1/machines.proto

namespace Acyclic\Machines\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Identifies a machine.
 *
 * Generated from protobuf message <code>acyclic.machines.v1.MachineId</code>
 */
class MachineId extends \Google\Protobuf\Internal\Message
{
    /**
     * The value value carried by MachineId.
     *
     * Generated from protobuf field <code>bytes value = 1;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $value
     *           The value value carried by MachineId.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Machines\V1\Machines::initOnce();
        parent::__construct($data);
    }

    /**
     * The value value carried by MachineId.
     *
     * Generated from protobuf field <code>bytes value = 1;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * The value value carried by MachineId.
     *
     * Generated from protobuf field <code>bytes value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setValue(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->value = $var;

        return $this;
    }

}

