<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machines/v1/machines.proto

namespace Acyclic\Machines\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Reports operation status and its stable identity.
 *
 * Generated from protobuf message <code>acyclic.machines.v1.OperationState</code>
 */
class OperationState extends \Google\Protobuf\Internal\Message
{
    /**
     * The operation value carried by OperationState.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.OperationId operation = 1;</code>
     */
    protected $operation = null;
    /**
     * The status value carried by OperationState.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.OperationStatus status = 2;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Machines\V1\OperationId $operation
     *           The operation value carried by OperationState.
     *     @type int $status
     *           The status value carried by OperationState.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Machines\V1\Machines::initOnce();
        parent::__construct($data);
    }

    /**
     * The operation value carried by OperationState.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.OperationId operation = 1;</code>
     * @return \Acyclic\Machines\V1\OperationId|null
     */
    public function getOperation()
    {
        return $this->operation;
    }

    public function hasOperation()
    {
        return isset($this->operation);
    }

    public function clearOperation()
    {
        unset($this->operation);
    }

    /**
     * The operation value carried by OperationState.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.OperationId operation = 1;</code>
     * @param \Acyclic\Machines\V1\OperationId $var
     * @return $this
     */
    public function setOperation(\Acyclic\Machines\V1\OperationId|null $var)
    {
        $this->operation = $var;

        return $this;
    }

    /**
     * The status value carried by OperationState.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.OperationStatus status = 2;</code>
     * @return int one of the values in {@see \Acyclic\Machines\V1\OperationStatus}
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * The status value carried by OperationState.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.OperationStatus status = 2;</code>
     * @param int $var one of the values in {@see \Acyclic\Machines\V1\OperationStatus}
     * @return $this
     */
    public function setStatus(int $var)
    {
        GPBUtil::checkEnum($var, \Acyclic\Machines\V1\OperationStatus::class);
        $this->status = $var;

        return $this;
    }

}

