<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machines/v1/machines.proto

namespace Acyclic\Machines\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A message in the Machines v1 wire contract.
 *
 * Generated from protobuf message <code>acyclic.machines.v1.PolicySet</code>
 */
class PolicySet extends \Google\Protobuf\Internal\Message
{
    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.MachineId machine = 1;</code>
     */
    protected $machine = null;
    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.SuspensionPolicy policy = 2;</code>
     */
    protected $policy = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Machines\V1\MachineId $machine
     *           A field in the Machines v1 wire contract.
     *     @type \Acyclic\Machines\V1\SuspensionPolicy $policy
     *           A field in the Machines v1 wire contract.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Machines\V1\Machines::initOnce();
        parent::__construct($data);
    }

    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.MachineId machine = 1;</code>
     * @return \Acyclic\Machines\V1\MachineId|null
     */
    public function getMachine()
    {
        return $this->machine;
    }

    public function hasMachine()
    {
        return isset($this->machine);
    }

    public function clearMachine()
    {
        unset($this->machine);
    }

    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.MachineId machine = 1;</code>
     * @param \Acyclic\Machines\V1\MachineId $var
     * @return $this
     */
    public function setMachine(\Acyclic\Machines\V1\MachineId|null $var)
    {
        $this->machine = $var;

        return $this;
    }

    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.SuspensionPolicy policy = 2;</code>
     * @return \Acyclic\Machines\V1\SuspensionPolicy|null
     */
    public function getPolicy()
    {
        return $this->policy;
    }

    public function hasPolicy()
    {
        return isset($this->policy);
    }

    public function clearPolicy()
    {
        unset($this->policy);
    }

    /**
     * A field in the Machines v1 wire contract.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.SuspensionPolicy policy = 2;</code>
     * @param \Acyclic\Machines\V1\SuspensionPolicy $var
     * @return $this
     */
    public function setPolicy(\Acyclic\Machines\V1\SuspensionPolicy|null $var)
    {
        $this->policy = $var;

        return $this;
    }

}

