<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: machines/v1/machines.proto

namespace Acyclic\Machines\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Requests qualification of an image against a protocol version.
 *
 * Generated from protobuf message <code>acyclic.machines.v1.QualifyImageRequest</code>
 */
class QualifyImageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The protocol value carried by QualifyImageRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ProtocolVersion protocol = 1;</code>
     */
    protected $protocol = null;
    /**
     * The image value carried by QualifyImageRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.Image image = 2;</code>
     */
    protected $image = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Machines\V1\ProtocolVersion $protocol
     *           The protocol value carried by QualifyImageRequest.
     *     @type \Acyclic\Machines\V1\Image $image
     *           The image value carried by QualifyImageRequest.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Machines\V1\Machines::initOnce();
        parent::__construct($data);
    }

    /**
     * The protocol value carried by QualifyImageRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ProtocolVersion protocol = 1;</code>
     * @return \Acyclic\Machines\V1\ProtocolVersion|null
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    public function hasProtocol()
    {
        return isset($this->protocol);
    }

    public function clearProtocol()
    {
        unset($this->protocol);
    }

    /**
     * The protocol value carried by QualifyImageRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.ProtocolVersion protocol = 1;</code>
     * @param \Acyclic\Machines\V1\ProtocolVersion $var
     * @return $this
     */
    public function setProtocol(\Acyclic\Machines\V1\ProtocolVersion|null $var)
    {
        $this->protocol = $var;

        return $this;
    }

    /**
     * The image value carried by QualifyImageRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.Image image = 2;</code>
     * @return \Acyclic\Machines\V1\Image|null
     */
    public function getImage()
    {
        return $this->image;
    }

    public function hasImage()
    {
        return isset($this->image);
    }

    public function clearImage()
    {
        unset($this->image);
    }

    /**
     * The image value carried by QualifyImageRequest.
     *
     * Generated from protobuf field <code>.acyclic.machines.v1.Image image = 2;</code>
     * @param \Acyclic\Machines\V1\Image $var
     * @return $this
     */
    public function setImage(\Acyclic\Machines\V1\Image|null $var)
    {
        $this->image = $var;

        return $this;
    }

}

