// Generated by acyclic-sdk-contract-wire; compile this file against the installed package.
using System.Threading;
using System.Threading.Tasks;
using Acyclic.Sdk.Transport;

public static class RustTypedFacadeConsumer
{
    public static async Task ExerciseAsync(ObjectsClient objects, InferenceClient inference)
    {
        var bucket = objects.CreateBucket(new ObjectsCreateBucketRequest(
            "customer.inputs", new IdempotencyKeyText("retry-1")));
        var stream = objects.GetObject(new RustObjectsGetObjectRequest(null!, "", "", new ObjectKey("artifact"), null!));
        await foreach (var frame in stream.ReadAllAsync(CancellationToken.None))
        {
            _ = frame.Frame;
        }
        _ = bucket;
        _ = inference;
    }
}
