name = "acyclic_ada_deps"
description = ""
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["acyclic_ada_deps"]

[[depends-on]]
utilada = "=2.9.0"

[[depends-on]]
utilada_xml = "=2.9.0"

[[depends-on]]
utilada_curl = "=2.9.0"

[[depends-on]]
security = "=1.6.0"
