<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream/v2/stream.proto

namespace Acyclic\Stream\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * An append mutation in an atomic commit.
 *
 * Generated from protobuf message <code>acyclic.stream.v2.AppendMutation</code>
 */
class AppendMutation extends \Google\Protobuf\Internal\Message
{
    /**
     * The stream path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * Records in the stream operation.
     *
     * Generated from protobuf field <code>repeated bytes records = 2;</code>
     */
    private $records;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           The stream path.
     *     @type string[] $records
     *           Records in the stream operation.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Stream\V2\Stream::initOnce();
        parent::__construct($data);
    }

    /**
     * The stream path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * The stream path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * Records in the stream operation.
     *
     * Generated from protobuf field <code>repeated bytes records = 2;</code>
     * @return RepeatedField<string>
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Records in the stream operation.
     *
     * Generated from protobuf field <code>repeated bytes records = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setRecords(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->records = $arr;

        return $this;
    }

}

