<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream/v2/stream.proto

namespace Acyclic\Stream\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * One streamed child stream response.
 *
 * Generated from protobuf message <code>acyclic.stream.v2.ChildrenResponse</code>
 */
class ChildrenResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The child stream identity.
     *
     * Generated from protobuf field <code>.acyclic.stream.v2.Child child = 1;</code>
     */
    protected $child = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Stream\V2\Child $child
     *           The child stream identity.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Stream\V2\Stream::initOnce();
        parent::__construct($data);
    }

    /**
     * The child stream identity.
     *
     * Generated from protobuf field <code>.acyclic.stream.v2.Child child = 1;</code>
     * @return \Acyclic\Stream\V2\Child|null
     */
    public function getChild()
    {
        return $this->child;
    }

    public function hasChild()
    {
        return isset($this->child);
    }

    public function clearChild()
    {
        unset($this->child);
    }

    /**
     * The child stream identity.
     *
     * Generated from protobuf field <code>.acyclic.stream.v2.Child child = 1;</code>
     * @param \Acyclic\Stream\V2\Child $var
     * @return $this
     */
    public function setChild(\Acyclic\Stream\V2\Child|null $var)
    {
        $this->child = $var;

        return $this;
    }

}

