<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream/v2/stream.proto

namespace Acyclic\Stream\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * An admitted append included in a committed envelope.
 *
 * Generated from protobuf message <code>acyclic.stream.v2.CommittedAppend</code>
 */
class CommittedAppend extends \Google\Protobuf\Internal\Message
{
    /**
     * The stream path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * The inclusive starting sequence.
     *
     * Generated from protobuf field <code>uint64 start = 2;</code>
     */
    protected $start = 0;
    /**
     * The inclusive ending sequence.
     *
     * Generated from protobuf field <code>uint64 end = 3;</code>
     */
    protected $end = 0;
    /**
     * The observed or resulting stream tail.
     *
     * Generated from protobuf field <code>uint64 tail = 4;</code>
     */
    protected $tail = 0;
    /**
     * Records in the stream operation.
     *
     * Generated from protobuf field <code>repeated .acyclic.stream.v2.Record records = 5;</code>
     */
    private $records;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           The stream path.
     *     @type int|string $start
     *           The inclusive starting sequence.
     *     @type int|string $end
     *           The inclusive ending sequence.
     *     @type int|string $tail
     *           The observed or resulting stream tail.
     *     @type \Acyclic\Stream\V2\Record[] $records
     *           Records in the stream operation.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Stream\V2\Stream::initOnce();
        parent::__construct($data);
    }

    /**
     * The stream path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * The stream path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * The inclusive starting sequence.
     *
     * Generated from protobuf field <code>uint64 start = 2;</code>
     * @return int|string
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * The inclusive starting sequence.
     *
     * Generated from protobuf field <code>uint64 start = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStart(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->start = $var;

        return $this;
    }

    /**
     * The inclusive ending sequence.
     *
     * Generated from protobuf field <code>uint64 end = 3;</code>
     * @return int|string
     */
    public function getEnd()
    {
        return $this->end;
    }

    /**
     * The inclusive ending sequence.
     *
     * Generated from protobuf field <code>uint64 end = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEnd(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->end = $var;

        return $this;
    }

    /**
     * The observed or resulting stream tail.
     *
     * Generated from protobuf field <code>uint64 tail = 4;</code>
     * @return int|string
     */
    public function getTail()
    {
        return $this->tail;
    }

    /**
     * The observed or resulting stream tail.
     *
     * Generated from protobuf field <code>uint64 tail = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTail(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->tail = $var;

        return $this;
    }

    /**
     * Records in the stream operation.
     *
     * Generated from protobuf field <code>repeated .acyclic.stream.v2.Record records = 5;</code>
     * @return RepeatedField<\Acyclic\Stream\V2\Record>
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Records in the stream operation.
     *
     * Generated from protobuf field <code>repeated .acyclic.stream.v2.Record records = 5;</code>
     * @param \Acyclic\Stream\V2\Record[] $var
     * @return $this
     */
    public function setRecords(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Acyclic\Stream\V2\Record::class);
        $this->records = $arr;

        return $this;
    }

}

