<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream/v2/stream.proto

namespace Acyclic\Stream\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The conflicts returned by an atomic commit.
 *
 * Generated from protobuf message <code>acyclic.stream.v2.CommitConflicts</code>
 */
class CommitConflicts extends \Google\Protobuf\Internal\Message
{
    /**
     * Commit conflicts returned by the service.
     *
     * Generated from protobuf field <code>repeated .acyclic.stream.v2.CommitConflict conflicts = 1;</code>
     */
    private $conflicts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Stream\V2\CommitConflict[] $conflicts
     *           Commit conflicts returned by the service.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Stream\V2\Stream::initOnce();
        parent::__construct($data);
    }

    /**
     * Commit conflicts returned by the service.
     *
     * Generated from protobuf field <code>repeated .acyclic.stream.v2.CommitConflict conflicts = 1;</code>
     * @return RepeatedField<\Acyclic\Stream\V2\CommitConflict>
     */
    public function getConflicts()
    {
        return $this->conflicts;
    }

    /**
     * Commit conflicts returned by the service.
     *
     * Generated from protobuf field <code>repeated .acyclic.stream.v2.CommitConflict conflicts = 1;</code>
     * @param \Acyclic\Stream\V2\CommitConflict[] $var
     * @return $this
     */
    public function setConflicts(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Acyclic\Stream\V2\CommitConflict::class);
        $this->conflicts = $arr;

        return $this;
    }

}

