<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream/v2/stream.proto

namespace Acyclic\Stream\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * One condition checked before committing mutations.
 *
 * Generated from protobuf message <code>acyclic.stream.v2.CommitCondition</code>
 */
class CommitCondition extends \Google\Protobuf\Internal\Message
{
    protected $condition;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Stream\V2\TailCondition $tail
     *           The observed or resulting stream tail.
     *     @type \Acyclic\Stream\V2\AbsentCondition $absent
     *           The absence condition.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Stream\V2\Stream::initOnce();
        parent::__construct($data);
    }

    /**
     * The observed or resulting stream tail.
     *
     * Generated from protobuf field <code>.acyclic.stream.v2.TailCondition tail = 1;</code>
     * @return \Acyclic\Stream\V2\TailCondition|null
     */
    public function getTail()
    {
        return $this->readOneof(1);
    }

    public function hasTail()
    {
        return $this->hasOneof(1);
    }

    /**
     * The observed or resulting stream tail.
     *
     * Generated from protobuf field <code>.acyclic.stream.v2.TailCondition tail = 1;</code>
     * @param \Acyclic\Stream\V2\TailCondition $var
     * @return $this
     */
    public function setTail(\Acyclic\Stream\V2\TailCondition|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * The absence condition.
     *
     * Generated from protobuf field <code>.acyclic.stream.v2.AbsentCondition absent = 2;</code>
     * @return \Acyclic\Stream\V2\AbsentCondition|null
     */
    public function getAbsent()
    {
        return $this->readOneof(2);
    }

    public function hasAbsent()
    {
        return $this->hasOneof(2);
    }

    /**
     * The absence condition.
     *
     * Generated from protobuf field <code>.acyclic.stream.v2.AbsentCondition absent = 2;</code>
     * @param \Acyclic\Stream\V2\AbsentCondition $var
     * @return $this
     */
    public function setAbsent(\Acyclic\Stream\V2\AbsentCondition|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getCondition()
    {
        return $this->whichOneof("condition");
    }

}

