<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream/v2/stream.proto

namespace Acyclic\Stream\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Forks a stream path at an admitted sequence.
 *
 * Generated from protobuf message <code>acyclic.stream.v2.ForkRequest</code>
 */
class ForkRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The source stream path.
     *
     * Generated from protobuf field <code>string source = 1;</code>
     */
    protected $source = '';
    /**
     * The destination stream path.
     *
     * Generated from protobuf field <code>string destination = 2;</code>
     */
    protected $destination = '';
    /**
     * The optional sequence at which to fork.
     *
     * Generated from protobuf field <code>optional uint64 at_tail = 3;</code>
     */
    protected $at_tail = null;
    /**
     * Client key used to make a mutation idempotent.
     *
     * Generated from protobuf field <code>optional bytes idempotency_key = 4;</code>
     */
    protected $idempotency_key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source
     *           The source stream path.
     *     @type string $destination
     *           The destination stream path.
     *     @type int|string $at_tail
     *           The optional sequence at which to fork.
     *     @type string $idempotency_key
     *           Client key used to make a mutation idempotent.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Stream\V2\Stream::initOnce();
        parent::__construct($data);
    }

    /**
     * The source stream path.
     *
     * Generated from protobuf field <code>string source = 1;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * The source stream path.
     *
     * Generated from protobuf field <code>string source = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSource(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->source = $var;

        return $this;
    }

    /**
     * The destination stream path.
     *
     * Generated from protobuf field <code>string destination = 2;</code>
     * @return string
     */
    public function getDestination()
    {
        return $this->destination;
    }

    /**
     * The destination stream path.
     *
     * Generated from protobuf field <code>string destination = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDestination(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->destination = $var;

        return $this;
    }

    /**
     * The optional sequence at which to fork.
     *
     * Generated from protobuf field <code>optional uint64 at_tail = 3;</code>
     * @return int|string
     */
    public function getAtTail()
    {
        return isset($this->at_tail) ? $this->at_tail : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasAtTail()
    {
        return isset($this->at_tail);
    }

    public function clearAtTail()
    {
        unset($this->at_tail);
    }

    /**
     * The optional sequence at which to fork.
     *
     * Generated from protobuf field <code>optional uint64 at_tail = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAtTail(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->at_tail = $var;

        return $this;
    }

    /**
     * Client key used to make a mutation idempotent.
     *
     * Generated from protobuf field <code>optional bytes idempotency_key = 4;</code>
     * @return string
     */
    public function getIdempotencyKey()
    {
        return isset($this->idempotency_key) ? $this->idempotency_key : '';
    }

    public function hasIdempotencyKey()
    {
        return isset($this->idempotency_key);
    }

    public function clearIdempotencyKey()
    {
        unset($this->idempotency_key);
    }

    /**
     * Client key used to make a mutation idempotent.
     *
     * Generated from protobuf field <code>optional bytes idempotency_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIdempotencyKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->idempotency_key = $var;

        return $this;
    }

}

