<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream/v2/stream.proto

namespace Acyclic\Stream\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A commit condition on a stream tail.
 *
 * Generated from protobuf message <code>acyclic.stream.v2.TailCondition</code>
 */
class TailCondition extends \Google\Protobuf\Internal\Message
{
    /**
     * The stream path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * The expected stream tail.
     *
     * Generated from protobuf field <code>uint64 expected = 2;</code>
     */
    protected $expected = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           The stream path.
     *     @type int|string $expected
     *           The expected stream tail.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Stream\V2\Stream::initOnce();
        parent::__construct($data);
    }

    /**
     * The stream path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * The stream path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * The expected stream tail.
     *
     * Generated from protobuf field <code>uint64 expected = 2;</code>
     * @return int|string
     */
    public function getExpected()
    {
        return $this->expected;
    }

    /**
     * The expected stream tail.
     *
     * Generated from protobuf field <code>uint64 expected = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpected(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->expected = $var;

        return $this;
    }

}

