<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filesystem/v2/filesystem.proto

namespace Acyclic\Filesystem\V2;

use UnexpectedValueException;

/**
 * Protobuf type <code>acyclic.filesystem.v2.JoinStatus</code>
 */
class JoinStatus
{
    /**
     * Generated from protobuf enum <code>JOIN_STATUS_UNSPECIFIED = 0;</code>
     */
    const JOIN_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>JOIN_STATUS_APPLIED = 1;</code>
     */
    const JOIN_STATUS_APPLIED = 1;
    /**
     * Generated from protobuf enum <code>JOIN_STATUS_ALREADY_APPLIED = 2;</code>
     */
    const JOIN_STATUS_ALREADY_APPLIED = 2;
    /**
     * Generated from protobuf enum <code>JOIN_STATUS_NO_CHANGES = 3;</code>
     */
    const JOIN_STATUS_NO_CHANGES = 3;
    /**
     * Generated from protobuf enum <code>JOIN_STATUS_STALE_TARGET = 4;</code>
     */
    const JOIN_STATUS_STALE_TARGET = 4;
    /**
     * Generated from protobuf enum <code>JOIN_STATUS_CONFLICTED = 5;</code>
     */
    const JOIN_STATUS_CONFLICTED = 5;
    /**
     * Generated from protobuf enum <code>JOIN_STATUS_FENCED = 6;</code>
     */
    const JOIN_STATUS_FENCED = 6;
    /**
     * Generated from protobuf enum <code>JOIN_STATUS_IDEMPOTENCY_CONFLICT = 7;</code>
     */
    const JOIN_STATUS_IDEMPOTENCY_CONFLICT = 7;

    private static $valueToName = [
        self::JOIN_STATUS_UNSPECIFIED => 'JOIN_STATUS_UNSPECIFIED',
        self::JOIN_STATUS_APPLIED => 'JOIN_STATUS_APPLIED',
        self::JOIN_STATUS_ALREADY_APPLIED => 'JOIN_STATUS_ALREADY_APPLIED',
        self::JOIN_STATUS_NO_CHANGES => 'JOIN_STATUS_NO_CHANGES',
        self::JOIN_STATUS_STALE_TARGET => 'JOIN_STATUS_STALE_TARGET',
        self::JOIN_STATUS_CONFLICTED => 'JOIN_STATUS_CONFLICTED',
        self::JOIN_STATUS_FENCED => 'JOIN_STATUS_FENCED',
        self::JOIN_STATUS_IDEMPOTENCY_CONFLICT => 'JOIN_STATUS_IDEMPOTENCY_CONFLICT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

