<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filesystem/v2/filesystem.proto

namespace Acyclic\Filesystem\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>acyclic.filesystem.v2.PageOptions</code>
 */
class PageOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 maximum_items = 1;</code>
     */
    protected $maximum_items = 0;
    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.LogicalName after = 2;</code>
     */
    protected $after = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $maximum_items
     *     @type \Acyclic\Filesystem\V2\LogicalName $after
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Filesystem\V2\Filesystem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 maximum_items = 1;</code>
     * @return int
     */
    public function getMaximumItems()
    {
        return $this->maximum_items;
    }

    /**
     * Generated from protobuf field <code>uint32 maximum_items = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMaximumItems(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->maximum_items = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.LogicalName after = 2;</code>
     * @return \Acyclic\Filesystem\V2\LogicalName|null
     */
    public function getAfter()
    {
        return $this->after;
    }

    public function hasAfter()
    {
        return isset($this->after);
    }

    public function clearAfter()
    {
        unset($this->after);
    }

    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.LogicalName after = 2;</code>
     * @param \Acyclic\Filesystem\V2\LogicalName $var
     * @return $this
     */
    public function setAfter(\Acyclic\Filesystem\V2\LogicalName|null $var)
    {
        $this->after = $var;

        return $this;
    }

}

