<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filesystem/v2/filesystem.proto

namespace Acyclic\Filesystem\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>acyclic.filesystem.v2.PlanJoinRequest</code>
 */
class PlanJoinRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.GenerationRef source = 1;</code>
     */
    protected $source = null;
    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.GenerationRef target = 2;</code>
     */
    protected $target = null;
    /**
     * Generated from protobuf field <code>uint32 maximum_changes = 3;</code>
     */
    protected $maximum_changes = 0;
    /**
     * Generated from protobuf field <code>uint32 maximum_conflicts = 4;</code>
     */
    protected $maximum_conflicts = 0;
    /**
     * Generated from protobuf field <code>uint32 maximum_generations = 5;</code>
     */
    protected $maximum_generations = 0;
    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.JoinHistory history = 6;</code>
     */
    protected $history = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Filesystem\V2\GenerationRef $source
     *     @type \Acyclic\Filesystem\V2\GenerationRef $target
     *     @type int $maximum_changes
     *     @type int $maximum_conflicts
     *     @type int $maximum_generations
     *     @type int $history
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Filesystem\V2\Filesystem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.GenerationRef source = 1;</code>
     * @return \Acyclic\Filesystem\V2\GenerationRef|null
     */
    public function getSource()
    {
        return $this->source;
    }

    public function hasSource()
    {
        return isset($this->source);
    }

    public function clearSource()
    {
        unset($this->source);
    }

    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.GenerationRef source = 1;</code>
     * @param \Acyclic\Filesystem\V2\GenerationRef $var
     * @return $this
     */
    public function setSource(\Acyclic\Filesystem\V2\GenerationRef|null $var)
    {
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.GenerationRef target = 2;</code>
     * @return \Acyclic\Filesystem\V2\GenerationRef|null
     */
    public function getTarget()
    {
        return $this->target;
    }

    public function hasTarget()
    {
        return isset($this->target);
    }

    public function clearTarget()
    {
        unset($this->target);
    }

    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.GenerationRef target = 2;</code>
     * @param \Acyclic\Filesystem\V2\GenerationRef $var
     * @return $this
     */
    public function setTarget(\Acyclic\Filesystem\V2\GenerationRef|null $var)
    {
        $this->target = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 maximum_changes = 3;</code>
     * @return int
     */
    public function getMaximumChanges()
    {
        return $this->maximum_changes;
    }

    /**
     * Generated from protobuf field <code>uint32 maximum_changes = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaximumChanges(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->maximum_changes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 maximum_conflicts = 4;</code>
     * @return int
     */
    public function getMaximumConflicts()
    {
        return $this->maximum_conflicts;
    }

    /**
     * Generated from protobuf field <code>uint32 maximum_conflicts = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaximumConflicts(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->maximum_conflicts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 maximum_generations = 5;</code>
     * @return int
     */
    public function getMaximumGenerations()
    {
        return $this->maximum_generations;
    }

    /**
     * Generated from protobuf field <code>uint32 maximum_generations = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMaximumGenerations(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->maximum_generations = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.JoinHistory history = 6;</code>
     * @return int one of the values in {@see \Acyclic\Filesystem\V2\JoinHistory}
     */
    public function getHistory()
    {
        return $this->history;
    }

    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.JoinHistory history = 6;</code>
     * @param int $var one of the values in {@see \Acyclic\Filesystem\V2\JoinHistory}
     * @return $this
     */
    public function setHistory(int $var)
    {
        GPBUtil::checkEnum($var, \Acyclic\Filesystem\V2\JoinHistory::class);
        $this->history = $var;

        return $this;
    }

}

