<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filesystem/v2/filesystem.proto

namespace Acyclic\Filesystem\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>acyclic.filesystem.v2.ReadRequest</code>
 */
class ReadRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.GenerationRef generation = 1;</code>
     */
    protected $generation = null;
    /**
     * Generated from protobuf field <code>string path = 2;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.ByteRange range = 3;</code>
     */
    protected $range = null;
    /**
     * Generated from protobuf field <code>uint64 maximum_bytes = 4;</code>
     */
    protected $maximum_bytes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Filesystem\V2\GenerationRef $generation
     *     @type string $path
     *     @type \Acyclic\Filesystem\V2\ByteRange $range
     *     @type int|string $maximum_bytes
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Filesystem\V2\Filesystem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.GenerationRef generation = 1;</code>
     * @return \Acyclic\Filesystem\V2\GenerationRef|null
     */
    public function getGeneration()
    {
        return $this->generation;
    }

    public function hasGeneration()
    {
        return isset($this->generation);
    }

    public function clearGeneration()
    {
        unset($this->generation);
    }

    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.GenerationRef generation = 1;</code>
     * @param \Acyclic\Filesystem\V2\GenerationRef $var
     * @return $this
     */
    public function setGeneration(\Acyclic\Filesystem\V2\GenerationRef|null $var)
    {
        $this->generation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.ByteRange range = 3;</code>
     * @return \Acyclic\Filesystem\V2\ByteRange|null
     */
    public function getRange()
    {
        return $this->range;
    }

    public function hasRange()
    {
        return isset($this->range);
    }

    public function clearRange()
    {
        unset($this->range);
    }

    /**
     * Generated from protobuf field <code>.acyclic.filesystem.v2.ByteRange range = 3;</code>
     * @param \Acyclic\Filesystem\V2\ByteRange $var
     * @return $this
     */
    public function setRange(\Acyclic\Filesystem\V2\ByteRange|null $var)
    {
        $this->range = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 maximum_bytes = 4;</code>
     * @return int|string
     */
    public function getMaximumBytes()
    {
        return $this->maximum_bytes;
    }

    /**
     * Generated from protobuf field <code>uint64 maximum_bytes = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaximumBytes(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->maximum_bytes = $var;

        return $this;
    }

}

