<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filesystem/v2/filesystem.proto

namespace Acyclic\Filesystem\V2;

use UnexpectedValueException;

/**
 * Protobuf type <code>acyclic.filesystem.v2.RebaseStatus</code>
 */
class RebaseStatus
{
    /**
     * Generated from protobuf enum <code>REBASE_STATUS_UNSPECIFIED = 0;</code>
     */
    const REBASE_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>REBASE_STATUS_REBASED = 1;</code>
     */
    const REBASE_STATUS_REBASED = 1;
    /**
     * Generated from protobuf enum <code>REBASE_STATUS_ALREADY_REBASED = 2;</code>
     */
    const REBASE_STATUS_ALREADY_REBASED = 2;
    /**
     * Generated from protobuf enum <code>REBASE_STATUS_CURRENT = 3;</code>
     */
    const REBASE_STATUS_CURRENT = 3;
    /**
     * Generated from protobuf enum <code>REBASE_STATUS_STALE = 4;</code>
     */
    const REBASE_STATUS_STALE = 4;
    /**
     * Generated from protobuf enum <code>REBASE_STATUS_CONFLICTED = 5;</code>
     */
    const REBASE_STATUS_CONFLICTED = 5;
    /**
     * Generated from protobuf enum <code>REBASE_STATUS_FENCED = 6;</code>
     */
    const REBASE_STATUS_FENCED = 6;
    /**
     * Generated from protobuf enum <code>REBASE_STATUS_IDEMPOTENCY_CONFLICT = 7;</code>
     */
    const REBASE_STATUS_IDEMPOTENCY_CONFLICT = 7;

    private static $valueToName = [
        self::REBASE_STATUS_UNSPECIFIED => 'REBASE_STATUS_UNSPECIFIED',
        self::REBASE_STATUS_REBASED => 'REBASE_STATUS_REBASED',
        self::REBASE_STATUS_ALREADY_REBASED => 'REBASE_STATUS_ALREADY_REBASED',
        self::REBASE_STATUS_CURRENT => 'REBASE_STATUS_CURRENT',
        self::REBASE_STATUS_STALE => 'REBASE_STATUS_STALE',
        self::REBASE_STATUS_CONFLICTED => 'REBASE_STATUS_CONFLICTED',
        self::REBASE_STATUS_FENCED => 'REBASE_STATUS_FENCED',
        self::REBASE_STATUS_IDEMPOTENCY_CONFLICT => 'REBASE_STATUS_IDEMPOTENCY_CONFLICT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

