<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filesystem/v2/filesystem.proto

namespace Acyclic\Filesystem\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>acyclic.filesystem.v2.Resize</code>
 */
class Resize extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>uint64 logical_bytes = 2;</code>
     */
    protected $logical_bytes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *     @type int|string $logical_bytes
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Filesystem\V2\Filesystem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 logical_bytes = 2;</code>
     * @return int|string
     */
    public function getLogicalBytes()
    {
        return $this->logical_bytes;
    }

    /**
     * Generated from protobuf field <code>uint64 logical_bytes = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLogicalBytes(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->logical_bytes = $var;

        return $this;
    }

}

