#nullable enable
using System; using System.Collections; using System.IO; using System.Net.Http; using System.Text.Json; using System.Threading; using System.Threading.Tasks; using Acyclic.Actors;
internal static class CurrentCancellation { sealed class O { public string endpoint{get;set;} =""; public string token{get;set;} =""; public string caCertificate{get;set;} =""; public string controlEndpoint{get;set;} =""; } sealed class S { public int started{get;set;} public int aborted{get;set;} public int active{get;set;} }
 public static async Task Main(){var o=JsonSerializer.Deserialize<O>(await File.ReadAllTextAsync("/mnt/q/sdk/work/current-csharp-pending-options-03bb.json"))!; using var client=await AcyclicActorsUniffiMethods.ConnectActorsWithCa(o.endpoint,o.token,System.Text.Encoding.UTF8.GetBytes(o.caCertificate),null,CancellationToken.None); using var http=new HttpClient(); var peaks=""; for(int i=0;i<3;i++){using var cts=new CancellationTokenSource(); var op=client.InspectActor(new InspectActorRequest($"pending-csharp-token-{i}"),null,cts.Token); await Wait(http,o.controlEndpoint,s=>s.started>=i+1&&s.active==1); var p=Count(); if(p<1) throw new Exception($"map did not grow {p}"); cts.Cancel(); bool ok=false; try{await op;}catch(OperationCanceledException e){ok=e.CancellationToken==cts.Token;} if(!ok)throw new Exception("wrong cancellation exception/token"); var after=await Wait(http,o.controlEndpoint,s=>s.aborted>=i+1&&s.active==0); if(Count()!=0)throw new Exception($"map leak {Count()}"); peaks=peaks.Length==0?p.ToString():peaks+","+p; Console.WriteLine($"ITERATION {i+1}: map baseline=0 pending={p} after=0 state={JsonSerializer.Serialize(after)}");} Console.WriteLine($"CURRENT_03BB_CANCELLATIONTOKEN_PASS baseline=0 peaks={peaks}"); }
 static int Count(){var t=typeof(ActorsClient).Assembly.GetType("Acyclic.Actors._UniFFIAsync")!; var f=t.GetField("_async_handle_map",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic)!; var m=f.GetValue(null)!; var sf=m.GetType().GetField("_map",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic)!; return ((ICollection)sf.GetValue(m)!).Count;}
 static async Task<S> Wait(HttpClient h,string e,Func<S,bool> p){for(int i=0;i<300;i++){var s=JsonSerializer.Deserialize<S>(await h.GetStringAsync(e+"/state"))!; if(p(s))return s; await Task.Delay(10);}throw new TimeoutException();}
}


