<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workers/v1/workers.proto

namespace Acyclic\Workers\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The current durable job state, attempt, output, and failure details.
 *
 * Generated from protobuf message <code>acyclic.workers.v1.JobObservation</code>
 */
class JobObservation extends \Google\Protobuf\Internal\Message
{
    /**
     * Stable durable job identifier.
     *
     * Generated from protobuf field <code>string job_id = 1;</code>
     */
    protected $job_id = '';
    /**
     * Current durable job state.
     *
     * Generated from protobuf field <code>.acyclic.workers.v1.JobState state = 2;</code>
     */
    protected $state = 0;
    /**
     * Digest of the version resolved for execution.
     *
     * Generated from protobuf field <code>bytes resolved_sha256 = 3;</code>
     */
    protected $resolved_sha256 = '';
    /**
     * Current delivery attempt, starting at one.
     *
     * Generated from protobuf field <code>uint32 attempt = 4;</code>
     */
    protected $attempt = 0;
    /**
     * Exact accepted job output after success.
     *
     * Generated from protobuf field <code>.acyclic.workers.v1.JobResult result = 5;</code>
     */
    protected $result = null;
    /**
     * Stable terminal failure code.
     *
     * Generated from protobuf field <code>string failure_code = 6;</code>
     */
    protected $failure_code = '';
    /**
     * Whether cancellation has been requested.
     *
     * Generated from protobuf field <code>bool cancellation_requested = 7;</code>
     */
    protected $cancellation_requested = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $job_id
     *           Stable durable job identifier.
     *     @type int $state
     *           Current durable job state.
     *     @type string $resolved_sha256
     *           Digest of the version resolved for execution.
     *     @type int $attempt
     *           Current delivery attempt, starting at one.
     *     @type \Acyclic\Workers\V1\JobResult $result
     *           Exact accepted job output after success.
     *     @type string $failure_code
     *           Stable terminal failure code.
     *     @type bool $cancellation_requested
     *           Whether cancellation has been requested.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Workers\V1\Workers::initOnce();
        parent::__construct($data);
    }

    /**
     * Stable durable job identifier.
     *
     * Generated from protobuf field <code>string job_id = 1;</code>
     * @return string
     */
    public function getJobId()
    {
        return $this->job_id;
    }

    /**
     * Stable durable job identifier.
     *
     * Generated from protobuf field <code>string job_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJobId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->job_id = $var;

        return $this;
    }

    /**
     * Current durable job state.
     *
     * Generated from protobuf field <code>.acyclic.workers.v1.JobState state = 2;</code>
     * @return int one of the values in {@see \Acyclic\Workers\V1\JobState}
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Current durable job state.
     *
     * Generated from protobuf field <code>.acyclic.workers.v1.JobState state = 2;</code>
     * @param int $var one of the values in {@see \Acyclic\Workers\V1\JobState}
     * @return $this
     */
    public function setState(int $var)
    {
        GPBUtil::checkEnum($var, \Acyclic\Workers\V1\JobState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Digest of the version resolved for execution.
     *
     * Generated from protobuf field <code>bytes resolved_sha256 = 3;</code>
     * @return string
     */
    public function getResolvedSha256()
    {
        return $this->resolved_sha256;
    }

    /**
     * Digest of the version resolved for execution.
     *
     * Generated from protobuf field <code>bytes resolved_sha256 = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setResolvedSha256(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->resolved_sha256 = $var;

        return $this;
    }

    /**
     * Current delivery attempt, starting at one.
     *
     * Generated from protobuf field <code>uint32 attempt = 4;</code>
     * @return int
     */
    public function getAttempt()
    {
        return $this->attempt;
    }

    /**
     * Current delivery attempt, starting at one.
     *
     * Generated from protobuf field <code>uint32 attempt = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAttempt(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->attempt = $var;

        return $this;
    }

    /**
     * Exact accepted job output after success.
     *
     * Generated from protobuf field <code>.acyclic.workers.v1.JobResult result = 5;</code>
     * @return \Acyclic\Workers\V1\JobResult|null
     */
    public function getResult()
    {
        return $this->result;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Exact accepted job output after success.
     *
     * Generated from protobuf field <code>.acyclic.workers.v1.JobResult result = 5;</code>
     * @param \Acyclic\Workers\V1\JobResult $var
     * @return $this
     */
    public function setResult(\Acyclic\Workers\V1\JobResult|null $var)
    {
        $this->result = $var;

        return $this;
    }

    /**
     * Stable terminal failure code.
     *
     * Generated from protobuf field <code>string failure_code = 6;</code>
     * @return string
     */
    public function getFailureCode()
    {
        return $this->failure_code;
    }

    /**
     * Stable terminal failure code.
     *
     * Generated from protobuf field <code>string failure_code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFailureCode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->failure_code = $var;

        return $this;
    }

    /**
     * Whether cancellation has been requested.
     *
     * Generated from protobuf field <code>bool cancellation_requested = 7;</code>
     * @return bool
     */
    public function getCancellationRequested()
    {
        return $this->cancellation_requested;
    }

    /**
     * Whether cancellation has been requested.
     *
     * Generated from protobuf field <code>bool cancellation_requested = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setCancellationRequested(bool $var)
    {
        $this->cancellation_requested = $var;

        return $this;
    }

}

