<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workers/v1/workers.proto

namespace Acyclic\Workers\V1;

use UnexpectedValueException;

/**
 * Lifecycle state of a durable Worker job.
 *
 * Protobuf type <code>acyclic.workers.v1.JobState</code>
 */
class JobState
{
    /**
     * Generated from protobuf enum <code>JOB_STATE_UNSPECIFIED = 0;</code>
     */
    const JOB_STATE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>JOB_STATE_ACCEPTED = 1;</code>
     */
    const JOB_STATE_ACCEPTED = 1;
    /**
     * Generated from protobuf enum <code>JOB_STATE_RUNNING = 2;</code>
     */
    const JOB_STATE_RUNNING = 2;
    /**
     * Generated from protobuf enum <code>JOB_STATE_SUCCEEDED = 3;</code>
     */
    const JOB_STATE_SUCCEEDED = 3;
    /**
     * Generated from protobuf enum <code>JOB_STATE_FAILED = 4;</code>
     */
    const JOB_STATE_FAILED = 4;
    /**
     * Generated from protobuf enum <code>JOB_STATE_CANCELLED = 5;</code>
     */
    const JOB_STATE_CANCELLED = 5;

    private static $valueToName = [
        self::JOB_STATE_UNSPECIFIED => 'JOB_STATE_UNSPECIFIED',
        self::JOB_STATE_ACCEPTED => 'JOB_STATE_ACCEPTED',
        self::JOB_STATE_RUNNING => 'JOB_STATE_RUNNING',
        self::JOB_STATE_SUCCEEDED => 'JOB_STATE_SUCCEEDED',
        self::JOB_STATE_FAILED => 'JOB_STATE_FAILED',
        self::JOB_STATE_CANCELLED => 'JOB_STATE_CANCELLED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

