<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workers/v1/workers.proto

namespace Acyclic\Workers\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Job input supplied inline or by a retained object reference.
 *
 * Generated from protobuf message <code>acyclic.workers.v1.Payload</code>
 */
class Payload extends \Google\Protobuf\Internal\Message
{
    protected $source;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $inline_bytes
     *           Input bytes retained directly with the job.
     *     @type \Acyclic\Workers\V1\ObjectRef $object
     *           Input object retained at durable job acceptance.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Workers\V1\Workers::initOnce();
        parent::__construct($data);
    }

    /**
     * Input bytes retained directly with the job.
     *
     * Generated from protobuf field <code>bytes inline_bytes = 1;</code>
     * @return string
     */
    public function getInlineBytes()
    {
        return $this->readOneof(1);
    }

    public function hasInlineBytes()
    {
        return $this->hasOneof(1);
    }

    /**
     * Input bytes retained directly with the job.
     *
     * Generated from protobuf field <code>bytes inline_bytes = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInlineBytes(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Input object retained at durable job acceptance.
     *
     * Generated from protobuf field <code>.acyclic.workers.v1.ObjectRef object = 2;</code>
     * @return \Acyclic\Workers\V1\ObjectRef|null
     */
    public function getObject()
    {
        return $this->readOneof(2);
    }

    public function hasObject()
    {
        return $this->hasOneof(2);
    }

    /**
     * Input object retained at durable job acceptance.
     *
     * Generated from protobuf field <code>.acyclic.workers.v1.ObjectRef object = 2;</code>
     * @param \Acyclic\Workers\V1\ObjectRef $var
     * @return $this
     */
    public function setObject(\Acyclic\Workers\V1\ObjectRef|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getSource()
    {
        return $this->whichOneof("source");
    }

}

