<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workers/v1/workers.proto

namespace Acyclic\Workers\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Publishes exact JavaScript module bytes after optional digest validation.
 *
 * Generated from protobuf message <code>acyclic.workers.v1.PublishVersionRequest</code>
 */
class PublishVersionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Exact JavaScript module bytes to publish.
     *
     * Generated from protobuf field <code>bytes javascript_module = 1;</code>
     */
    protected $javascript_module = '';
    /**
     * Optional digest that must match the published bytes.
     *
     * Generated from protobuf field <code>bytes expected_sha256 = 2;</code>
     */
    protected $expected_sha256 = '';
    /**
     * Client key used to make a mutation idempotent.
     *
     * Generated from protobuf field <code>string idempotency_key = 3;</code>
     */
    protected $idempotency_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $javascript_module
     *           Exact JavaScript module bytes to publish.
     *     @type string $expected_sha256
     *           Optional digest that must match the published bytes.
     *     @type string $idempotency_key
     *           Client key used to make a mutation idempotent.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Workers\V1\Workers::initOnce();
        parent::__construct($data);
    }

    /**
     * Exact JavaScript module bytes to publish.
     *
     * Generated from protobuf field <code>bytes javascript_module = 1;</code>
     * @return string
     */
    public function getJavascriptModule()
    {
        return $this->javascript_module;
    }

    /**
     * Exact JavaScript module bytes to publish.
     *
     * Generated from protobuf field <code>bytes javascript_module = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJavascriptModule(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->javascript_module = $var;

        return $this;
    }

    /**
     * Optional digest that must match the published bytes.
     *
     * Generated from protobuf field <code>bytes expected_sha256 = 2;</code>
     * @return string
     */
    public function getExpectedSha256()
    {
        return $this->expected_sha256;
    }

    /**
     * Optional digest that must match the published bytes.
     *
     * Generated from protobuf field <code>bytes expected_sha256 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setExpectedSha256(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->expected_sha256 = $var;

        return $this;
    }

    /**
     * Client key used to make a mutation idempotent.
     *
     * Generated from protobuf field <code>string idempotency_key = 3;</code>
     * @return string
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    /**
     * Client key used to make a mutation idempotent.
     *
     * Generated from protobuf field <code>string idempotency_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIdempotencyKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->idempotency_key = $var;

        return $this;
    }

}

