<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workers/v1/workers.proto

namespace Acyclic\Workers\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The immutable version identity created by publication.
 *
 * Generated from protobuf message <code>acyclic.workers.v1.PublishVersionResponse</code>
 */
class PublishVersionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Immutable version selected by the deployment.
     *
     * Generated from protobuf field <code>.acyclic.workers.v1.CodeVersion version = 1;</code>
     */
    protected $version = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Workers\V1\CodeVersion $version
     *           Immutable version selected by the deployment.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Workers\V1\Workers::initOnce();
        parent::__construct($data);
    }

    /**
     * Immutable version selected by the deployment.
     *
     * Generated from protobuf field <code>.acyclic.workers.v1.CodeVersion version = 1;</code>
     * @return \Acyclic\Workers\V1\CodeVersion|null
     */
    public function getVersion()
    {
        return $this->version;
    }

    public function hasVersion()
    {
        return isset($this->version);
    }

    public function clearVersion()
    {
        unset($this->version);
    }

    /**
     * Immutable version selected by the deployment.
     *
     * Generated from protobuf field <code>.acyclic.workers.v1.CodeVersion version = 1;</code>
     * @param \Acyclic\Workers\V1\CodeVersion $var
     * @return $this
     */
    public function setVersion(\Acyclic\Workers\V1\CodeVersion|null $var)
    {
        $this->version = $var;

        return $this;
    }

}

