<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workers/v1/workers.proto

namespace Acyclic\Workers\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Selects an immutable version for an alias with optional compare-and-swap revision.
 *
 * Generated from protobuf message <code>acyclic.workers.v1.SelectDeploymentRequest</code>
 */
class SelectDeploymentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Mutable deployment alias.
     *
     * Generated from protobuf field <code>string alias = 1;</code>
     */
    protected $alias = '';
    /**
     * Immutable version digest.
     *
     * Generated from protobuf field <code>bytes version_sha256 = 2;</code>
     */
    protected $version_sha256 = '';
    /**
     * Optional current deployment revision required for selection.
     *
     * Generated from protobuf field <code>optional uint64 expected_revision = 3;</code>
     */
    protected $expected_revision = null;
    /**
     * Client key used to make a mutation idempotent.
     *
     * Generated from protobuf field <code>string idempotency_key = 4;</code>
     */
    protected $idempotency_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $alias
     *           Mutable deployment alias.
     *     @type string $version_sha256
     *           Immutable version digest.
     *     @type int|string $expected_revision
     *           Optional current deployment revision required for selection.
     *     @type string $idempotency_key
     *           Client key used to make a mutation idempotent.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Workers\V1\Workers::initOnce();
        parent::__construct($data);
    }

    /**
     * Mutable deployment alias.
     *
     * Generated from protobuf field <code>string alias = 1;</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Mutable deployment alias.
     *
     * Generated from protobuf field <code>string alias = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAlias(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->alias = $var;

        return $this;
    }

    /**
     * Immutable version digest.
     *
     * Generated from protobuf field <code>bytes version_sha256 = 2;</code>
     * @return string
     */
    public function getVersionSha256()
    {
        return $this->version_sha256;
    }

    /**
     * Immutable version digest.
     *
     * Generated from protobuf field <code>bytes version_sha256 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersionSha256(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->version_sha256 = $var;

        return $this;
    }

    /**
     * Optional current deployment revision required for selection.
     *
     * Generated from protobuf field <code>optional uint64 expected_revision = 3;</code>
     * @return int|string
     */
    public function getExpectedRevision()
    {
        return isset($this->expected_revision) ? $this->expected_revision : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasExpectedRevision()
    {
        return isset($this->expected_revision);
    }

    public function clearExpectedRevision()
    {
        unset($this->expected_revision);
    }

    /**
     * Optional current deployment revision required for selection.
     *
     * Generated from protobuf field <code>optional uint64 expected_revision = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpectedRevision(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->expected_revision = $var;

        return $this;
    }

    /**
     * Client key used to make a mutation idempotent.
     *
     * Generated from protobuf field <code>string idempotency_key = 4;</code>
     * @return string
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    /**
     * Client key used to make a mutation idempotent.
     *
     * Generated from protobuf field <code>string idempotency_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIdempotencyKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->idempotency_key = $var;

        return $this;
    }

}

