<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness/v2/harness.proto

namespace Acyclic\Harness\V2;

use UnexpectedValueException;

/**
 * Protobuf type <code>acyclic.harness.v2.AggregateKind</code>
 */
class AggregateKind
{
    /**
     * Generated from protobuf enum <code>AGGREGATE_KIND_UNSPECIFIED = 0;</code>
     */
    const AGGREGATE_KIND_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>AGGREGATE_KIND_AGENT = 1;</code>
     */
    const AGGREGATE_KIND_AGENT = 1;
    /**
     * Generated from protobuf enum <code>AGGREGATE_KIND_CONVERSATION = 2;</code>
     */
    const AGGREGATE_KIND_CONVERSATION = 2;
    /**
     * Generated from protobuf enum <code>AGGREGATE_KIND_SESSION = 3;</code>
     */
    const AGGREGATE_KIND_SESSION = 3;
    /**
     * Generated from protobuf enum <code>AGGREGATE_KIND_TURN = 4;</code>
     */
    const AGGREGATE_KIND_TURN = 4;
    /**
     * Generated from protobuf enum <code>AGGREGATE_KIND_TASK = 5;</code>
     */
    const AGGREGATE_KIND_TASK = 5;

    private static $valueToName = [
        self::AGGREGATE_KIND_UNSPECIFIED => 'AGGREGATE_KIND_UNSPECIFIED',
        self::AGGREGATE_KIND_AGENT => 'AGGREGATE_KIND_AGENT',
        self::AGGREGATE_KIND_CONVERSATION => 'AGGREGATE_KIND_CONVERSATION',
        self::AGGREGATE_KIND_SESSION => 'AGGREGATE_KIND_SESSION',
        self::AGGREGATE_KIND_TURN => 'AGGREGATE_KIND_TURN',
        self::AGGREGATE_KIND_TASK => 'AGGREGATE_KIND_TASK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

