<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness/v2/harness.proto

namespace Acyclic\Harness\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>acyclic.harness.v2.ApplyResponse</code>
 */
class ApplyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.ApplyState state = 1;</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.EventEnvelope event = 2;</code>
     */
    protected $event = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $state
     *     @type \Acyclic\Harness\V2\EventEnvelope $event
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Harness\V2\Harness::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.ApplyState state = 1;</code>
     * @return int one of the values in {@see \Acyclic\Harness\V2\ApplyState}
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.ApplyState state = 1;</code>
     * @param int $var one of the values in {@see \Acyclic\Harness\V2\ApplyState}
     * @return $this
     */
    public function setState(int $var)
    {
        GPBUtil::checkEnum($var, \Acyclic\Harness\V2\ApplyState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.EventEnvelope event = 2;</code>
     * @return \Acyclic\Harness\V2\EventEnvelope|null
     */
    public function getEvent()
    {
        return $this->event;
    }

    public function hasEvent()
    {
        return isset($this->event);
    }

    public function clearEvent()
    {
        unset($this->event);
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.EventEnvelope event = 2;</code>
     * @param \Acyclic\Harness\V2\EventEnvelope $var
     * @return $this
     */
    public function setEvent(\Acyclic\Harness\V2\EventEnvelope|null $var)
    {
        $this->event = $var;

        return $this;
    }

}

