<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness/v2/harness.proto

namespace Acyclic\Harness\V2;

use UnexpectedValueException;

/**
 * Protobuf type <code>acyclic.harness.v2.ApplyState</code>
 */
class ApplyState
{
    /**
     * Generated from protobuf enum <code>APPLY_STATE_UNSPECIFIED = 0;</code>
     */
    const APPLY_STATE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>APPLY_STATE_APPLIED = 1;</code>
     */
    const APPLY_STATE_APPLIED = 1;
    /**
     * Generated from protobuf enum <code>APPLY_STATE_REPLAYED = 2;</code>
     */
    const APPLY_STATE_REPLAYED = 2;

    private static $valueToName = [
        self::APPLY_STATE_UNSPECIFIED => 'APPLY_STATE_UNSPECIFIED',
        self::APPLY_STATE_APPLIED => 'APPLY_STATE_APPLIED',
        self::APPLY_STATE_REPLAYED => 'APPLY_STATE_REPLAYED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

