<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness/v2/harness.proto

namespace Acyclic\Harness\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>acyclic.harness.v2.Attachment</code>
 */
class Attachment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.FileRef file = 1;</code>
     */
    protected $file = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Harness\V2\FileRef $file
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Harness\V2\Harness::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.FileRef file = 1;</code>
     * @return \Acyclic\Harness\V2\FileRef|null
     */
    public function getFile()
    {
        return $this->file;
    }

    public function hasFile()
    {
        return isset($this->file);
    }

    public function clearFile()
    {
        unset($this->file);
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.FileRef file = 1;</code>
     * @param \Acyclic\Harness\V2\FileRef $var
     * @return $this
     */
    public function setFile(\Acyclic\Harness\V2\FileRef|null $var)
    {
        $this->file = $var;

        return $this;
    }

}

