<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness/v2/harness.proto

namespace Acyclic\Harness\V2;

use UnexpectedValueException;

/**
 * Protobuf type <code>acyclic.harness.v2.BatchGroupPolicy</code>
 */
class BatchGroupPolicy
{
    /**
     * Generated from protobuf enum <code>BATCH_GROUP_POLICY_UNSPECIFIED = 0;</code>
     */
    const BATCH_GROUP_POLICY_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>BATCH_GROUP_POLICY_COLLECT_ALL = 1;</code>
     */
    const BATCH_GROUP_POLICY_COLLECT_ALL = 1;
    /**
     * Generated from protobuf enum <code>BATCH_GROUP_POLICY_CANCEL_ON_FAILURE = 2;</code>
     */
    const BATCH_GROUP_POLICY_CANCEL_ON_FAILURE = 2;

    private static $valueToName = [
        self::BATCH_GROUP_POLICY_UNSPECIFIED => 'BATCH_GROUP_POLICY_UNSPECIFIED',
        self::BATCH_GROUP_POLICY_COLLECT_ALL => 'BATCH_GROUP_POLICY_COLLECT_ALL',
        self::BATCH_GROUP_POLICY_CANCEL_ON_FAILURE => 'BATCH_GROUP_POLICY_CANCEL_ON_FAILURE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

