<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness/v2/harness.proto

namespace Acyclic\Harness\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>acyclic.harness.v2.EventEnvelope</code>
 */
class EventEnvelope extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.acyclic.protocol.v1.ProtocolIdentity protocol = 1;</code>
     */
    protected $protocol = null;
    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.Authority authority = 2;</code>
     */
    protected $authority = null;
    /**
     * Generated from protobuf field <code>uint64 revision = 3;</code>
     */
    protected $revision = 0;
    /**
     * Generated from protobuf field <code>string operation_id = 4;</code>
     */
    protected $operation_id = '';
    /**
     * Generated from protobuf field <code>bytes intent_digest = 5;</code>
     */
    protected $intent_digest = '';
    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.RecordedScope scope = 6;</code>
     */
    protected $scope = null;
    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.EventReference causal_parent = 7;</code>
     */
    protected $causal_parent = null;
    /**
     * Generated from protobuf field <code>string event_type = 8;</code>
     */
    protected $event_type = '';
    /**
     * Generated from protobuf field <code>bytes canonical_payload_json = 9;</code>
     */
    protected $canonical_payload_json = '';
    /**
     * Generated from protobuf field <code>bytes attestation = 10;</code>
     */
    protected $attestation = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Protocol\V1\ProtocolIdentity $protocol
     *     @type \Acyclic\Harness\V2\Authority $authority
     *     @type int|string $revision
     *     @type string $operation_id
     *     @type string $intent_digest
     *     @type \Acyclic\Harness\V2\RecordedScope $scope
     *     @type \Acyclic\Harness\V2\EventReference $causal_parent
     *     @type string $event_type
     *     @type string $canonical_payload_json
     *     @type string $attestation
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Harness\V2\Harness::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.acyclic.protocol.v1.ProtocolIdentity protocol = 1;</code>
     * @return \Acyclic\Protocol\V1\ProtocolIdentity|null
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    public function hasProtocol()
    {
        return isset($this->protocol);
    }

    public function clearProtocol()
    {
        unset($this->protocol);
    }

    /**
     * Generated from protobuf field <code>.acyclic.protocol.v1.ProtocolIdentity protocol = 1;</code>
     * @param \Acyclic\Protocol\V1\ProtocolIdentity $var
     * @return $this
     */
    public function setProtocol(\Acyclic\Protocol\V1\ProtocolIdentity|null $var)
    {
        $this->protocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.Authority authority = 2;</code>
     * @return \Acyclic\Harness\V2\Authority|null
     */
    public function getAuthority()
    {
        return $this->authority;
    }

    public function hasAuthority()
    {
        return isset($this->authority);
    }

    public function clearAuthority()
    {
        unset($this->authority);
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.Authority authority = 2;</code>
     * @param \Acyclic\Harness\V2\Authority $var
     * @return $this
     */
    public function setAuthority(\Acyclic\Harness\V2\Authority|null $var)
    {
        $this->authority = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 revision = 3;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * Generated from protobuf field <code>uint64 revision = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->revision = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string operation_id = 4;</code>
     * @return string
     */
    public function getOperationId()
    {
        return $this->operation_id;
    }

    /**
     * Generated from protobuf field <code>string operation_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->operation_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes intent_digest = 5;</code>
     * @return string
     */
    public function getIntentDigest()
    {
        return $this->intent_digest;
    }

    /**
     * Generated from protobuf field <code>bytes intent_digest = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setIntentDigest(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->intent_digest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.RecordedScope scope = 6;</code>
     * @return \Acyclic\Harness\V2\RecordedScope|null
     */
    public function getScope()
    {
        return $this->scope;
    }

    public function hasScope()
    {
        return isset($this->scope);
    }

    public function clearScope()
    {
        unset($this->scope);
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.RecordedScope scope = 6;</code>
     * @param \Acyclic\Harness\V2\RecordedScope $var
     * @return $this
     */
    public function setScope(\Acyclic\Harness\V2\RecordedScope|null $var)
    {
        $this->scope = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.EventReference causal_parent = 7;</code>
     * @return \Acyclic\Harness\V2\EventReference|null
     */
    public function getCausalParent()
    {
        return $this->causal_parent;
    }

    public function hasCausalParent()
    {
        return isset($this->causal_parent);
    }

    public function clearCausalParent()
    {
        unset($this->causal_parent);
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.EventReference causal_parent = 7;</code>
     * @param \Acyclic\Harness\V2\EventReference $var
     * @return $this
     */
    public function setCausalParent(\Acyclic\Harness\V2\EventReference|null $var)
    {
        $this->causal_parent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string event_type = 8;</code>
     * @return string
     */
    public function getEventType()
    {
        return $this->event_type;
    }

    /**
     * Generated from protobuf field <code>string event_type = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setEventType(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->event_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes canonical_payload_json = 9;</code>
     * @return string
     */
    public function getCanonicalPayloadJson()
    {
        return $this->canonical_payload_json;
    }

    /**
     * Generated from protobuf field <code>bytes canonical_payload_json = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCanonicalPayloadJson(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->canonical_payload_json = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes attestation = 10;</code>
     * @return string
     */
    public function getAttestation()
    {
        return $this->attestation;
    }

    /**
     * Generated from protobuf field <code>bytes attestation = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setAttestation(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->attestation = $var;

        return $this;
    }

}

