<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness/v2/harness.proto

namespace Acyclic\Harness\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>acyclic.harness.v2.ExtensionAdmission</code>
 */
class ExtensionAdmission extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.EventReference source = 1;</code>
     */
    protected $source = null;
    /**
     * Generated from protobuf field <code>repeated .acyclic.harness.v2.ExtensionDependency selected = 2;</code>
     */
    private $selected;
    /**
     * Generated from protobuf field <code>repeated .acyclic.harness.v2.ExtensionConfiguration configurations = 3;</code>
     */
    private $configurations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Harness\V2\EventReference $source
     *     @type \Acyclic\Harness\V2\ExtensionDependency[] $selected
     *     @type \Acyclic\Harness\V2\ExtensionConfiguration[] $configurations
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Harness\V2\Harness::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.EventReference source = 1;</code>
     * @return \Acyclic\Harness\V2\EventReference|null
     */
    public function getSource()
    {
        return $this->source;
    }

    public function hasSource()
    {
        return isset($this->source);
    }

    public function clearSource()
    {
        unset($this->source);
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.EventReference source = 1;</code>
     * @param \Acyclic\Harness\V2\EventReference $var
     * @return $this
     */
    public function setSource(\Acyclic\Harness\V2\EventReference|null $var)
    {
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .acyclic.harness.v2.ExtensionDependency selected = 2;</code>
     * @return RepeatedField<\Acyclic\Harness\V2\ExtensionDependency>
     */
    public function getSelected()
    {
        return $this->selected;
    }

    /**
     * Generated from protobuf field <code>repeated .acyclic.harness.v2.ExtensionDependency selected = 2;</code>
     * @param \Acyclic\Harness\V2\ExtensionDependency[] $var
     * @return $this
     */
    public function setSelected(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Acyclic\Harness\V2\ExtensionDependency::class);
        $this->selected = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .acyclic.harness.v2.ExtensionConfiguration configurations = 3;</code>
     * @return RepeatedField<\Acyclic\Harness\V2\ExtensionConfiguration>
     */
    public function getConfigurations()
    {
        return $this->configurations;
    }

    /**
     * Generated from protobuf field <code>repeated .acyclic.harness.v2.ExtensionConfiguration configurations = 3;</code>
     * @param \Acyclic\Harness\V2\ExtensionConfiguration[] $var
     * @return $this
     */
    public function setConfigurations(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Acyclic\Harness\V2\ExtensionConfiguration::class);
        $this->configurations = $arr;

        return $this;
    }

}

