<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harness/v2/harness.proto

namespace Acyclic\Harness\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>acyclic.harness.v2.ReferencedAttachments</code>
 */
class ReferencedAttachments extends \Google\Protobuf\Internal\Message
{
    protected $source;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Harness\V2\AttachmentItems $inline_items
     *     @type \Acyclic\Harness\V2\AttachmentManifest $manifest
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Harness\V2\Harness::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.AttachmentItems inline_items = 1;</code>
     * @return \Acyclic\Harness\V2\AttachmentItems|null
     */
    public function getInlineItems()
    {
        return $this->readOneof(1);
    }

    public function hasInlineItems()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.AttachmentItems inline_items = 1;</code>
     * @param \Acyclic\Harness\V2\AttachmentItems $var
     * @return $this
     */
    public function setInlineItems(\Acyclic\Harness\V2\AttachmentItems|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.AttachmentManifest manifest = 2;</code>
     * @return \Acyclic\Harness\V2\AttachmentManifest|null
     */
    public function getManifest()
    {
        return $this->readOneof(2);
    }

    public function hasManifest()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.acyclic.harness.v2.AttachmentManifest manifest = 2;</code>
     * @param \Acyclic\Harness\V2\AttachmentManifest $var
     * @return $this
     */
    public function setManifest(\Acyclic\Harness\V2\AttachmentManifest|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getSource()
    {
        return $this->whichOneof("source");
    }

}

