import type {
  BucketId, BucketRef, ByteRange, Condition, ETag, IdempotencyKey, ListPage, MultipartProvider,
  MultipartUpload, ObjectMetadata, ObjectsProvider, ObjectVersion, ReadTarget, SnapshotId,
  SnapshotRef, StoredObject, UploadedPart, UploadId, VersionId,
} from "./index.js";

interface VersionEntry { readonly descriptor: ObjectVersion; readonly body: Uint8Array }
interface BucketState { readonly reference: BucketRef; readonly objects: Map<string, VersionEntry[]> }
interface SnapshotState { readonly reference: SnapshotRef; readonly objects: Map<string, VersionEntry[]> }
interface UploadState { readonly upload: MultipartUpload; readonly parts: Map<number, VersionEntry> }
type ListingItem = { readonly kind: "entry"; readonly value: ListPage["entries"][number] } | { readonly kind: "prefix"; readonly value: string };
interface ListingState { readonly fingerprint: string; readonly items: readonly ListingItem[]; readonly expiresAt: number }

/** Fully versioned process-local provider for tests, browsers, and offline agents. */
export class MemoryObjectsProvider implements ObjectsProvider, MultipartProvider {
  readonly #buckets = new Map<BucketId, BucketState>();
  readonly #bucketNames = new Map<string, BucketId>();
  readonly #snapshots = new Map<SnapshotId, SnapshotState>();
  readonly #uploads = new Map<UploadId, UploadState>();
  readonly #replays = new Map<IdempotencyKey, { readonly intent: string; readonly value: unknown }>();
  readonly #listings = new Map<string, ListingState>();

  async createBucket(name: string, key?: IdempotencyKey): Promise<BucketRef> { return this.#mutate(key, `create:${name}`, () => { if (!name) throw new ObjectError("invalid_name", "bucket name is required"); if (this.#bucketNames.has(name)) throw new ObjectError("bucket_exists", "bucket name already exists"); const reference = { bucketId: id<BucketId>("bucket"), name }; this.#buckets.set(reference.bucketId, { reference, objects: new Map() }); this.#bucketNames.set(name, reference.bucketId); return reference; }); }
  async headBucket(bucket: BucketRef): Promise<BucketRef> { return this.#bucket(bucket).reference; }
  async deleteBucket(bucket: BucketRef, key?: IdempotencyKey): Promise<boolean> { return this.#mutate(key, `delete-bucket:${bucket.bucketId}`, () => { const state = this.#bucket(bucket); if ([...state.objects.values()].some(versions => versions.length > 0) || [...this.#uploads.values()].some(value => value.upload.bucket.bucketId === bucket.bucketId)) throw new ObjectError("bucket_not_empty", "bucket retains object versions or multipart uploads"); this.#bucketNames.delete(state.reference.name); return this.#buckets.delete(bucket.bucketId); }); }
  async put(bucket: BucketRef, objectKey: string, body: Uint8Array, metadata: ObjectMetadata, condition?: Condition, key?: IdempotencyKey): Promise<ObjectVersion> { return this.#mutate(key, canonical(["put", bucket.bucketId, objectKey, body, metadata, condition]), () => this.#put(this.#bucket(bucket), objectKey, body, metadata, condition)); }
  async head(target: ReadTarget, objectKey: string, versionId?: VersionId): Promise<ObjectVersion> { const versions = this.#objects(target).get(objectKey) ?? []; const entry = versionId ? versions.find(value => value.descriptor.versionId === versionId) : current(versions); if (!entry || entry.descriptor.deleteMarker) throw new ObjectError("not_found", "object is not visible"); return clone(entry.descriptor); }
  async get(target: ReadTarget, objectKey: string, versionId?: VersionId, range?: Omit<ByteRange, "total">): Promise<StoredObject> {
    const versions = this.#objects(target).get(objectKey) ?? []; const entry = versionId ? versions.find(value => value.descriptor.versionId === versionId) : current(versions);
    if (!entry || entry.descriptor.deleteMarker) throw new ObjectError("not_found", "object is not visible");
    if (!range) return { version: clone(entry.descriptor), body: entry.body.slice() };
    if (!Number.isSafeInteger(range.start) || !Number.isSafeInteger(range.endExclusive) || range.start < 0 || range.endExclusive <= range.start || range.endExclusive > entry.body.byteLength) throw new ObjectError("invalid_range", "range is outside the object");
    return { version: clone(entry.descriptor), body: entry.body.slice(range.start, range.endExclusive), contentRange: { ...range, total: entry.body.byteLength } };
  }
  async delete(bucket: BucketRef, objectKey: string, versionId?: VersionId, condition?: Condition, key?: IdempotencyKey): Promise<{ readonly existed: boolean; readonly marker?: ObjectVersion }> { return this.#mutate(key, canonical(["delete", bucket.bucketId, objectKey, versionId, condition]), () => { const state = this.#bucket(bucket); const versions = state.objects.get(objectKey) ?? []; this.#condition(versions, condition); if (versionId) { const index = versions.findIndex(value => value.descriptor.versionId === versionId); if (index < 0) return { existed: false }; versions.splice(index, 1); return { existed: true }; } const descriptor = this.#descriptor(new Uint8Array(), emptyMetadata, true); versions.push({ descriptor, body: new Uint8Array() }); state.objects.set(objectKey, versions); return { existed: currentVisible(versions.slice(0, -1)) !== undefined, marker: descriptor }; }); }
  async list(target: ReadTarget, prefix: string, delimiter: string | undefined, versions: boolean, pageSize: number, continuation?: string): Promise<ListPage> {
    if (!Number.isSafeInteger(pageSize) || pageSize < 1 || pageSize > 1000) throw new ObjectError("invalid_page_size", "page size must be 1..1000");
    const fingerprint = canonical([targetId(target), prefix, delimiter, versions]); let listingId: string; let start: number; let listing: ListingState;
    if (continuation) { const [idValue, offsetValue] = continuation.split(":", 2); listingId = idValue ?? ""; start = Number.parseInt(offsetValue ?? "", 10); const retained = this.#listings.get(listingId); if (!retained || retained.expiresAt <= Date.now() || retained.fingerprint !== fingerprint || !Number.isSafeInteger(start) || start < 0) throw new ObjectError("invalid_continuation", "continuation is unavailable, expired, or bound to different listing arguments"); listing = retained; }
    else { const items: ListingItem[] = []; const prefixes = new Set<string>(); for (const [objectKey, history] of [...this.#objects(target)].sort(([a], [b]) => a.localeCompare(b))) { if (!objectKey.startsWith(prefix)) continue; const remainder = objectKey.slice(prefix.length); const split = delimiter ? remainder.indexOf(delimiter) : -1; if (split >= 0 && delimiter) { const commonPrefix = prefix + remainder.slice(0, split + delimiter.length); if (!prefixes.has(commonPrefix)) { prefixes.add(commonPrefix); items.push({ kind: "prefix", value: commonPrefix }); } continue; } const selected = versions ? [...history].reverse() : [current(history)].filter((value): value is VersionEntry => value !== undefined); for (const entry of selected) if (versions || !entry.descriptor.deleteMarker) items.push({ kind: "entry", value: { objectKey, version: clone(entry.descriptor) } }); } listingId = `listing_${crypto.randomUUID()}`; start = 0; listing = { fingerprint, items, expiresAt: Date.now() + 86_400_000 }; this.#listings.set(listingId, listing); }
    const items = listing.items.slice(start, start + pageSize); const next = start + items.length; return { entries: items.filter((item): item is Extract<ListingItem, { readonly kind: "entry" }> => item.kind === "entry").map(item => item.value), commonPrefixes: items.filter((item): item is Extract<ListingItem, { readonly kind: "prefix" }> => item.kind === "prefix").map(item => item.value), continuation: next < listing.items.length ? `${listingId}:${next}` : undefined };
  }
  async snapshot(bucket: BucketRef, key?: IdempotencyKey): Promise<SnapshotRef> { return this.#mutate(key, `snapshot:${bucket.bucketId}`, () => { const source = this.#bucket(bucket); const reference = { snapshotId: id<SnapshotId>("snapshot"), sourceBucketId: bucket.bucketId }; this.#snapshots.set(reference.snapshotId, { reference, objects: copyObjects(source.objects) }); return reference; }); }
  async destroySnapshot(snapshot: SnapshotRef, key?: IdempotencyKey): Promise<boolean> { return this.#mutate(key, `destroy-snapshot:${snapshot.snapshotId}`, () => this.#snapshots.delete(snapshot.snapshotId)); }
  async fork(source: ReadTarget, destinationName: string, key?: IdempotencyKey): Promise<BucketRef> { return this.#mutate(key, `fork:${targetId(source)}:${destinationName}`, () => { if (!destinationName) throw new ObjectError("invalid_name", "bucket name is required"); if (this.#bucketNames.has(destinationName)) throw new ObjectError("bucket_exists", "bucket name already exists"); const reference = { bucketId: id<BucketId>("bucket"), name: destinationName }; this.#buckets.set(reference.bucketId, { reference, objects: copyObjects(this.#objects(source)) }); this.#bucketNames.set(destinationName, reference.bucketId); return reference; }); }

  async createMultipart(bucket: BucketRef, objectKey: string, metadata: ObjectMetadata, key?: IdempotencyKey): Promise<MultipartUpload> { return this.#mutate(key, canonical(["multipart", bucket.bucketId, objectKey, metadata]), () => { const retainedBucket = clone(this.#bucket(bucket).reference); const upload = { uploadId: id<UploadId>("upload"), bucket: retainedBucket, objectKey, metadata: clone(metadata) }; this.#uploads.set(upload.uploadId, { upload, parts: new Map() }); return clone(upload); }); }
  async uploadPart(upload: MultipartUpload, partNumber: number, body: Uint8Array, key?: IdempotencyKey): Promise<UploadedPart> { return this.#mutate(key, canonical(["upload-part", upload.uploadId, partNumber, body]), () => { if (!Number.isSafeInteger(partNumber) || partNumber < 1 || partNumber > 10_000) throw new ObjectError("invalid_part", "part number must be 1..10000"); const state = this.#upload(upload); const descriptor = this.#descriptor(body, state.upload.metadata, false); state.parts.set(partNumber, { descriptor, body: body.slice() }); return { partNumber, etag: descriptor.etag, size: body.byteLength }; }); }
  async listParts(upload: MultipartUpload): Promise<readonly UploadedPart[]> { return [...this.#upload(upload).parts].sort(([a], [b]) => a - b).map(([partNumber, value]) => ({ partNumber, etag: value.descriptor.etag, size: value.body.byteLength })); }
  async completeMultipart(upload: MultipartUpload, parts: readonly UploadedPart[], condition?: Condition, key?: IdempotencyKey): Promise<ObjectVersion> { return this.#mutate(key, canonical(["complete", upload.uploadId, parts, condition]), () => { if (parts.length < 1 || parts.length > 10_000 || parts.some((part, index) => part.partNumber < 1 || part.partNumber > 10_000 || (index > 0 && part.partNumber <= parts[index - 1]!.partNumber))) throw new ObjectError("invalid_part", "multipart manifest must contain 1..10000 unique parts in ascending order"); const state = this.#upload(upload); const bodies = parts.map(part => { const stored = state.parts.get(part.partNumber); if (!stored || stored.descriptor.etag !== part.etag || stored.body.byteLength !== part.size) throw new ObjectError("invalid_part", "multipart manifest does not match uploaded parts"); return stored.body; }); const body = concat(bodies); const retained = state.upload; const result = this.#put(this.#bucket(retained.bucket), retained.objectKey, body, retained.metadata, condition); this.#uploads.delete(upload.uploadId); return result; }); }
  async abortMultipart(upload: MultipartUpload, key?: IdempotencyKey): Promise<boolean> { return this.#mutate(key, `abort:${upload.uploadId}`, () => this.#uploads.delete(upload.uploadId)); }

  #put(bucket: BucketState, objectKey: string, body: Uint8Array, metadata: ObjectMetadata, condition?: Condition): ObjectVersion { if (!objectKey) throw new ObjectError("invalid_key", "object key is required"); const versions = bucket.objects.get(objectKey) ?? []; this.#condition(versions, condition); const descriptor = this.#descriptor(body, metadata, false); versions.push({ descriptor, body: body.slice() }); bucket.objects.set(objectKey, versions); return descriptor; }
  #descriptor(body: Uint8Array, metadata: ObjectMetadata, deleteMarker: boolean): ObjectVersion { const versionId = id<VersionId>("version"); return { versionId, etag: (`\"${contentTag(body)}\"` as ETag), size: BigInt(body.byteLength), deleteMarker, metadata: clone(metadata) }; }
  #condition(versions: readonly VersionEntry[], condition?: Condition): void { if (!condition) return; const entry = currentVisible(versions); const accepted = condition.kind === "ifAbsent" ? entry === undefined : condition.kind === "ifMatch" ? entry?.descriptor.etag === condition.etag : entry?.descriptor.versionId === condition.versionId; if (!accepted) throw new ObjectError("precondition_failed", "object condition does not hold"); }
  #objects(target: ReadTarget): Map<string, VersionEntry[]> { return target.kind === "bucket" ? this.#bucket(target.bucket).objects : this.#snapshot(target.snapshot).objects; }
  #bucket(reference: BucketRef): BucketState { const value = this.#buckets.get(reference.bucketId); if (!value || value.reference.name !== reference.name) throw new ObjectError("not_found", "bucket identity is not retained"); return value; }
  #snapshot(reference: SnapshotRef): SnapshotState { const value = this.#snapshots.get(reference.snapshotId); if (!value || value.reference.sourceBucketId !== reference.sourceBucketId) throw new ObjectError("not_found", "snapshot identity is not retained"); return value; }
  #upload(upload: MultipartUpload): UploadState { const value = this.#uploads.get(upload.uploadId); if (!value) throw new ObjectError("not_found", "multipart upload is not retained"); return value; }
  #mutate<Value>(key: IdempotencyKey | undefined, intent: string, action: () => Value): Value { if (!key) return action(); const replay = this.#replays.get(key); if (replay) { if (replay.intent !== intent) throw new ObjectError("idempotency_mismatch", "idempotency key is bound to another request"); return clone(replay.value) as Value; } const value = action(); this.#replays.set(key, { intent, value: clone(value) }); return value; }
}

export class ObjectError extends Error { constructor(readonly code: "not_found" | "precondition_failed" | "idempotency_mismatch" | "bucket_not_empty" | "bucket_exists" | "invalid_name" | "invalid_key" | "invalid_range" | "invalid_page_size" | "invalid_part" | "invalid_continuation", message: string) { super(message); } }
const emptyMetadata: ObjectMetadata = { contentType: "", contentEncoding: "", cacheControl: "", contentDisposition: "", contentLanguage: "", expiresUnixSeconds: undefined, user: new Map() };
const id = <Value extends string>(prefix: string): Value => `${prefix}:${crypto.randomUUID()}` as Value;
const current = (values: readonly VersionEntry[]): VersionEntry | undefined => values.at(-1);
const currentVisible = (values: readonly VersionEntry[]): VersionEntry | undefined => { const value = current(values); return value?.descriptor.deleteMarker ? undefined : value; };
const copyObjects = (objects: Map<string, VersionEntry[]>): Map<string, VersionEntry[]> => new Map([...objects].map(([key, values]) => [key, values.map(value => ({ descriptor: clone(value.descriptor), body: value.body.slice() }))]));
const clone = <Value>(value: Value): Value => structuredClone(value);
const targetId = (target: ReadTarget): string => target.kind === "bucket" ? target.bucket.bucketId : target.snapshot.snapshotId;
const contentTag = (bytes: Uint8Array): string => { let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte); return btoa(binary); };
const concat = (parts: readonly Uint8Array[]): Uint8Array => { const output = new Uint8Array(parts.reduce((size, part) => size + part.byteLength, 0)); let offset = 0; for (const part of parts) { output.set(part, offset); offset += part.byteLength; } return output; };
const canonical = (value: unknown): string => value instanceof Uint8Array ? `[${value.join(",")}]` : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : value instanceof Map ? canonical([...value].sort()) : value !== null && typeof value === "object" ? `{${Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(",")}}` : typeof value === "bigint" ? `"${value}"` : JSON.stringify(value);
