package main

import (
  "context"
  "crypto/sha256"
  "encoding/json"
  "fmt"
  "io"
  "os"
  "strings"
  "time"

  _ "github.com/acyclic-labs/sdk/go/gen/filesystem/v2"
  _ "github.com/acyclic-labs/sdk/go/gen/harness/v2"
  "google.golang.org/grpc"
  "google.golang.org/grpc/codes"
  "google.golang.org/grpc/credentials/insecure"
  "google.golang.org/grpc/status"
  "google.golang.org/protobuf/reflect/protoreflect"
  "google.golang.org/protobuf/reflect/protoregistry"
  "google.golang.org/protobuf/types/dynamicpb"
)

type scenario struct { Order int `json:"order"`; Family string `json:"family"`; Operation string `json:"operation"`; Seed string `json:"seed"`; KnownOutput string `json:"known_output"`; DependsOn []string `json:"depends_on"` }
type row struct { Order int `json:"order"`; Family string `json:"family"`; Operation string `json:"operation"`; Seed string `json:"seed"`; KnownOutput string `json:"known_output"`; ExecutionMode string `json:"execution_mode"`; Transport string `json:"transport"`; Status string `json:"status"`; DependsOn []string `json:"depends_on"`; RequestFrameCount, ResponseCount int `json:"request_frame_count"`; SemanticCheck string `json:"semantic_check"`; Actual map[string]any `json:"actual,omitempty"`; Error string `json:"error,omitempty"`; ElapsedMs float64 `json:"elapsed_ms"` }

func service(name string) protoreflect.ServiceDescriptor { d,e:=protoregistry.GlobalFiles.FindDescriptorByName(protoreflect.FullName(name)); if e!=nil { panic(e) }; return d.(protoreflect.ServiceDescriptor) }
func message(md protoreflect.MessageDescriptor) *dynamicpb.Message { return dynamicpb.NewMessage(md) }
func setString(m protoreflect.Message, name, value string) { if f:=m.Descriptor().Fields().ByName(protoreflect.Name(name)); f!=nil { m.Set(f,protoreflect.ValueOfString(value)) } }
func setBytes(m protoreflect.Message, name string, value []byte) { if f:=m.Descriptor().Fields().ByName(protoreflect.Name(name)); f!=nil { m.Set(f,protoreflect.ValueOfBytes(value)) } }
func setBool(m protoreflect.Message, name string, value bool) { if f:=m.Descriptor().Fields().ByName(protoreflect.Name(name)); f!=nil { m.Set(f,protoreflect.ValueOfBool(value)) } }
func fill(m protoreflect.Message, context string) {
  if string(m.Descriptor().FullName())=="acyclic.protocol.v1.ProtocolIdentity" { setString(m,"version","2"); setString(m,"descriptor_digest","8efc8c682b2ba1025b1221dd203685bdf999d04e87568fad3acdf0e428bd84cf"); return }
  if string(m.Descriptor().FullName())=="acyclic.harness.v2.Authority" { f:=m.Descriptor().Fields().ByName("kind"); if f!=nil { m.Set(f,protoreflect.ValueOfEnum(5)) }; setString(m,"id","00000000-0000-0000-0000-000000000001"); return }
  if string(m.Descriptor().FullName())=="acyclic.harness.v2.Scope" { setString(m,"id","scope:fixture"); setString(m,"issuer","fixture"); setBytes(m,"proof",bytesRepeat(1,32)); if f:=m.Descriptor().Fields().ByName("capabilities"); f!=nil { l:=m.Mutable(f).List(); l.Append(protoreflect.ValueOfString("operation:observe")); l.Append(protoreflect.ValueOfString("operation:cancel")) }; return }
  fs:=m.Descriptor().Fields(); for i:=0;i<fs.Len();i++ { f:=fs.Get(i); if f.IsMap() { continue }; if f.Kind()==protoreflect.MessageKind || f.Kind()==protoreflect.GroupKind { if f.IsList() { continue }; fill(m.Mutable(f).Message(),context); continue }; if f.IsList() { continue }; switch f.Kind() { case protoreflect.StringKind: v:="fixture-"+context; if string(f.Name())=="operation_id" { v="11111111-1111-1111-1111-111111111111" }; if string(f.Name())=="path" { v="fixture/path" }; if string(f.Name())=="idempotency_key" { v="fixture-idempotency" }; m.Set(f,protoreflect.ValueOfString(v)); case protoreflect.BytesKind: m.Set(f,protoreflect.ValueOfBytes([]byte("fixture"))); case protoreflect.BoolKind: m.Set(f,protoreflect.ValueOfBool(false)); case protoreflect.EnumKind: m.Set(f,protoreflect.ValueOfEnum(1)); case protoreflect.Uint32Kind,protoreflect.Fixed32Kind: m.Set(f,protoreflect.ValueOfUint32(1)); case protoreflect.Uint64Kind,protoreflect.Fixed64Kind: m.Set(f,protoreflect.ValueOfUint64(1)); case protoreflect.Int32Kind,protoreflect.Sint32Kind,protoreflect.Sfixed32Kind: m.Set(f,protoreflect.ValueOfInt32(1)); case protoreflect.Int64Kind,protoreflect.Sint64Kind,protoreflect.Sfixed64Kind: m.Set(f,protoreflect.ValueOfInt64(1)) } }
}
func bytesRepeat(v byte,n int) []byte { b:=make([]byte,n); for i:=range b { b[i]=v }; return b }
func findMethod(svc protoreflect.ServiceDescriptor, operation string) protoreflect.MethodDescriptor { target:=strings.ToLower(strings.ReplaceAll(operation,"_","")); ms:=svc.Methods(); for i:=0;i<ms.Len();i++ { if strings.ToLower(string(ms.Get(i).Name()))==target { return ms.Get(i) } }; return nil }
func invoke(ctx context.Context, conn *grpc.ClientConn, svc protoreflect.ServiceDescriptor, md protoreflect.MethodDescriptor) ([]protoreflect.Message,int,error) {
 path:="/"+string(svc.FullName())+"/"+string(md.Name()); req:=message(md.Input()); fill(req,string(md.Name())); out:=[]protoreflect.Message{}; desc:=&grpc.StreamDesc{ServerStreams:md.IsStreamingServer(),ClientStreams:md.IsStreamingClient()}; st,e:=conn.NewStream(ctx,desc,path); if e!=nil{return nil,1,e}; if md.IsStreamingClient() { if e=st.SendMsg(req); e!=nil{return nil,1,e}; if e=st.CloseSend(); e!=nil{return nil,1,e} } else { if e=st.SendMsg(req); e!=nil{return nil,1,e} }
 if md.IsStreamingServer() { for { x:=message(md.Output()); e=st.RecvMsg(x); if e==io.EOF { break }; if e!=nil{return nil,1,e}; out=append(out,x) }; return out,1,nil }
 x:=message(md.Output()); if e=st.RecvMsg(x); e!=nil{return nil,1,e}; return append(out,x),1,nil
}
func field(m protoreflect.Message, name string) (protoreflect.Value, bool) { f:=m.Descriptor().Fields().ByName(protoreflect.Name(name)); if f==nil { return protoreflect.Value{}, false }; if (f.Kind()==protoreflect.MessageKind || f.Kind()==protoreflect.GroupKind || f.IsList()) && !m.Has(f) { return protoreflect.Value{}, false }; return m.Get(f), true }
func nestedField(m protoreflect.Message, name string) (protoreflect.Message, bool) { v,ok:=field(m,name); if !ok || v.Message()==nil { return nil,false }; return v.Message(),true }
func decodedSummary(m protoreflect.Message, depth int) map[string]any { result:=map[string]any{"type":string(m.Descriptor().FullName()),"fields":map[string]any{}}; if depth>3 { result["truncated"]=true; return result }; fields:=result["fields"].(map[string]any); fs:=m.Descriptor().Fields(); for i:=0;i<fs.Len();i++ { f:=fs.Get(i); if !m.Has(f) { continue }; v:=m.Get(f); if f.IsList() { list:=v.List(); items:=make([]any,0); for j:=0;j<list.Len()&&j<8;j++ { item:=list.Get(j); if f.Kind()==protoreflect.MessageKind { items=append(items,decodedSummary(item.Message(),depth+1)) } else { items=append(items,item.Interface()) } }; fields[string(f.Name())]=items; continue }; switch f.Kind() { case protoreflect.MessageKind: fields[string(f.Name())]=decodedSummary(v.Message(),depth+1); case protoreflect.BytesKind: sum:=sha256.Sum256(v.Bytes()); fields[string(f.Name())]=map[string]any{"byte_length":len(v.Bytes()),"sha256":fmt.Sprintf("%x",sum[:])}; case protoreflect.EnumKind: ev:=f.Enum().Values().ByNumber(v.Enum()); name:=""; if ev!=nil { name=string(ev.Name()) }; fields[string(f.Name())]=map[string]any{"number":int32(v.Enum()),"name":name}; default: fields[string(f.Name())]=v.Interface() } }; return result }
func genericSemantic(m protoreflect.Message, knownOutput string) string { summary:=decodedSummary(m,0); fields:=summary["fields"].(map[string]any); if len(fields)==0 { return fmt.Sprintf("mismatch: expected decoded %s; response contained no present fields",knownOutput) }; return fmt.Sprintf("passed: decoded fields for %s",knownOutput) }
func actual(method string, out []protoreflect.Message) map[string]any { if len(out)==0{return map[string]any{"response":"empty"}};m:=out[0];switch method { case "Handshake":p,ok:=nestedField(m,"protocol");if !ok{return decodedSummary(m,0)};v,_:=field(p,"version");d,_:=field(p,"descriptor_digest");_,supported:=field(m,"supported");return map[string]any{"protocol_version":v.String(),"descriptor_digest":d.String(),"supported_present":supported};case "Submit":sf:=m.Descriptor().Fields().ByName("state");if sf==nil||sf.Kind()!=protoreflect.EnumKind{return decodedSummary(m,0)};state,hasState:=field(m,"state");if !hasState{return decodedSummary(m,0)};op,has:=nestedField(m,"operation");r:=map[string]any{"state":state.Enum(),"operation_present":has};if has{id,_:=field(op,"operation_id");r["operation_id"]=id.String()};return r;case "Replay":live,hasLive:=field(m,"live");if !hasLive{return decodedSummary(m,0)};gen,_:=field(m,"generation");ev,hasEv:=field(m,"events");events:=0;if hasEv{events=ev.List().Len()};return map[string]any{"live":live.Bool(),"generation":gen.String(),"event_count":events};case "Observe":sf:=m.Descriptor().Fields().ByName("state");if sf==nil||sf.Kind()!=protoreflect.EnumKind{return decodedSummary(m,0)};state,hasState:=field(m,"state");if !hasState{return decodedSummary(m,0)};rev,hasRev:=field(m,"revision");revision:=uint64(0);if hasRev{revision=rev.Uint()};op,ho:=nestedField(m,"operation");owner,hw:=nestedField(m,"owner");r:=map[string]any{"state":state.Enum(),"revision":revision,"operation_present":ho,"owner_present":hw};if ho{v,_:=field(op,"operation_id");r["operation_id"]=v.String()};if hw{v,_:=field(owner,"id");r["owner_id"]=v.String()};return r;case "Cancel":st,hs:=nestedField(m,"status");op,ho:=nestedField(m,"operation");r:=map[string]any{"status_present":hs,"operation_present":ho};if hs{sf:=st.Descriptor().Fields().ByName("state");v,hasState:=field(st,"state");rv,hasRev:=field(st,"revision");if hasState&&sf!=nil&&sf.Kind()==protoreflect.EnumKind{r["state"]=v.Enum()};if hasRev{r["revision"]=rv.Uint()}};if ho{v,_:=field(op,"operation_id");r["operation_id"]=v.String()};return r;case "Export":c,_:=field(m,"contents");cur,_:=field(m,"cursor");id,_:=field(m,"object_id");term,_:=field(m,"terminal");return map[string]any{"cursor":string(cur.Bytes()),"object_id":string(id.Bytes()),"contents_utf8":string(c.Bytes()),"terminal":term.Bool()}};return decodedSummary(m,0) }
func semantic(method string, out []protoreflect.Message, knownOutput string) string { if method=="Export"{if len(out)!=1{return "mismatch: expected one export chunk"};a:=actual(method,out);if a["cursor"]!="fixture-export-cursor-1"||a["object_id"]!="fixture-export-object-1"||a["contents_utf8"]!="rust-owned-filesystem-export"||a["terminal"]!=true{return "mismatch: export chunk differs from Rust fixture"};return "passed: rust export chunk"};if method=="Handshake"{a:=actual(method,out);if a["protocol_version"]!="2"{return "mismatch: protocol identity"};return "passed: protocol+capabilities"};if method=="Submit"{a:=actual(method,out);if a["state"]!=protoreflect.EnumNumber(1)||a["operation_present"]!=true{return "mismatch: expected accepted admission"};return "passed: accepted"};if method=="Replay"{a:=actual(method,out);if a["live"]!=false||a["event_count"].(int)<1{return "mismatch: expected one non-live delivery"};return "passed: live_delivery_false"};if method=="Observe"{a:=actual(method,out);if a["state"]!=protoreflect.EnumNumber(1)||a["owner_present"]!=true{return "mismatch: expected running status"};return "passed: running_status"};if method=="Cancel"{a:=actual(method,out);if a["status_present"]!=true||a["state"]!=protoreflect.EnumNumber(4)||a["revision"]!=uint64(1){return "mismatch: expected cancelled revision 1"};return "passed: cancelled_revision"};if len(out)>0 { return genericSemantic(out[0],knownOutput) }; return fmt.Sprintf("mismatch: expected %s; empty response",knownOutput) }
func main() {
 addr:=os.Getenv("FIXTURE_GRPC_ADDRESS"); if addr=="" {addr="127.0.0.1:58315"}; graphPath:=os.Getenv("SEED_GRAPH"); if graphPath=="" {graphPath="Q:/sdk/work/fs35-rust-seed-graph.json"}; raw,e:=os.ReadFile(graphPath); if e!=nil {panic(e)}; var graph struct{Steps []scenario `json:"steps"`}; if e=json.Unmarshal(raw,&graph); e!=nil {panic(e)}; ctx,cancel:=context.WithTimeout(context.Background(),60*time.Second); defer cancel(); conn,e:=grpc.DialContext(ctx,addr,grpc.WithTransportCredentials(insecure.NewCredentials()),grpc.WithBlock()); if e!=nil {panic(e)}; defer conn.Close(); rows:=make([]row,0,len(graph.Steps)); for _,sc:=range graph.Steps { svcName:="acyclic.filesystem.v2.FilesystemService"; if sc.Family=="harness" {svcName="acyclic.harness.v2.HarnessService"}; svc:=service(svcName); method:=strings.ReplaceAll(sc.Operation,"_",""); md:=findMethod(svc,method); started:=time.Now(); r:=row{Order:sc.Order,Family:sc.Family,Operation:sc.Operation,Seed:sc.Seed,KnownOutput:sc.KnownOutput,ExecutionMode:"remote",Transport:"grpc",DependsOn:sc.DependsOn,RequestFrameCount:1}; if md==nil {r.Status="failed";r.Error="method descriptor missing"} else {out,frames,err:=invoke(ctx,conn,svc,md); r.RequestFrameCount=frames;r.ResponseCount=len(out);if err!=nil {r.Status="failed"; if s,ok:=status.FromError(err); ok {r.Error=s.Code().String()+":"+s.Message()} else {r.Error=err.Error()}; if status.Code(err)==codes.Canceled {r.SemanticCheck="passed: cancellation"} } else {r.Status="passed";r.Actual=actual(string(md.Name()),out);r.SemanticCheck=semantic(string(md.Name()),out,sc.KnownOutput)}}; r.ElapsedMs=float64(time.Since(started).Microseconds())/1000; rows=append(rows,r) }
 passed,failed,mismatch:=0,0,0; for _,r:=range rows {if r.Status=="passed"{passed++}else{failed++};if strings.HasPrefix(r.SemanticCheck,"mismatch:"){mismatch++}}; doc:=map[string]any{"schema":"acyclic.sdk.go.rust-seed35-trace.v1","consumer":"go","address":addr,"execution_mode":"remote","steps":rows,"passed":passed,"failed":failed,"semantic_mismatches":mismatch}; out,_:=json.MarshalIndent(doc,"","  "); path:=os.Getenv("TRACE_OUTPUT");if path==""{path="Q:/sdk/work/go-seed35-trace.json"};if e=os.WriteFile(path,append(out,'\n'),0644);e!=nil{panic(e)};fmt.Printf("{\"passed\":%d,\"failed\":%d,\"semantic_mismatches\":%d}\n",passed,failed,mismatch)
}












