<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference/v1/inference.proto

namespace Inference\Customer\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A message in the Inference customer v1 wire contract.
 *
 * Generated from protobuf message <code>inference.customer.v1.ContextView</code>
 */
class ContextView extends \Google\Protobuf\Internal\Message
{
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes revision = 1 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     */
    protected $revision = '';
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>optional bytes parent = 2 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     */
    protected $parent = null;
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes lineage = 3 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     */
    protected $lineage = '';
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes execution_profile = 4 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     */
    protected $execution_profile = '';
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes content_digest = 5 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     */
    protected $content_digest = '';
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>repeated .inference.customer.v1.Item items = 6;</code>
     */
    private $items;
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>string model = 7 [(.acyclic.validation.v1.nonempty_max_bytes) = 256];</code>
     */
    protected $model = '';
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>.inference.customer.v1.ContextProvenance provenance = 8 [(.acyclic.validation.v1.required_message) = true];</code>
     */
    protected $provenance = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $revision
     *           A field in the Inference customer v1 wire contract.
     *     @type string $parent
     *           A field in the Inference customer v1 wire contract.
     *     @type string $lineage
     *           A field in the Inference customer v1 wire contract.
     *     @type string $execution_profile
     *           A field in the Inference customer v1 wire contract.
     *     @type string $content_digest
     *           A field in the Inference customer v1 wire contract.
     *     @type \Inference\Customer\V1\Item[] $items
     *           A field in the Inference customer v1 wire contract.
     *     @type string $model
     *           A field in the Inference customer v1 wire contract.
     *     @type \Inference\Customer\V1\ContextProvenance $provenance
     *           A field in the Inference customer v1 wire contract.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Inference\V1\Inference::initOnce();
        parent::__construct($data);
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes revision = 1 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @return string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes revision = 1 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @param string $var
     * @return $this
     */
    public function setRevision(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->revision = $var;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>optional bytes parent = 2 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @return string
     */
    public function getParent()
    {
        return isset($this->parent) ? $this->parent : '';
    }

    public function hasParent()
    {
        return isset($this->parent);
    }

    public function clearParent()
    {
        unset($this->parent);
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>optional bytes parent = 2 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @param string $var
     * @return $this
     */
    public function setParent(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->parent = $var;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes lineage = 3 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @return string
     */
    public function getLineage()
    {
        return $this->lineage;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes lineage = 3 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @param string $var
     * @return $this
     */
    public function setLineage(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->lineage = $var;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes execution_profile = 4 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @return string
     */
    public function getExecutionProfile()
    {
        return $this->execution_profile;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes execution_profile = 4 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @param string $var
     * @return $this
     */
    public function setExecutionProfile(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->execution_profile = $var;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes content_digest = 5 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @return string
     */
    public function getContentDigest()
    {
        return $this->content_digest;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes content_digest = 5 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @param string $var
     * @return $this
     */
    public function setContentDigest(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->content_digest = $var;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>repeated .inference.customer.v1.Item items = 6;</code>
     * @return RepeatedField<\Inference\Customer\V1\Item>
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>repeated .inference.customer.v1.Item items = 6;</code>
     * @param \Inference\Customer\V1\Item[] $var
     * @return $this
     */
    public function setItems(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inference\Customer\V1\Item::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>string model = 7 [(.acyclic.validation.v1.nonempty_max_bytes) = 256];</code>
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>string model = 7 [(.acyclic.validation.v1.nonempty_max_bytes) = 256];</code>
     * @param string $var
     * @return $this
     */
    public function setModel(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->model = $var;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>.inference.customer.v1.ContextProvenance provenance = 8 [(.acyclic.validation.v1.required_message) = true];</code>
     * @return \Inference\Customer\V1\ContextProvenance|null
     */
    public function getProvenance()
    {
        return $this->provenance;
    }

    public function hasProvenance()
    {
        return isset($this->provenance);
    }

    public function clearProvenance()
    {
        unset($this->provenance);
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>.inference.customer.v1.ContextProvenance provenance = 8 [(.acyclic.validation.v1.required_message) = true];</code>
     * @param \Inference\Customer\V1\ContextProvenance $var
     * @return $this
     */
    public function setProvenance(\Inference\Customer\V1\ContextProvenance|null $var)
    {
        $this->provenance = $var;

        return $this;
    }

}

