<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference/v1/inference.proto

namespace Inference\Customer\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A message in the Inference customer v1 wire contract.
 *
 * Generated from protobuf message <code>inference.customer.v1.Edits</code>
 */
class Edits extends \Google\Protobuf\Internal\Message
{
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>repeated .inference.customer.v1.Edit edits = 1;</code>
     */
    private $edits;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Inference\Customer\V1\Edit[] $edits
     *           A field in the Inference customer v1 wire contract.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Inference\V1\Inference::initOnce();
        parent::__construct($data);
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>repeated .inference.customer.v1.Edit edits = 1;</code>
     * @return RepeatedField<\Inference\Customer\V1\Edit>
     */
    public function getEdits()
    {
        return $this->edits;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>repeated .inference.customer.v1.Edit edits = 1;</code>
     * @param \Inference\Customer\V1\Edit[] $var
     * @return $this
     */
    public function setEdits(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inference\Customer\V1\Edit::class);
        $this->edits = $arr;

        return $this;
    }

}

