<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference/v1/inference.proto

namespace Inference\Customer\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A message in the Inference customer v1 wire contract.
 *
 * Generated from protobuf message <code>inference.customer.v1.RetainWarmRequest</code>
 */
class RetainWarmRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>.inference.customer.v1.RequestIdentity identity = 1 [(.acyclic.validation.v1.required_message) = true];</code>
     */
    protected $identity = null;
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes context = 2 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     */
    protected $context = '';
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes latency_profile = 3;</code>
     */
    protected $latency_profile = '';
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>uint64 expires_at_ms = 4;</code>
     */
    protected $expires_at_ms = 0;
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>.inference.customer.v1.IdleKvPolicy idle_kv = 5;</code>
     */
    protected $idle_kv = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Inference\Customer\V1\RequestIdentity $identity
     *           A field in the Inference customer v1 wire contract.
     *     @type string $context
     *           A field in the Inference customer v1 wire contract.
     *     @type string $latency_profile
     *           A field in the Inference customer v1 wire contract.
     *     @type int|string $expires_at_ms
     *           A field in the Inference customer v1 wire contract.
     *     @type \Inference\Customer\V1\IdleKvPolicy $idle_kv
     *           A field in the Inference customer v1 wire contract.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Inference\V1\Inference::initOnce();
        parent::__construct($data);
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>.inference.customer.v1.RequestIdentity identity = 1 [(.acyclic.validation.v1.required_message) = true];</code>
     * @return \Inference\Customer\V1\RequestIdentity|null
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    public function hasIdentity()
    {
        return isset($this->identity);
    }

    public function clearIdentity()
    {
        unset($this->identity);
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>.inference.customer.v1.RequestIdentity identity = 1 [(.acyclic.validation.v1.required_message) = true];</code>
     * @param \Inference\Customer\V1\RequestIdentity $var
     * @return $this
     */
    public function setIdentity(\Inference\Customer\V1\RequestIdentity|null $var)
    {
        $this->identity = $var;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes context = 2 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @return string
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes context = 2 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @param string $var
     * @return $this
     */
    public function setContext(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->context = $var;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes latency_profile = 3;</code>
     * @return string
     */
    public function getLatencyProfile()
    {
        return $this->latency_profile;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes latency_profile = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLatencyProfile(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->latency_profile = $var;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>uint64 expires_at_ms = 4;</code>
     * @return int|string
     */
    public function getExpiresAtMs()
    {
        return $this->expires_at_ms;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>uint64 expires_at_ms = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiresAtMs(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->expires_at_ms = $var;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>.inference.customer.v1.IdleKvPolicy idle_kv = 5;</code>
     * @return \Inference\Customer\V1\IdleKvPolicy|null
     */
    public function getIdleKv()
    {
        return $this->idle_kv;
    }

    public function hasIdleKv()
    {
        return isset($this->idle_kv);
    }

    public function clearIdleKv()
    {
        unset($this->idle_kv);
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>.inference.customer.v1.IdleKvPolicy idle_kv = 5;</code>
     * @param \Inference\Customer\V1\IdleKvPolicy $var
     * @return $this
     */
    public function setIdleKv(\Inference\Customer\V1\IdleKvPolicy|null $var)
    {
        $this->idle_kv = $var;

        return $this;
    }

}

