<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference/v1/inference.proto

namespace Inference\Customer\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A message in the Inference customer v1 wire contract.
 *
 * Generated from protobuf message <code>inference.customer.v1.RetentionProfile</code>
 */
class RetentionProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes profile = 1 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     */
    protected $profile = '';
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>uint64 minimum_duration_ms = 2 [(.acyclic.validation.v1.positive_uint64) = true];</code>
     */
    protected $minimum_duration_ms = 0;
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>uint64 maximum_duration_ms = 3;</code>
     */
    protected $maximum_duration_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $profile
     *           A field in the Inference customer v1 wire contract.
     *     @type int|string $minimum_duration_ms
     *           A field in the Inference customer v1 wire contract.
     *     @type int|string $maximum_duration_ms
     *           A field in the Inference customer v1 wire contract.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Inference\V1\Inference::initOnce();
        parent::__construct($data);
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes profile = 1 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @return string
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>bytes profile = 1 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @param string $var
     * @return $this
     */
    public function setProfile(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->profile = $var;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>uint64 minimum_duration_ms = 2 [(.acyclic.validation.v1.positive_uint64) = true];</code>
     * @return int|string
     */
    public function getMinimumDurationMs()
    {
        return $this->minimum_duration_ms;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>uint64 minimum_duration_ms = 2 [(.acyclic.validation.v1.positive_uint64) = true];</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinimumDurationMs(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->minimum_duration_ms = $var;

        return $this;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>uint64 maximum_duration_ms = 3;</code>
     * @return int|string
     */
    public function getMaximumDurationMs()
    {
        return $this->maximum_duration_ms;
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>uint64 maximum_duration_ms = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaximumDurationMs(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->maximum_duration_ms = $var;

        return $this;
    }

}

