<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference/v1/inference.proto

namespace Inference\Customer\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Records the context and run inputs used for generation.
 *
 * Generated from protobuf message <code>inference.customer.v1.RunInputProvenance</code>
 */
class RunInputProvenance extends \Google\Protobuf\Internal\Message
{
    /**
     * The source value carried by RunInputProvenance.
     *
     * Generated from protobuf field <code>bytes source = 1 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     */
    protected $source = '';
    /**
     * The run id value carried by RunInputProvenance.
     *
     * Generated from protobuf field <code>bytes run_id = 2 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 16];</code>
     */
    protected $run_id = '';
    /**
     * The maximum output value carried by RunInputProvenance.
     *
     * Generated from protobuf field <code>uint64 maximum_output = 3 [(.acyclic.validation.v1.positive_uint64) = true];</code>
     */
    protected $maximum_output = 0;
    /**
     * The seed value carried by RunInputProvenance.
     *
     * Generated from protobuf field <code>optional uint64 seed = 4;</code>
     */
    protected $seed = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source
     *           The source value carried by RunInputProvenance.
     *     @type string $run_id
     *           The run id value carried by RunInputProvenance.
     *     @type int|string $maximum_output
     *           The maximum output value carried by RunInputProvenance.
     *     @type int|string $seed
     *           The seed value carried by RunInputProvenance.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Inference\V1\Inference::initOnce();
        parent::__construct($data);
    }

    /**
     * The source value carried by RunInputProvenance.
     *
     * Generated from protobuf field <code>bytes source = 1 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * The source value carried by RunInputProvenance.
     *
     * Generated from protobuf field <code>bytes source = 1 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @param string $var
     * @return $this
     */
    public function setSource(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->source = $var;

        return $this;
    }

    /**
     * The run id value carried by RunInputProvenance.
     *
     * Generated from protobuf field <code>bytes run_id = 2 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 16];</code>
     * @return string
     */
    public function getRunId()
    {
        return $this->run_id;
    }

    /**
     * The run id value carried by RunInputProvenance.
     *
     * Generated from protobuf field <code>bytes run_id = 2 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 16];</code>
     * @param string $var
     * @return $this
     */
    public function setRunId(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->run_id = $var;

        return $this;
    }

    /**
     * The maximum output value carried by RunInputProvenance.
     *
     * Generated from protobuf field <code>uint64 maximum_output = 3 [(.acyclic.validation.v1.positive_uint64) = true];</code>
     * @return int|string
     */
    public function getMaximumOutput()
    {
        return $this->maximum_output;
    }

    /**
     * The maximum output value carried by RunInputProvenance.
     *
     * Generated from protobuf field <code>uint64 maximum_output = 3 [(.acyclic.validation.v1.positive_uint64) = true];</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaximumOutput(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->maximum_output = $var;

        return $this;
    }

    /**
     * The seed value carried by RunInputProvenance.
     *
     * Generated from protobuf field <code>optional uint64 seed = 4;</code>
     * @return int|string
     */
    public function getSeed()
    {
        return isset($this->seed) ? $this->seed : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasSeed()
    {
        return isset($this->seed);
    }

    public function clearSeed()
    {
        unset($this->seed);
    }

    /**
     * The seed value carried by RunInputProvenance.
     *
     * Generated from protobuf field <code>optional uint64 seed = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeed(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->seed = $var;

        return $this;
    }

}

