<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference/v1/inference.proto

namespace Inference\Customer\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Records a model transfer and compatible-state reuse.
 *
 * Generated from protobuf message <code>inference.customer.v1.TransferProvenance</code>
 */
class TransferProvenance extends \Google\Protobuf\Internal\Message
{
    /**
     * The source value carried by TransferProvenance.
     *
     * Generated from protobuf field <code>bytes source = 1 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     */
    protected $source = '';
    /**
     * The reused compatible state value carried by TransferProvenance.
     *
     * Generated from protobuf field <code>bool reused_compatible_state = 2;</code>
     */
    protected $reused_compatible_state = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source
     *           The source value carried by TransferProvenance.
     *     @type bool $reused_compatible_state
     *           The reused compatible state value carried by TransferProvenance.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Inference\V1\Inference::initOnce();
        parent::__construct($data);
    }

    /**
     * The source value carried by TransferProvenance.
     *
     * Generated from protobuf field <code>bytes source = 1 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * The source value carried by TransferProvenance.
     *
     * Generated from protobuf field <code>bytes source = 1 [(.acyclic.validation.v1.nonzero_fixed_bytes) = 32];</code>
     * @param string $var
     * @return $this
     */
    public function setSource(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->source = $var;

        return $this;
    }

    /**
     * The reused compatible state value carried by TransferProvenance.
     *
     * Generated from protobuf field <code>bool reused_compatible_state = 2;</code>
     * @return bool
     */
    public function getReusedCompatibleState()
    {
        return $this->reused_compatible_state;
    }

    /**
     * The reused compatible state value carried by TransferProvenance.
     *
     * Generated from protobuf field <code>bool reused_compatible_state = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setReusedCompatibleState(bool $var)
    {
        $this->reused_compatible_state = $var;

        return $this;
    }

}

