<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference/v1/inference.proto

namespace Inference\Customer\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A message in the Inference customer v1 wire contract.
 *
 * Generated from protobuf message <code>inference.customer.v1.Truncate</code>
 */
class Truncate extends \Google\Protobuf\Internal\Message
{
    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>optional bytes through = 1;</code>
     */
    protected $through = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $through
     *           A field in the Inference customer v1 wire contract.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Inference\V1\Inference::initOnce();
        parent::__construct($data);
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>optional bytes through = 1;</code>
     * @return string
     */
    public function getThrough()
    {
        return isset($this->through) ? $this->through : '';
    }

    public function hasThrough()
    {
        return isset($this->through);
    }

    public function clearThrough()
    {
        unset($this->through);
    }

    /**
     * A field in the Inference customer v1 wire contract.
     *
     * Generated from protobuf field <code>optional bytes through = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setThrough(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->through = $var;

        return $this;
    }

}

