# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .rb file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Ruby
# helpers directly inline like we're doing here.

require 'ffi'
require 'monitor'


module AcyclicActorsUniffi
  def self.uniffi_in_range(i, type_name, min, max)
  raise TypeError, "no implicit conversion of #{i} into Integer" unless i.respond_to?(:to_int)
  i = i.to_int
  raise RangeError, "#{type_name} requires #{min} <= value < #{max}" unless (min <= i && i < max)
  i
end

def self.uniffi_utf8(v)
  raise TypeError, "no implicit conversion of #{v} into String" unless v.respond_to?(:to_str)
  v = v.to_str.encode(Encoding::UTF_8)
  raise Encoding::InvalidByteSequenceError, "not a valid UTF-8 encoded string" unless v.valid_encoding?
  v
end

def self.uniffi_bytes(v)
  raise TypeError, "no implicit conversion of #{v} into String" unless v.respond_to?(:to_str)
  v.to_str
end
  # A handle map for converting Ruby objects to/from integer handles.
#
# When passing callback interface or trait interface objects to Ruby, we store
# the Ruby object in this map and pass the integer handle to Rust. When Rust
# calls back, we look up the Ruby object by its handle.
#
# Ruby-created handles are always odd (staring at 1, incrementing by 2).
# Rust-created handles are always even. This convention lets us distinguish
# the source in lift/lower without extra metadata.


class UniffiHandleMap
  def initialize
    @lock = Monitor.new
    @map = {}
    @counter = 1 # Start at 1 (odd), increment by 2
  end

  def insert(obj)
    @lock.synchronize do
      handle = @counter
      @counter += 2
      @map[handle] = obj
      handle
    end
  end

  def get(handle)
    @lock.synchronize do
      obj = @map[handle]
      raise InternalError, "UniffiHandleMap.get: invalid handle #{handle}" if obj.nil?
      obj
    end
  end

  def clone_handle(handle)
    @lock.synchronize do
      obj = @map[handle]
      raise InternalError, "UniffiHandleMap.clone_handle: invalid handle #{handle}" if obj.nil?
      new_handle = @counter
      @counter += 2
      @map[new_handle] = obj
      new_handle
    end
  end

  def remove(handle)
    @lock.synchronize do
      obj = @map.delete(handle)
      raise InternalError, "UniffiHandleMap.remove: invalid handle #{handle}" if obj.nil?
      obj
    end
  end

  # Used for testing/debugging purposes
  def size
    @lock.synchronize { @map.size }
  end
end

private_constant :UniffiHandleMap

  class RustBuffer < FFI::Struct
  layout :capacity, :uint64,
         :len,      :uint64,
         :data,     :pointer

  def self.alloc(size)
    return AcyclicActorsUniffi.rust_call(:ffi_acyclic_actors_uniffi_rustbuffer_alloc, size)
  end

  def self.reserve(rbuf, additional)
    return AcyclicActorsUniffi.rust_call(:ffi_acyclic_actors_uniffi_rustbuffer_reserve, rbuf, additional)
  end

  def free
    AcyclicActorsUniffi.rust_call(:ffi_acyclic_actors_uniffi_rustbuffer_free, self)
  end

  def capacity
    self[:capacity]
  end

  def len
    self[:len]
  end

  def len=(value)
    self[:len] = value
  end

  def data
    self[:data]
  end

  def to_s
    "RustBuffer(capacity=#{capacity}, len=#{len}, data=#{data.read_bytes len})"
  end

  # The allocated buffer will be automatically freed if an error occurs, ensuring that
  # we don't accidentally leak it.
  def self.allocWithBuilder
    builder = RustBufferBuilder.new

    begin
      yield builder
    rescue => e
      builder.discard
      raise e
    end
  end

  # The RustBuffer will be freed once the context-manager exits, ensuring that we don't
  # leak it even if an error occurs.
  def consumeWithStream
    stream = RustBufferStream.new self

    yield stream

    raise RuntimeError, 'junk data left in buffer after consuming' if stream.remaining != 0
  ensure
    free
  end# The primitive String type.

  def self.allocFromString(value)
    RustBuffer.allocWithBuilder do |builder|
      builder.write value.encode('utf-8')
      return builder.finalize
    end
  end

  def consumeIntoString
    consumeWithStream do |stream|
      return stream.read(stream.remaining).force_encoding(Encoding::UTF_8)
    end
  end

  # The primitive Bytes type.

  def self.allocFromBytes(value)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_Bytes(value)
      return builder.finalize
    end
  end

  def consumeIntoBytes
    consumeWithStream do |stream|
      return stream.readBytes
    end
  end

  

  # The Optional<T> type for i32.

  def self.check_lower_Optionali32(v)
    if not v.nil?
      
    end
  end

  def self.alloc_from_Optionali32(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_Optionali32(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionali32
    consumeWithStream do |stream|
      return stream.readOptionali32
    end
  end

  # The Optional<T> type for bytes.

  def self.check_lower_Optionalbytes(v)
    if not v.nil?
      
    end
  end

  def self.alloc_from_Optionalbytes(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_Optionalbytes(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalbytes
    consumeWithStream do |stream|
      return stream.readOptionalbytes
    end
  end

  # The Optional<T> type for TypeCancellationHandle.

  def self.check_lower_OptionalTypeCancellationHandle(v)
    if not v.nil?
      (CancellationHandle.uniffi_check_lower v)
    end
  end

  def self.alloc_from_OptionalTypeCancellationHandle(v)
    RustBuffer.allocWithBuilder do |builder|
      builder.write_OptionalTypeCancellationHandle(v)
      return builder.finalize()
    end
  end

  def consumeIntoOptionalTypeCancellationHandle
    consumeWithStream do |stream|
      return stream.readOptionalTypeCancellationHandle
    end
  end

  
end

module UniFFILib
  class ForeignBytes < FFI::Struct
    layout :len,      :int32,
           :data,     :pointer

    def len
      self[:len]
    end

    def data
      self[:data]
    end

    def to_s
      "ForeignBytes(len=#{len}, data=#{data.read_bytes(len)})"
    end
  end
end

private_constant :UniFFILib
  
# Helper for structured reading of values from a RustBuffer.
class RustBufferStream

  def initialize(rbuf)
    @rbuf = rbuf
    @offset = 0
  end

  def remaining
    @rbuf.len - @offset
  end

  def read(size)
    raise InternalError, 'read past end of rust buffer' if @offset + size > @rbuf.len

    data = @rbuf.data.get_bytes @offset, size

    @offset += size

    data
  end

  def readI32
    unpack_from 4, 'l>'
  end

  def readU64
    unpack_from 8, 'Q>'
  end

  def readBool
    v = unpack_from 1, 'c'

    return false if v == 0
    return true if v == 1

    raise InternalError, 'Unexpected byte for Boolean type'
  end

  def readString
    size = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative string length' if size.negative?

    read(size).force_encoding(Encoding::UTF_8)
  end

  def readBytes
    size = unpack_from 4, 'l>'

    raise InternalError, 'Unexpected negative byte string length' if size.negative?

    read(size).force_encoding(Encoding::BINARY)
  end

  # The Object type ActorsClient.

  def readTypeActorsClient
    handle = unpack_from 8, 'Q>'
    return ActorsClient.uniffi_allocate(handle)
  end

  # The Object type CancellationHandle.

  def readTypeCancellationHandle
    handle = unpack_from 8, 'Q>'
    return CancellationHandle.uniffi_allocate(handle)
  end

  

  

  # The Error type BindingError

  def readTypeBindingError
    variant = unpack_from 4, 'l>'
    
    if variant == 1
        return BindingError::Configuration.new(
            readString()
        )
    end
    if variant == 2
        return BindingError::Transport.new(
            readString()
        )
    end
    if variant == 3
        return BindingError::Service.new(
            readI32(),
            readOptionali32(),
            readString()
        )
    end
    if variant == 4
        return BindingError::Contract.new(
            readString()
        )
    end
    if variant == 5
        return BindingError::Semantic.new(
            readString()
        )
    end
    if variant == 6
        return BindingError::Cancelled.new
    end

    raise InternalError, 'Unexpected variant tag for TypeBindingError'
  end
  

  # The Optional<T> type for i32.

  def readOptionali32
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readI32
    else
      raise InternalError, 'Unexpected flag byte for Optionali32'
    end
  end

  # The Optional<T> type for bytes.

  def readOptionalbytes
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readBytes
    else
      raise InternalError, 'Unexpected flag byte for Optionalbytes'
    end
  end

  # The Optional<T> type for TypeCancellationHandle.

  def readOptionalTypeCancellationHandle
    flag = unpack_from 1, 'c'

    if flag == 0
      return nil
    elsif flag == 1
      return readTypeCancellationHandle
    else
      raise InternalError, 'Unexpected flag byte for OptionalTypeCancellationHandle'
    end
  end

  

  def unpack_from(size, format)
    raise InternalError, 'read past end of rust buffer' if @offset + size > @rbuf.len

    value = @rbuf.data.get_bytes(@offset, size).unpack format

    @offset += size

    # TODO: verify this
    raise 'more than one element!!!' if value.size > 1

    value[0]
  end
end

private_constant :RustBufferStream
  
# Helper for structured writing of values into a RustBuffer.
class RustBufferBuilder
  def initialize
    @rust_buf = RustBuffer.alloc 16
    @rust_buf.len = 0
  end

  def finalize
    rbuf = @rust_buf

    @rust_buf = nil

    rbuf
  end

  def discard
    return if @rust_buf.nil?

    rbuf = finalize
    rbuf.free
  end

  def write(value)
    reserve(value.bytes.size) do
      @rust_buf.data.put_array_of_char @rust_buf.len, value.bytes
    end
  end

  def write_I32(v)
    v = AcyclicActorsUniffi::uniffi_in_range(v, "i32", -2**31, 2**31)
    pack_into(4, 'l>', v)
  end

  def write_U64(v)
    v = AcyclicActorsUniffi::uniffi_in_range(v, "u64", 0, 2**64)
    pack_into(8, 'Q>', v)
  end

  def write_Bool(v)
    pack_into(1, 'c', v ? 1 : 0)
  end

  def write_String(v)
    v = AcyclicActorsUniffi::uniffi_utf8(v)
    pack_into 4, 'l>', v.bytes.size
    write v
  end

  def write_Bytes(v)
    v = AcyclicActorsUniffi::uniffi_bytes(v)
    pack_into 4, 'l>', v.bytes.size
    write v
  end

  # The Object type ActorsClient.

  def write_TypeActorsClient(obj)
    handle = ActorsClient.uniffi_lower obj
    pack_into(8, 'Q>', handle)
  end

  # The Object type CancellationHandle.

  def write_TypeCancellationHandle(obj)
    handle = CancellationHandle.uniffi_lower obj
    pack_into(8, 'Q>', handle)
  end

  

  # The Optional<T> type for i32.

  def write_Optionali32(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_I32(v)
    end
  end

  # The Optional<T> type for bytes.

  def write_Optionalbytes(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_Bytes(v)
    end
  end

  # The Optional<T> type for TypeCancellationHandle.

  def write_OptionalTypeCancellationHandle(v)
    if v.nil?
      pack_into(1, 'c', 0)
    else
      pack_into(1, 'c', 1)
      self.write_TypeCancellationHandle(v)
    end
  end

  

  private

  def reserve(num_bytes)
    if @rust_buf.len + num_bytes > @rust_buf.capacity
      @rust_buf = RustBuffer.reserve(@rust_buf, num_bytes)
    end

    yield

    @rust_buf.len += num_bytes
  end

  def pack_into(size, format, value)
    reserve(size) do
      @rust_buf.data.put_array_of_char @rust_buf.len, [value].pack(format).bytes
    end
  end
end

private_constant :RustBufferBuilder

  # Error definitions
  class RustCallStatus < FFI::Struct
  layout :code,    :int8,
         :error_buf, RustBuffer

  def code
    self[:code]
  end

  def error_buf
    self[:error_buf]
  end

  def to_s
    "RustCallStatus(code=#{self[:code]})"
  end
end

# These match the values from the uniffi::rustcalls module
CALL_SUCCESS = 0
CALL_ERROR = 1
CALL_PANIC = 2


module BindingError
  class Configuration < StandardError
    def initialize(detail_message)
        @detail_message = detail_message
        super()
      end

    attr_reader :detail_message
    

    def to_s
     "#{self.class.name}(detail_message=#{@detail_message.inspect})"
    end
  end
  class Transport < StandardError
    def initialize(detail_message)
        @detail_message = detail_message
        super()
      end

    attr_reader :detail_message
    

    def to_s
     "#{self.class.name}(detail_message=#{@detail_message.inspect})"
    end
  end
  class Service < StandardError
    def initialize(grpc_code, service_code, detail_message)
        @grpc_code = grpc_code
        @service_code = service_code
        @detail_message = detail_message
        super()
      end

    attr_reader :grpc_code, :service_code, :detail_message
    

    def to_s
     "#{self.class.name}(grpc_code=#{@grpc_code.inspect}, service_code=#{@service_code.inspect}, detail_message=#{@detail_message.inspect})"
    end
  end
  class Contract < StandardError
    def initialize(detail_message)
        @detail_message = detail_message
        super()
      end

    attr_reader :detail_message
    

    def to_s
     "#{self.class.name}(detail_message=#{@detail_message.inspect})"
    end
  end
  class Semantic < StandardError
    def initialize(detail_message)
        @detail_message = detail_message
        super()
      end

    attr_reader :detail_message
    

    def to_s
     "#{self.class.name}(detail_message=#{@detail_message.inspect})"
    end
  end
  class Cancelled < StandardError
    def initialize()
        super()
      end

    def to_s
     "#{self.class.name}()"
    end
  end

end


# Map error modules to the RustBuffer method name that reads them
ERROR_MODULE_TO_READER_METHOD = {

  BindingError => :readTypeBindingError,

}

private_constant :ERROR_MODULE_TO_READER_METHOD, :CALL_SUCCESS, :CALL_ERROR, :CALL_PANIC,
                 :RustCallStatus

def self.consume_buffer_into_error(error_module, rust_buffer)
  rust_buffer.consumeWithStream do |stream|
    reader_method = ERROR_MODULE_TO_READER_METHOD[error_module]
    return stream.send(reader_method)
  end
end

class InternalError < StandardError
end

def self.rust_call(fn_name, *args)
  # Call a rust function
  rust_call_with_error(nil, fn_name, *args)
end

def self.rust_call_with_error(error_module, fn_name, *args)
  # Call a rust function and handle errors
  #
  # Use this when the rust function returns a Result<>.  error_module must be the error_module that corresponds to that Result.


  # Note: RustCallStatus.new zeroes out the struct, which is exactly what we
  # want to pass to Rust (code=0, error_buf=RustBuffer(len=0, capacity=0,
  # data=NULL))
  status = RustCallStatus.new
  args << status

  result = UniFFILib.public_send(fn_name, *args)

  case status.code
  when CALL_SUCCESS
    result
  when CALL_ERROR
    if error_module.nil?
      status.error_buf.free
      raise InternalError, "CALL_ERROR with no error_module set"
    else
      raise consume_buffer_into_error(error_module, status.error_buf)
    end
  when CALL_PANIC
    # When the rust code sees a panic, it tries to construct a RustBuffer
    # with the message.  But if that code panics, then it just sends back
    # an empty buffer.
    if status.error_buf.len > 0
      raise InternalError, status.error_buf.consumeIntoString()
    else
      raise InternalError, "Rust panic"
    end
  else
    raise InternalError, "Unknown call status: #{status.code}"
  end
end

private_class_method :consume_buffer_into_error

  # This is how we find and load the dynamic library provided by the component.
# For now we just look it up by name.
module UniFFILib
  extend FFI::Library

  
  ffi_lib '/tmp/ruby-c8-wsl-native-target-20261007/release/libacyclic_actors_uniffi.so'
  

  
  callback :RustFutureContinuationCallback,
    [:uint64, :int8, ],
    :void
  
  callback :ForeignFutureDroppedCallback,
    [:uint64, ],
    :void
  
  callback :CallbackInterfaceFree,
    [:uint64, ],
    :void
  
  callback :CallbackInterfaceClone,
    [:uint64, ],
    :uint64
  
  class ForeignFutureDroppedCallbackStruct < FFI::Struct
    layout(
      :handle, :uint64,
      :free, :ForeignFutureDroppedCallback
    )
  end
  
  class ForeignFutureResultU8 < FFI::Struct
    layout(
      :return_value, :uint8,
      :call_status, RustCallStatus
    )
  end
  
  callback :ForeignFutureCompleteU8,
    [:uint64, ForeignFutureResultU8.by_value, ],
    :void
  
  class ForeignFutureResultI8 < FFI::Struct
    layout(
      :return_value, :int8,
      :call_status, RustCallStatus
    )
  end
  
  callback :ForeignFutureCompleteI8,
    [:uint64, ForeignFutureResultI8.by_value, ],
    :void
  
  class ForeignFutureResultU16 < FFI::Struct
    layout(
      :return_value, :uint16,
      :call_status, RustCallStatus
    )
  end
  
  callback :ForeignFutureCompleteU16,
    [:uint64, ForeignFutureResultU16.by_value, ],
    :void
  
  class ForeignFutureResultI16 < FFI::Struct
    layout(
      :return_value, :int16,
      :call_status, RustCallStatus
    )
  end
  
  callback :ForeignFutureCompleteI16,
    [:uint64, ForeignFutureResultI16.by_value, ],
    :void
  
  class ForeignFutureResultU32 < FFI::Struct
    layout(
      :return_value, :uint32,
      :call_status, RustCallStatus
    )
  end
  
  callback :ForeignFutureCompleteU32,
    [:uint64, ForeignFutureResultU32.by_value, ],
    :void
  
  class ForeignFutureResultI32 < FFI::Struct
    layout(
      :return_value, :int32,
      :call_status, RustCallStatus
    )
  end
  
  callback :ForeignFutureCompleteI32,
    [:uint64, ForeignFutureResultI32.by_value, ],
    :void
  
  class ForeignFutureResultU64 < FFI::Struct
    layout(
      :return_value, :uint64,
      :call_status, RustCallStatus
    )
  end
  
  callback :ForeignFutureCompleteU64,
    [:uint64, ForeignFutureResultU64.by_value, ],
    :void
  
  class ForeignFutureResultI64 < FFI::Struct
    layout(
      :return_value, :int64,
      :call_status, RustCallStatus
    )
  end
  
  callback :ForeignFutureCompleteI64,
    [:uint64, ForeignFutureResultI64.by_value, ],
    :void
  
  class ForeignFutureResultF32 < FFI::Struct
    layout(
      :return_value, :float,
      :call_status, RustCallStatus
    )
  end
  
  callback :ForeignFutureCompleteF32,
    [:uint64, ForeignFutureResultF32.by_value, ],
    :void
  
  class ForeignFutureResultF64 < FFI::Struct
    layout(
      :return_value, :double,
      :call_status, RustCallStatus
    )
  end
  
  callback :ForeignFutureCompleteF64,
    [:uint64, ForeignFutureResultF64.by_value, ],
    :void
  
  class ForeignFutureResultRustBuffer < FFI::Struct
    layout(
      :return_value, RustBuffer.by_value,
      :call_status, RustCallStatus
    )
  end
  
  callback :ForeignFutureCompleteRustBuffer,
    [:uint64, ForeignFutureResultRustBuffer.by_value, ],
    :void
  
  class ForeignFutureResultVoid < FFI::Struct
    layout(
      :call_status, RustCallStatus
    )
  end
  
  callback :ForeignFutureCompleteVoid,
    [:uint64, ForeignFutureResultVoid.by_value, ],
    :void
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_clone_actorsclient,
    [:uint64, RustCallStatus.by_ref],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_free_actorsclient,
    [:uint64, RustCallStatus.by_ref],
    :void
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_method_actorsclient_add_subscription,
    [:uint64, RustBuffer.by_value, RustBuffer.by_value, ],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_method_actorsclient_checkpoint_actor,
    [:uint64, RustBuffer.by_value, RustBuffer.by_value, ],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_method_actorsclient_create_actor,
    [:uint64, RustBuffer.by_value, RustBuffer.by_value, ],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_method_actorsclient_inspect_actor,
    [:uint64, RustBuffer.by_value, RustBuffer.by_value, ],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_method_actorsclient_invoke_actor,
    [:uint64, RustBuffer.by_value, RustBuffer.by_value, ],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_method_actorsclient_remove_subscription,
    [:uint64, RustBuffer.by_value, RustBuffer.by_value, ],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_method_actorsclient_resume_subscription,
    [:uint64, RustBuffer.by_value, RustBuffer.by_value, ],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_method_actorsclient_update_actor,
    [:uint64, RustBuffer.by_value, RustBuffer.by_value, ],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_clone_cancellationhandle,
    [:uint64, RustCallStatus.by_ref],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_free_cancellationhandle,
    [:uint64, RustCallStatus.by_ref],
    :void
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_constructor_cancellationhandle_new,
    [RustCallStatus.by_ref],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_method_cancellationhandle_cancel,
    [:uint64, RustCallStatus.by_ref],
    :void
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_method_cancellationhandle_is_cancelled,
    [:uint64, RustCallStatus.by_ref],
    :int8
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_func_connect_actors,
    [RustBuffer.by_value, RustBuffer.by_value, RustBuffer.by_value, ],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_func_connect_actors_with_ca,
    [RustBuffer.by_value, RustBuffer.by_value, RustBuffer.by_value, RustBuffer.by_value, ],
    :uint64
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_func_validate_actor_id,
    [RustBuffer.by_value, RustCallStatus.by_ref],
    :void
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_func_validate_code_sha256,
    [RustBuffer.by_value, RustCallStatus.by_ref],
    :void
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_func_validate_current_head,
    [:int8, RustCallStatus.by_ref],
    :void
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_func_validate_current_head_marker,
    [:int8, RustCallStatus.by_ref],
    :void
  
  attach_function :uniffi_acyclic_actors_uniffi_fn_func_validate_positive_u64,
    [:uint64, RustCallStatus.by_ref],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rustbuffer_alloc,
    [:uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  
  attach_function :ffi_acyclic_actors_uniffi_rustbuffer_from_bytes,
    [ForeignBytes, RustCallStatus.by_ref],
    RustBuffer.by_value
  
  attach_function :ffi_acyclic_actors_uniffi_rustbuffer_free,
    [RustBuffer.by_value, RustCallStatus.by_ref],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rustbuffer_reserve,
    [RustBuffer.by_value, :uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_poll_u8,
    [:uint64, :RustFutureContinuationCallback, :uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_cancel_u8,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_free_u8,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_complete_u8,
    [:uint64, RustCallStatus.by_ref],
    :uint8
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_poll_i8,
    [:uint64, :RustFutureContinuationCallback, :uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_cancel_i8,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_free_i8,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_complete_i8,
    [:uint64, RustCallStatus.by_ref],
    :int8
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_poll_u16,
    [:uint64, :RustFutureContinuationCallback, :uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_cancel_u16,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_free_u16,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_complete_u16,
    [:uint64, RustCallStatus.by_ref],
    :uint16
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_poll_i16,
    [:uint64, :RustFutureContinuationCallback, :uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_cancel_i16,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_free_i16,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_complete_i16,
    [:uint64, RustCallStatus.by_ref],
    :int16
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_poll_u32,
    [:uint64, :RustFutureContinuationCallback, :uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_cancel_u32,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_free_u32,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_complete_u32,
    [:uint64, RustCallStatus.by_ref],
    :uint32
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_poll_i32,
    [:uint64, :RustFutureContinuationCallback, :uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_cancel_i32,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_free_i32,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_complete_i32,
    [:uint64, RustCallStatus.by_ref],
    :int32
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_poll_u64,
    [:uint64, :RustFutureContinuationCallback, :uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_cancel_u64,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_free_u64,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_complete_u64,
    [:uint64, RustCallStatus.by_ref],
    :uint64
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_poll_i64,
    [:uint64, :RustFutureContinuationCallback, :uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_cancel_i64,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_free_i64,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_complete_i64,
    [:uint64, RustCallStatus.by_ref],
    :int64
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_poll_f32,
    [:uint64, :RustFutureContinuationCallback, :uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_cancel_f32,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_free_f32,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_complete_f32,
    [:uint64, RustCallStatus.by_ref],
    :float
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_poll_f64,
    [:uint64, :RustFutureContinuationCallback, :uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_cancel_f64,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_free_f64,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_complete_f64,
    [:uint64, RustCallStatus.by_ref],
    :double
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_poll_rust_buffer,
    [:uint64, :RustFutureContinuationCallback, :uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_cancel_rust_buffer,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_free_rust_buffer,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_complete_rust_buffer,
    [:uint64, RustCallStatus.by_ref],
    RustBuffer.by_value
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_poll_void,
    [:uint64, :RustFutureContinuationCallback, :uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_cancel_void,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_free_void,
    [:uint64, ],
    :void
  
  attach_function :ffi_acyclic_actors_uniffi_rust_future_complete_void,
    [:uint64, RustCallStatus.by_ref],
    :void
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_func_connect_actors,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_func_connect_actors_with_ca,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_func_validate_actor_id,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_func_validate_code_sha256,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_func_validate_current_head,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_func_validate_current_head_marker,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_func_validate_positive_u64,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_method_actorsclient_add_subscription,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_method_actorsclient_checkpoint_actor,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_method_actorsclient_create_actor,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_method_actorsclient_inspect_actor,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_method_actorsclient_invoke_actor,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_method_actorsclient_remove_subscription,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_method_actorsclient_resume_subscription,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_method_actorsclient_update_actor,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_method_cancellationhandle_cancel,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_method_cancellationhandle_is_cancelled,
    [],
    :uint16
  
  attach_function :uniffi_acyclic_actors_uniffi_checksum_constructor_cancellationhandle_new,
    [],
    :uint16
  
  attach_function :ffi_acyclic_actors_uniffi_uniffi_contract_version,
    [],
    :uint32
  
end
  # RustFuture poll codes
UNIFFI_RUST_FUTURE_POLL_READY = 0
UNIFFI_RUST_FUTURE_POLL_WAKE = 1

# Handle map for storing write-end IO objects used by the continuation callbacks.
UNIFFI_ASYNC_HANDLE_MAP = UniffiHandleMap.new

# Continuation callback for async functions.
# Called by Rust when the future is ready to make progress.
# Writes the poll code to the pipe so the waiting thread/fiber can continue.
#
# Exceptions must never escape this Proc.
# Rust invokes it directly via FFI, so any unhandled Ruby exception would be caught
# by Ruby-FFI, which swallows it (prints a warning) and returns a garbage value to Rust.
# The poll code Rust receives would be invalid, causing the Ruby polling loop to
# never see POLL_READY and block forever.
UNIFFI_CONTINUATION_CALLBACK = Proc.new do |data, poll_code|
  begin
    wr = UNIFFI_ASYNC_HANDLE_MAP.get data

    # This can only be blocking if pipe if full. Rust will never try to call continuation
    # callback more than once (so will not fill it up), hence this call should never block.
    wr.putc poll_code
  rescue Exception
    # Swallow exception. A leak or a hang is better than a hard VM segfault.
  end
end

# Poll a Rust future to completion.
#
# This works both with and without a Fiber::Scheduler:
# - Without scheduler: wait_readable blocks with a timeout, releasing the GVL
#   so the callback can fire from foreign threads (works around MRI limitation
#   where rb_thread_call_with_gvl cannot wake up threads in indefinite sleep).
# - With scheduler: wait_readable hooks into io_wait, yielding the fiber.
#
# cancel_fn is called in the ensure block when exception interrupts an in-flight poll.
# This guarantees Rust fires the continuation callback so the handle-map entry is released
# and the pipe is drained before we free the future.
def self.uniffi_wait_readable(io, timeout = nil)
  if io.respond_to?(:wait_readable)
    io.wait_readable(timeout)
  else
    IO.select([io], nil, nil, timeout)
  end
end

def self.uniffi_rust_call_async(rust_future, poll_fn, cancel_fn, complete_fn, free_fn, lift_func, error_ffi_converter)
  rd = wr = nil
  handle = nil
  poll_in_flight = false

  begin
    rd, wr = IO.pipe
    wr.sync = true # avoid buffering and delayed read for rd.wait_readable
    handle = UNIFFI_ASYNC_HANDLE_MAP.insert wr

    loop do
      poll_in_flight = true
      UniFFILib.public_send(poll_fn, rust_future, UNIFFI_CONTINUATION_CALLBACK, handle)

      # Blocks until the continuation callback writes to the pipe.
      # Releases the GVL so the callback can fire from foreign threads.
      # With a Fiber::Scheduler, this hooks into io_wait for non-blocking concurrency.
      uniffi_wait_readable(rd)
      poll_code = rd.getbyte
      poll_in_flight = false

      break if poll_code == UNIFFI_RUST_FUTURE_POLL_READY
    end

    result = if error_ffi_converter.nil?
      ::AcyclicActorsUniffi.rust_call(complete_fn, rust_future)
    else
      ::AcyclicActorsUniffi.rust_call_with_error(error_ffi_converter, complete_fn, rust_future)
    end

    lift_func.call(result)
  ensure
    # Defer any further Thread#raise / Timeout during cleanup so all steps execute
    # automatically. Without this, a second raise during wait_readable(0.5) would skip
    # handle-map removal, pipe close, and free_fn - leaking FDs and Rust memory.
    Thread.handle_interrupt(Exception => :never) do
      if poll_in_flight
        # An exception interrupted an in-flight poll. Cancel and drain the byte
        # the continuation callback will write so we don't leak the pipe.
        UniFFILib.public_send(cancel_fn, rust_future)
        # rd.wait_readable may time out and return nil if the poll was never actually sent
        # (raise landed between poll_in_flight=true and the FFI call).
        if uniffi_wait_readable(rd, 0.5)
          rd.getbyte
        end
      end

      # Remove handle first so any late-firing callback's `get` raises (swallowed by rescue).
      UNIFFI_ASYNC_HANDLE_MAP.remove(handle) rescue nil if handle
      rd&.close rescue nil
      wr&.close rescue nil
      UniFFILib.public_send(free_fn, rust_future)
    end
  end
end

  # Public interface members begin here.

  
  

  
  
def self.connect_actors(endpoint, token, cancellation)
    endpoint = AcyclicActorsUniffi::uniffi_utf8(endpoint)
    
    
    token = AcyclicActorsUniffi::uniffi_utf8(token)
    
    
    cancellation = (cancellation ? cancellation : nil)
    RustBuffer.check_lower_OptionalTypeCancellationHandle(cancellation)
    
  ::AcyclicActorsUniffi.uniffi_rust_call_async(
      UniFFILib.uniffi_acyclic_actors_uniffi_fn_func_connect_actors(RustBuffer.allocFromString(endpoint),RustBuffer.allocFromString(token),RustBuffer.alloc_from_OptionalTypeCancellationHandle(cancellation)),
      :ffi_acyclic_actors_uniffi_rust_future_poll_u64,
      :ffi_acyclic_actors_uniffi_rust_future_cancel_u64,
      :ffi_acyclic_actors_uniffi_rust_future_complete_u64,
      :ffi_acyclic_actors_uniffi_rust_future_free_u64,
      Proc.new { |v| ActorsClient.uniffi_allocate(v) },BindingError
    )
end
  
  
def self.connect_actors_with_ca(endpoint, token, ca_certificate, cancellation)
    endpoint = AcyclicActorsUniffi::uniffi_utf8(endpoint)
    
    
    token = AcyclicActorsUniffi::uniffi_utf8(token)
    
    
    ca_certificate = (ca_certificate ? AcyclicActorsUniffi::uniffi_bytes(ca_certificate) : nil)
    RustBuffer.check_lower_Optionalbytes(ca_certificate)
    
    cancellation = (cancellation ? cancellation : nil)
    RustBuffer.check_lower_OptionalTypeCancellationHandle(cancellation)
    
  ::AcyclicActorsUniffi.uniffi_rust_call_async(
      UniFFILib.uniffi_acyclic_actors_uniffi_fn_func_connect_actors_with_ca(RustBuffer.allocFromString(endpoint),RustBuffer.allocFromString(token),RustBuffer.alloc_from_Optionalbytes(ca_certificate),RustBuffer.alloc_from_OptionalTypeCancellationHandle(cancellation)),
      :ffi_acyclic_actors_uniffi_rust_future_poll_u64,
      :ffi_acyclic_actors_uniffi_rust_future_cancel_u64,
      :ffi_acyclic_actors_uniffi_rust_future_complete_u64,
      :ffi_acyclic_actors_uniffi_rust_future_free_u64,
      Proc.new { |v| ActorsClient.uniffi_allocate(v) },BindingError
    )
end
  
  

def self.validate_actor_id(value)
    value = AcyclicActorsUniffi::uniffi_utf8(value)
    
    
  AcyclicActorsUniffi.rust_call_with_error(BindingError,:uniffi_acyclic_actors_uniffi_fn_func_validate_actor_id,RustBuffer.allocFromString(value))
end

  
  

def self.validate_code_sha256(value)
    value = AcyclicActorsUniffi::uniffi_bytes(value)
    
    
  AcyclicActorsUniffi.rust_call_with_error(BindingError,:uniffi_acyclic_actors_uniffi_fn_func_validate_code_sha256,RustBuffer.allocFromBytes(value))
end

  
  

def self.validate_current_head(value)
    value = value ? true : false
    
    
  AcyclicActorsUniffi.rust_call_with_error(BindingError,:uniffi_acyclic_actors_uniffi_fn_func_validate_current_head,(value ? 1 : 0))
end

  
  

def self.validate_current_head_marker(value)
    value = value ? true : false
    
    
  AcyclicActorsUniffi.rust_call_with_error(BindingError,:uniffi_acyclic_actors_uniffi_fn_func_validate_current_head_marker,(value ? 1 : 0))
end

  
  

def self.validate_positive_u64(value)
    value = AcyclicActorsUniffi::uniffi_in_range(value, "u64", 0, 2**64)
    
    
  AcyclicActorsUniffi.rust_call_with_error(BindingError,:uniffi_acyclic_actors_uniffi_fn_func_validate_positive_u64,value)
end

  

  
  class ActorsClient

  # A private helper for initializing instances of the class from a raw handle,
  # bypassing any initialization logic and ensuring they are GC'd properly.
  def self.uniffi_allocate(handle)
    inst = allocate
    inst.instance_variable_set :@handle, handle
    ObjectSpace.define_finalizer(inst, uniffi_define_finalizer_by_handle(handle, inst.object_id))
    return inst
  end

  # A private helper for registering an object finalizer.
  # N.B. it's important that this does not capture a reference
  # to the actual instance, only its underlying handle.
  def self.uniffi_define_finalizer_by_handle(handle, object_id)
    Proc.new do |_id|
      AcyclicActorsUniffi.rust_call(
        :uniffi_acyclic_actors_uniffi_fn_free_actorsclient,
        handle
      )
    end
  end

  # A private helper for lowering instances into a raw handle.
  # This does an explicit typecheck, because accidentally lowering a different type of
  # object in a place where this type is expected, could lead to memory unsafety.
  def self.uniffi_check_lower(inst)
    if not inst.is_a? self
      raise TypeError.new "Expected a ActorsClient instance, got #{inst}"
    end
  end

  def uniffi_clone_handle()
    return AcyclicActorsUniffi.rust_call(
      :uniffi_acyclic_actors_uniffi_fn_clone_actorsclient,
      @handle
    )
  end

  def self.uniffi_lower(inst)
    return inst.uniffi_clone_handle()
  end

  

  
  def add_subscription(request, cancellation)
        request = request
        RustBuffer.check_lower_TypeAddSubscriptionRequest(request)
        cancellation = (cancellation ? cancellation : nil)
        RustBuffer.check_lower_OptionalTypeCancellationHandle(cancellation)
    ::AcyclicActorsUniffi.uniffi_rust_call_async(
      UniFFILib.uniffi_acyclic_actors_uniffi_fn_method_actorsclient_add_subscription(
        uniffi_clone_handle(),RustBuffer.alloc_from_TypeAddSubscriptionRequest(request),RustBuffer.alloc_from_OptionalTypeCancellationHandle(cancellation)),
      :ffi_acyclic_actors_uniffi_rust_future_poll_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_cancel_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_complete_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_free_rust_buffer,
      Proc.new { |v| v.consumeIntoTypeAddSubscriptionResponse },BindingError
    )
  end
  
  def checkpoint_actor(request, cancellation)
        request = request
        RustBuffer.check_lower_TypeCheckpointActorRequest(request)
        cancellation = (cancellation ? cancellation : nil)
        RustBuffer.check_lower_OptionalTypeCancellationHandle(cancellation)
    ::AcyclicActorsUniffi.uniffi_rust_call_async(
      UniFFILib.uniffi_acyclic_actors_uniffi_fn_method_actorsclient_checkpoint_actor(
        uniffi_clone_handle(),RustBuffer.alloc_from_TypeCheckpointActorRequest(request),RustBuffer.alloc_from_OptionalTypeCancellationHandle(cancellation)),
      :ffi_acyclic_actors_uniffi_rust_future_poll_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_cancel_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_complete_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_free_rust_buffer,
      Proc.new { |v| v.consumeIntoTypeCheckpointActorResponse },BindingError
    )
  end
  
  def create_actor(request, cancellation)
        request = request
        RustBuffer.check_lower_TypeCreateActorRequest(request)
        cancellation = (cancellation ? cancellation : nil)
        RustBuffer.check_lower_OptionalTypeCancellationHandle(cancellation)
    ::AcyclicActorsUniffi.uniffi_rust_call_async(
      UniFFILib.uniffi_acyclic_actors_uniffi_fn_method_actorsclient_create_actor(
        uniffi_clone_handle(),RustBuffer.alloc_from_TypeCreateActorRequest(request),RustBuffer.alloc_from_OptionalTypeCancellationHandle(cancellation)),
      :ffi_acyclic_actors_uniffi_rust_future_poll_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_cancel_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_complete_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_free_rust_buffer,
      Proc.new { |v| v.consumeIntoTypeCreateActorResponse },BindingError
    )
  end
  
  def inspect_actor(request, cancellation)
        request = request
        RustBuffer.check_lower_TypeInspectActorRequest(request)
        cancellation = (cancellation ? cancellation : nil)
        RustBuffer.check_lower_OptionalTypeCancellationHandle(cancellation)
    ::AcyclicActorsUniffi.uniffi_rust_call_async(
      UniFFILib.uniffi_acyclic_actors_uniffi_fn_method_actorsclient_inspect_actor(
        uniffi_clone_handle(),RustBuffer.alloc_from_TypeInspectActorRequest(request),RustBuffer.alloc_from_OptionalTypeCancellationHandle(cancellation)),
      :ffi_acyclic_actors_uniffi_rust_future_poll_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_cancel_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_complete_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_free_rust_buffer,
      Proc.new { |v| v.consumeIntoTypeInspectActorResponse },BindingError
    )
  end
  
  def invoke_actor(request, cancellation)
        request = request
        RustBuffer.check_lower_TypeInvokeActorRequest(request)
        cancellation = (cancellation ? cancellation : nil)
        RustBuffer.check_lower_OptionalTypeCancellationHandle(cancellation)
    ::AcyclicActorsUniffi.uniffi_rust_call_async(
      UniFFILib.uniffi_acyclic_actors_uniffi_fn_method_actorsclient_invoke_actor(
        uniffi_clone_handle(),RustBuffer.alloc_from_TypeInvokeActorRequest(request),RustBuffer.alloc_from_OptionalTypeCancellationHandle(cancellation)),
      :ffi_acyclic_actors_uniffi_rust_future_poll_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_cancel_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_complete_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_free_rust_buffer,
      Proc.new { |v| v.consumeIntoTypeInvokeActorResponse },BindingError
    )
  end
  
  def remove_subscription(request, cancellation)
        request = request
        RustBuffer.check_lower_TypeRemoveSubscriptionRequest(request)
        cancellation = (cancellation ? cancellation : nil)
        RustBuffer.check_lower_OptionalTypeCancellationHandle(cancellation)
    ::AcyclicActorsUniffi.uniffi_rust_call_async(
      UniFFILib.uniffi_acyclic_actors_uniffi_fn_method_actorsclient_remove_subscription(
        uniffi_clone_handle(),RustBuffer.alloc_from_TypeRemoveSubscriptionRequest(request),RustBuffer.alloc_from_OptionalTypeCancellationHandle(cancellation)),
      :ffi_acyclic_actors_uniffi_rust_future_poll_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_cancel_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_complete_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_free_rust_buffer,
      Proc.new { |v| v.consumeIntoTypeRemoveSubscriptionResponse },BindingError
    )
  end
  
  def resume_subscription(request, cancellation)
        request = request
        RustBuffer.check_lower_TypeResumeSubscriptionRequest(request)
        cancellation = (cancellation ? cancellation : nil)
        RustBuffer.check_lower_OptionalTypeCancellationHandle(cancellation)
    ::AcyclicActorsUniffi.uniffi_rust_call_async(
      UniFFILib.uniffi_acyclic_actors_uniffi_fn_method_actorsclient_resume_subscription(
        uniffi_clone_handle(),RustBuffer.alloc_from_TypeResumeSubscriptionRequest(request),RustBuffer.alloc_from_OptionalTypeCancellationHandle(cancellation)),
      :ffi_acyclic_actors_uniffi_rust_future_poll_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_cancel_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_complete_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_free_rust_buffer,
      Proc.new { |v| v.consumeIntoTypeResumeSubscriptionResponse },BindingError
    )
  end
  
  def update_actor(request, cancellation)
        request = request
        RustBuffer.check_lower_TypeUpdateActorRequest(request)
        cancellation = (cancellation ? cancellation : nil)
        RustBuffer.check_lower_OptionalTypeCancellationHandle(cancellation)
    ::AcyclicActorsUniffi.uniffi_rust_call_async(
      UniFFILib.uniffi_acyclic_actors_uniffi_fn_method_actorsclient_update_actor(
        uniffi_clone_handle(),RustBuffer.alloc_from_TypeUpdateActorRequest(request),RustBuffer.alloc_from_OptionalTypeCancellationHandle(cancellation)),
      :ffi_acyclic_actors_uniffi_rust_future_poll_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_cancel_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_complete_rust_buffer,
      :ffi_acyclic_actors_uniffi_rust_future_free_rust_buffer,
      Proc.new { |v| v.consumeIntoTypeUpdateActorResponse },BindingError
    )
  end
  
end
  
  class CancellationHandle

  # A private helper for initializing instances of the class from a raw handle,
  # bypassing any initialization logic and ensuring they are GC'd properly.
  def self.uniffi_allocate(handle)
    inst = allocate
    inst.instance_variable_set :@handle, handle
    ObjectSpace.define_finalizer(inst, uniffi_define_finalizer_by_handle(handle, inst.object_id))
    return inst
  end

  # A private helper for registering an object finalizer.
  # N.B. it's important that this does not capture a reference
  # to the actual instance, only its underlying handle.
  def self.uniffi_define_finalizer_by_handle(handle, object_id)
    Proc.new do |_id|
      AcyclicActorsUniffi.rust_call(
        :uniffi_acyclic_actors_uniffi_fn_free_cancellationhandle,
        handle
      )
    end
  end

  # A private helper for lowering instances into a raw handle.
  # This does an explicit typecheck, because accidentally lowering a different type of
  # object in a place where this type is expected, could lead to memory unsafety.
  def self.uniffi_check_lower(inst)
    if not inst.is_a? self
      raise TypeError.new "Expected a CancellationHandle instance, got #{inst}"
    end
  end

  def uniffi_clone_handle()
    return AcyclicActorsUniffi.rust_call(
      :uniffi_acyclic_actors_uniffi_fn_clone_cancellationhandle,
      @handle
    )
  end

  def self.uniffi_lower(inst)
    return inst.uniffi_clone_handle()
  end
  def initialize()
    handle = AcyclicActorsUniffi.rust_call(:uniffi_acyclic_actors_uniffi_fn_constructor_cancellationhandle_new,)
    @handle = handle
    ObjectSpace.define_finalizer(self, self.class.uniffi_define_finalizer_by_handle(handle, self.object_id))
  end

  

  def cancel()
      AcyclicActorsUniffi.rust_call(:uniffi_acyclic_actors_uniffi_fn_method_cancellationhandle_cancel,uniffi_clone_handle(),)
  end
  
  def is_cancelled()
    result = AcyclicActorsUniffi.rust_call(:uniffi_acyclic_actors_uniffi_fn_method_cancellationhandle_is_cancelled,uniffi_clone_handle(),)
    return 1 == result
  end
  
end
  

  
  EXTERNAL_RUSTBUFFER_MODULES = [
  
    AcyclicActors::RustBuffer,
  
  ]
  class RustBuffer
    class << self
      def method_missing(name, *args, &block)
        converter = EXTERNAL_RUSTBUFFER_MODULES.find { |mod| mod.respond_to?(name) }
        return converter.public_send(name, *args, &block) if converter
        super
      end

      def respond_to_missing?(name, include_private = false)
        EXTERNAL_RUSTBUFFER_MODULES.any? { |mod| mod.respond_to?(name, include_private) } || super
      end
    end

    def method_missing(name, *args, &block)
      converter = EXTERNAL_RUSTBUFFER_MODULES.find { |mod| mod.public_instance_methods.include?(name) }
      return converter.new(self.pointer).public_send(name, *args, &block) if converter
      super
    end

    def respond_to_missing?(name, include_private = false)
      EXTERNAL_RUSTBUFFER_MODULES.any? { |mod| mod.public_instance_methods.include?(name) } || super
    end
  end


end