// Generated by acyclic-sdk-contract-wire; do not edit.
// rust_policy_source_binding: C3EB0FB2EC4A1E44476E73FDBFF3FCE33616AE7DB6A819763FDD2711CFC1A199
#pragma warning disable CS1591

using System;
using System.Collections.Generic;

namespace Acyclic.Sdk.Transport;

public static class GeneratedRemotePolicy
{
    public enum Runtime { Native, Browser }
    public enum Transport { Grpc, GrpcWeb, HttpJson }
    public readonly record struct Option(Transport Transport, bool Streaming, bool BearerAuth);
    public readonly record struct Operation(bool ClientStreaming, bool ServerStreaming, bool BearerAuth, string Cancellation);
    public readonly record struct Availability(bool Grpc, bool GrpcWeb, bool HttpJson)
    {
        public static readonly Availability All = new(true, true, true);
        public static readonly Availability GrpcOnly = new(true, false, false);
        public bool Supports(Transport transport) => transport switch
        {
            Transport.Grpc => Grpc,
            Transport.GrpcWeb => GrpcWeb,
            Transport.HttpJson => HttpJson,
            _ => false
        };
    }
    public readonly record struct Defaults(string Endpoint, string BearerToken)
    {
        public static Defaults FromEnvironment() => new(
            FirstNonBlank(Environment.GetEnvironmentVariable("ACYCLIC_ENDPOINT"), "http://127.0.0.1:8080"),
            Environment.GetEnvironmentVariable("ACYCLIC_BEARER_TOKEN") ?? string.Empty);
    }

    public const string SourceBinding = "C3EB0FB2EC4A1E44476E73FDBFF3FCE33616AE7DB6A819763FDD2711CFC1A199";
    public const string Probe = "none";
    public const string PostFailureFallback = "none";
    public const string Replay = "none";
    public static readonly IReadOnlyDictionary<Runtime, IReadOnlyDictionary<string, IReadOnlyList<Option>>> Options =
        new Dictionary<Runtime, IReadOnlyDictionary<string, IReadOnlyList<Option>>>
        {
            [Runtime.Native] = BuildOptions(Runtime.Native),
            [Runtime.Browser] = BuildOptions(Runtime.Browser),
        };
    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, Operation>> Operations = BuildOperations();

    private static IReadOnlyDictionary<string, IReadOnlyList<Option>> BuildOptions(Runtime runtime)
    {
        var result = new Dictionary<string, IReadOnlyList<Option>>(StringComparer.Ordinal);
        switch (runtime)
        {
            case Runtime.Native:
                result["actors"] = new Option[] {new(Transport.Grpc, false, true), new(Transport.HttpJson, false, true)};
                result["workers"] = new Option[] {new(Transport.Grpc, false, true), new(Transport.HttpJson, false, true)};
                result["objects"] = new Option[] {new(Transport.Grpc, true, true), new(Transport.HttpJson, true, true)};
                result["stream"] = new Option[] {new(Transport.Grpc, true, true), new(Transport.HttpJson, true, true)};
                result["inference"] = new Option[] {new(Transport.Grpc, true, true), new(Transport.HttpJson, true, true)};
                result["machines"] = new Option[] {new(Transport.Grpc, true, false)};
                result["filesystem"] = new Option[] {new(Transport.Grpc, true, true)};
                result["harness"] = new Option[] {new(Transport.Grpc, true, true)};
                break;
            case Runtime.Browser:
                result["actors"] = new Option[] {new(Transport.HttpJson, false, true)};
                result["workers"] = new Option[] {new(Transport.HttpJson, false, true)};
                result["objects"] = new Option[] {new(Transport.HttpJson, true, true)};
                result["stream"] = new Option[] {new(Transport.HttpJson, true, true)};
                result["inference"] = new Option[] {new(Transport.HttpJson, true, true)};
                result["machines"] = new Option[] {};
                result["filesystem"] = new Option[] {new(Transport.GrpcWeb, true, true)};
                result["harness"] = new Option[] {};
                break;
        }
        return result;
    }

    private static IReadOnlyDictionary<string, IReadOnlyDictionary<string, Operation>> BuildOperations()
    {
        var result = new Dictionary<string, IReadOnlyDictionary<string, Operation>>(StringComparer.Ordinal);
        var actors = new Dictionary<string, Operation>(StringComparer.Ordinal);
        actors["acyclic.actors.v1.ActorsService/CreateActor"] = new(false, false, true, "none");
        actors["acyclic.actors.v1.ActorsService/UpdateActor"] = new(false, false, true, "none");
        actors["acyclic.actors.v1.ActorsService/InspectActor"] = new(false, false, true, "none");
        actors["acyclic.actors.v1.ActorsService/AddSubscription"] = new(false, false, true, "none");
        actors["acyclic.actors.v1.ActorsService/RemoveSubscription"] = new(false, false, true, "none");
        actors["acyclic.actors.v1.ActorsService/ResumeSubscription"] = new(false, false, true, "none");
        actors["acyclic.actors.v1.ActorsService/CheckpointActor"] = new(false, false, true, "none");
        actors["acyclic.actors.v1.ActorsService/InvokeActor"] = new(false, false, true, "none");
        result["actors"] = actors.AsReadOnly();
        var workers = new Dictionary<string, Operation>(StringComparer.Ordinal);
        workers["acyclic.workers.v1.WorkersService/PublishVersion"] = new(false, false, true, "none");
        workers["acyclic.workers.v1.WorkersService/SelectDeployment"] = new(false, false, true, "none");
        workers["acyclic.workers.v1.WorkersService/SubmitJob"] = new(false, false, true, "none");
        workers["acyclic.workers.v1.WorkersService/InspectJob"] = new(false, false, true, "none");
        workers["acyclic.workers.v1.WorkersService/CancelJob"] = new(false, false, true, "none");
        workers["acyclic.workers.v1.WorkersService/InvokeVersion"] = new(false, false, true, "none");
        workers["acyclic.workers.v1.WorkersService/InvokeDeployment"] = new(false, false, true, "none");
        result["workers"] = workers.AsReadOnly();
        var objects = new Dictionary<string, Operation>(StringComparer.Ordinal);
        objects["acyclic.objects.v2.BucketsService/CreateBucket"] = new(false, false, true, "none");
        objects["acyclic.objects.v2.BucketsService/HeadBucket"] = new(false, false, true, "none");
        objects["acyclic.objects.v2.BucketsService/DeleteBucket"] = new(false, false, true, "none");
        objects["acyclic.objects.v2.ObjectsService/PutObject"] = new(true, false, true, "call");
        objects["acyclic.objects.v2.ObjectsService/GetObject"] = new(false, true, true, "call");
        objects["acyclic.objects.v2.ObjectsService/HeadObject"] = new(false, false, true, "none");
        objects["acyclic.objects.v2.ObjectsService/DeleteObject"] = new(false, false, true, "none");
        objects["acyclic.objects.v2.ObjectsService/ListObjects"] = new(false, false, true, "none");
        objects["acyclic.objects.v2.MultipartService/CreateMultipart"] = new(false, false, true, "none");
        objects["acyclic.objects.v2.MultipartService/UploadPart"] = new(true, false, true, "call");
        objects["acyclic.objects.v2.MultipartService/ListParts"] = new(false, false, true, "none");
        objects["acyclic.objects.v2.MultipartService/CompleteMultipart"] = new(false, false, true, "none");
        objects["acyclic.objects.v2.MultipartService/AbortMultipart"] = new(false, false, true, "none");
        result["objects"] = objects.AsReadOnly();
        var stream = new Dictionary<string, Operation>(StringComparer.Ordinal);
        stream["acyclic.stream.v2.StreamService/InspectIdempotency"] = new(false, false, true, "none");
        stream["acyclic.stream.v2.StreamService/Append"] = new(false, false, true, "none");
        stream["acyclic.stream.v2.StreamService/Tail"] = new(false, false, true, "none");
        stream["acyclic.stream.v2.StreamService/Fork"] = new(false, false, true, "none");
        stream["acyclic.stream.v2.StreamService/Read"] = new(false, true, true, "call");
        stream["acyclic.stream.v2.StreamService/Follow"] = new(false, true, true, "call");
        stream["acyclic.stream.v2.StreamService/Children"] = new(false, true, true, "call");
        stream["acyclic.stream.v2.StreamService/ChildrenPage"] = new(false, false, true, "none");
        stream["acyclic.stream.v2.StreamService/Commit"] = new(false, false, true, "none");
        stream["acyclic.stream.v2.StreamService/ReadCommit"] = new(false, false, true, "none");
        result["stream"] = stream.AsReadOnly();
        var inference = new Dictionary<string, Operation>(StringComparer.Ordinal);
        inference["inference.customer.v1.ModelsService/List"] = new(false, false, true, "none");
        inference["inference.customer.v1.ContextsService/Create"] = new(false, false, true, "none");
        inference["inference.customer.v1.ContextsService/Inspect"] = new(false, false, true, "none");
        inference["inference.customer.v1.ContextsService/Mutate"] = new(false, false, true, "none");
        inference["inference.customer.v1.WarmContextsService/Retain"] = new(false, false, true, "none");
        inference["inference.customer.v1.WarmContextsService/Inspect"] = new(false, false, true, "none");
        inference["inference.customer.v1.WarmContextsService/Renew"] = new(false, false, true, "none");
        inference["inference.customer.v1.WarmContextsService/Release"] = new(false, false, true, "none");
        inference["inference.customer.v1.RunsService/Generate"] = new(false, false, true, "none");
        inference["inference.customer.v1.RunsService/Inspect"] = new(false, false, true, "none");
        inference["inference.customer.v1.RunsService/Watch"] = new(false, true, true, "call");
        inference["inference.customer.v1.RunsService/Cancel"] = new(false, false, true, "operation");
        inference["inference.customer.v1.EvaluationsService/Create"] = new(false, false, true, "none");
        inference["inference.customer.v1.EvaluationsService/Inspect"] = new(false, false, true, "none");
        result["inference"] = inference.AsReadOnly();
        var machines = new Dictionary<string, Operation>(StringComparer.Ordinal);
        machines["acyclic.machines.v1.MachinesService/QualifyImage"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/Create"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/Checkpoint"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/Fork"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/ForkMachine"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/Suspend"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/Wake"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/SetSuspensionPolicy"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/DestroyMachine"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/DestroyCheckpoint"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/Recover"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/InspectMachine"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/InspectCheckpoint"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/ListMachines"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/Events"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/Usage"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/Cancel"] = new(false, false, false, "operation");
        machines["acyclic.machines.v1.MachinesService/InspectOperation"] = new(false, false, false, "none");
        machines["acyclic.machines.v1.MachinesService/WatchOperation"] = new(false, true, false, "call");
        result["machines"] = machines.AsReadOnly();
        var filesystem = new Dictionary<string, Operation>(StringComparer.Ordinal);
        filesystem["acyclic.filesystem.v2.FilesystemService/Handshake"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/CreateWorkspace"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/OpenWorkspace"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/DeleteWorkspace"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/GetHead"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/GetGeneration"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/Read"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/Stat"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/ListDirectory"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/ReadLink"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/PlanExtents"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/ApplyTransaction"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/RebaseTransaction"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/ForkWorkspace"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/Diff"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/Rebase"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/PlanJoin"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/ApplyJoin"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/Checkpoint"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/Pin"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/Export"] = new(false, true, true, "call");
        filesystem["acyclic.filesystem.v2.FilesystemService/Import"] = new(true, false, true, "call");
        filesystem["acyclic.filesystem.v2.FilesystemService/IssueMountCredential"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/IssueS3Credential"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/GetSourceState"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/ReconcileSource"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/RescanSource"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/SealSource"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/Observe"] = new(false, false, true, "none");
        filesystem["acyclic.filesystem.v2.FilesystemService/Cancel"] = new(false, false, true, "operation");
        result["filesystem"] = filesystem.AsReadOnly();
        var harness = new Dictionary<string, Operation>(StringComparer.Ordinal);
        harness["acyclic.harness.v2.HarnessService/Handshake"] = new(false, false, true, "none");
        harness["acyclic.harness.v2.HarnessService/Submit"] = new(false, false, true, "none");
        harness["acyclic.harness.v2.HarnessService/Replay"] = new(false, true, true, "call");
        harness["acyclic.harness.v2.HarnessService/Observe"] = new(false, false, true, "none");
        harness["acyclic.harness.v2.HarnessService/Cancel"] = new(false, false, true, "operation");
        result["harness"] = harness.AsReadOnly();
        return result;
    }

    public static Transport Select(
        string family,
        Runtime runtime,
        bool streaming,
        bool bearerAuth,
        Availability installed,
        Availability endpoint,
        Transport? overrideTransport = null)
    {
        if (!Options.TryGetValue(runtime, out var byFamily) || !byFamily.TryGetValue(family, out var familyOptions))
            throw new ArgumentException($"unknown transport family or runtime: {family}/{runtime}");
        foreach (var option in familyOptions)
        {
            if (overrideTransport == option.Transport && Compatible(option, streaming, bearerAuth, installed, endpoint))
                return option.Transport;
        }
        if (overrideTransport is not null)
            throw new ArgumentException($"unsupported transport override for {family}/{runtime}");
        foreach (var option in familyOptions)
        {
            if (Compatible(option, streaming, bearerAuth, installed, endpoint)) return option.Transport;
        }
        throw new ArgumentException($"no compatible transport for {family}/{runtime}");
    }

    private static bool Compatible(Option option, bool streaming, bool bearerAuth,
        Availability installed, Availability endpoint) => installed.Supports(option.Transport)
        && endpoint.Supports(option.Transport)
        && (!streaming || option.Streaming)
        && (!bearerAuth || option.BearerAuth);

    public static bool RequiresBearer(string family, Runtime runtime)
    {
        if (!Options.TryGetValue(runtime, out var byFamily) ||
            !byFamily.TryGetValue(family, out var familyOptions) || familyOptions.Count == 0)
            throw new ArgumentException($"unknown transport family or runtime: {family}/{runtime}");
        return familyOptions[0].BearerAuth;
    }

    public static string ValidateBearer(string token)
    {
        if (string.IsNullOrWhiteSpace(token) || token.Contains('\r') || token.Contains('\n'))
            throw new ArgumentException("invalid bearer credential", nameof(token));
        return token;
    }

    private static string FirstNonBlank(string? value, string fallback) =>
        string.IsNullOrWhiteSpace(value) ? fallback : value;
}
