//! Source files that define the compiled SDK generator's behavior.

/// Files whose contents or dependency selection can change generated SDK or
/// documentation output.
pub const PATHS: &[&str] = &[
    "package.json",
    "bun.lock",
    "release/cargo-crates.json",
    "proto/actors/v1/actors.proto",
    "scripts/generate-contracts.mjs",
    "scripts/generate-runtime-routes.mjs",
    "scripts/generate.mjs",
    "scripts/stage-actors-contract.mjs",
    "rust/crates/actors/build.rs",
    "rust/crates/actors/src/contract_definitions.rs",
    "rust/crates/actors/src/wire.rs",
    "rust/crates/actors/examples/actors-contract.rs",
    "rust/crates/actors/examples/actors-descriptor.rs",
    "scripts/build-wasm.mjs",
    "scripts/ensure-wasm-bindgen.sh",
    "scripts/filesystem-napi-types.mjs",
    "rust/crates/actors/src/codegen.rs",
    "rust/crates/actors/src/contract.rs",
    "rust/crates/actors/src/domain.rs",
    "rust/crates/actors/src/grpc.rs",
    "rust/crates/actors/src/http.rs",
    "rust/crates/actors/Cargo.toml",
    "rust/crates/actors/src/lib.rs",
    "rust/crates/workers/src/grpc.rs",
    "rust/crates/workers/src/http.rs",
    "rust/crates/workers/src/lib.rs",
    "rust/crates/workers/Cargo.toml",
    "rust/crates/sdk-docs/Cargo.toml",
    "rust/crates/sdk-docs/Cargo.lock",
    "rust/crates/sdk-docs/src/lib.rs",
    "rust/crates/sdk-docs/src/public_api.rs",
    "rust/crates/sdk-generation/Cargo.toml",
    "rust/crates/sdk-generation/Cargo.lock",
    "rust/crates/sdk-generation/build.rs",
    "rust/crates/sdk-generation/src/compiled_generator_inputs.rs",
    "rust/crates/sdk-generation/src/main.rs",
];
