// @generated by Rust sdk-contracts; do not edit.

export const MANAGED_OCI_CONTRACT = Object.freeze({
  separator: "@sha256:",
  digestHexLength: 64,
  hexDigits: "0123456789abcdefABCDEF",
  zeroDigit: "0",
  maxPageSize: 256,
  maxEventPageSize: 1024,
} as const);
