<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actors/v1/actors.proto

namespace Acyclic\Actors\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A capability binding made available to an actor.
 *
 * Generated from protobuf message <code>acyclic.actors.v1.Binding</code>
 */
class Binding extends \Google\Protobuf\Internal\Message
{
    /**
     * The stable name of the binding or header.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * The capability granted by the binding.
     *
     * Generated from protobuf field <code>string capability = 2;</code>
     */
    protected $capability = '';
    /**
     * The resource selected by the binding.
     *
     * Generated from protobuf field <code>string resource = 3;</code>
     */
    protected $resource = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The stable name of the binding or header.
     *     @type string $capability
     *           The capability granted by the binding.
     *     @type string $resource
     *           The resource selected by the binding.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Actors\V1\Actors::initOnce();
        parent::__construct($data);
    }

    /**
     * The stable name of the binding or header.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The stable name of the binding or header.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * The capability granted by the binding.
     *
     * Generated from protobuf field <code>string capability = 2;</code>
     * @return string
     */
    public function getCapability()
    {
        return $this->capability;
    }

    /**
     * The capability granted by the binding.
     *
     * Generated from protobuf field <code>string capability = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCapability(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->capability = $var;

        return $this;
    }

    /**
     * The resource selected by the binding.
     *
     * Generated from protobuf field <code>string resource = 3;</code>
     * @return string
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * The resource selected by the binding.
     *
     * Generated from protobuf field <code>string resource = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setResource(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->resource = $var;

        return $this;
    }

}

