<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actors/v1/actors.proto

namespace Acyclic\Actors\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Creates an actor and its initial subscriptions.
 *
 * Generated from protobuf message <code>acyclic.actors.v1.CreateActorRequest</code>
 */
class CreateActorRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * SHA-256 digest of the actor code.
     *
     * Generated from protobuf field <code>bytes code_sha256 = 1;</code>
     */
    protected $code_sha256 = '';
    /**
     * The actor's home region.
     *
     * Generated from protobuf field <code>string home_region = 2;</code>
     */
    protected $home_region = '';
    /**
     * Capability bindings supplied to the actor.
     *
     * Generated from protobuf field <code>repeated .acyclic.actors.v1.Binding bindings = 3;</code>
     */
    private $bindings;
    /**
     * Resource and checkpoint limits supplied to the actor.
     *
     * Generated from protobuf field <code>.acyclic.actors.v1.ActorLimits limits = 4;</code>
     */
    protected $limits = null;
    /**
     * Subscriptions associated with the actor.
     *
     * Generated from protobuf field <code>repeated .acyclic.actors.v1.SubscriptionSpec subscriptions = 5;</code>
     */
    private $subscriptions;
    /**
     * Client key used to make a mutation idempotent.
     *
     * Generated from protobuf field <code>string idempotency_key = 6;</code>
     */
    protected $idempotency_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code_sha256
     *           SHA-256 digest of the actor code.
     *     @type string $home_region
     *           The actor's home region.
     *     @type \Acyclic\Actors\V1\Binding[] $bindings
     *           Capability bindings supplied to the actor.
     *     @type \Acyclic\Actors\V1\ActorLimits $limits
     *           Resource and checkpoint limits supplied to the actor.
     *     @type \Acyclic\Actors\V1\SubscriptionSpec[] $subscriptions
     *           Subscriptions associated with the actor.
     *     @type string $idempotency_key
     *           Client key used to make a mutation idempotent.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Actors\V1\Actors::initOnce();
        parent::__construct($data);
    }

    /**
     * SHA-256 digest of the actor code.
     *
     * Generated from protobuf field <code>bytes code_sha256 = 1;</code>
     * @return string
     */
    public function getCodeSha256()
    {
        return $this->code_sha256;
    }

    /**
     * SHA-256 digest of the actor code.
     *
     * Generated from protobuf field <code>bytes code_sha256 = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCodeSha256(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->code_sha256 = $var;

        return $this;
    }

    /**
     * The actor's home region.
     *
     * Generated from protobuf field <code>string home_region = 2;</code>
     * @return string
     */
    public function getHomeRegion()
    {
        return $this->home_region;
    }

    /**
     * The actor's home region.
     *
     * Generated from protobuf field <code>string home_region = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHomeRegion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->home_region = $var;

        return $this;
    }

    /**
     * Capability bindings supplied to the actor.
     *
     * Generated from protobuf field <code>repeated .acyclic.actors.v1.Binding bindings = 3;</code>
     * @return RepeatedField<\Acyclic\Actors\V1\Binding>
     */
    public function getBindings()
    {
        return $this->bindings;
    }

    /**
     * Capability bindings supplied to the actor.
     *
     * Generated from protobuf field <code>repeated .acyclic.actors.v1.Binding bindings = 3;</code>
     * @param \Acyclic\Actors\V1\Binding[] $var
     * @return $this
     */
    public function setBindings(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Acyclic\Actors\V1\Binding::class);
        $this->bindings = $arr;

        return $this;
    }

    /**
     * Resource and checkpoint limits supplied to the actor.
     *
     * Generated from protobuf field <code>.acyclic.actors.v1.ActorLimits limits = 4;</code>
     * @return \Acyclic\Actors\V1\ActorLimits|null
     */
    public function getLimits()
    {
        return $this->limits;
    }

    public function hasLimits()
    {
        return isset($this->limits);
    }

    public function clearLimits()
    {
        unset($this->limits);
    }

    /**
     * Resource and checkpoint limits supplied to the actor.
     *
     * Generated from protobuf field <code>.acyclic.actors.v1.ActorLimits limits = 4;</code>
     * @param \Acyclic\Actors\V1\ActorLimits $var
     * @return $this
     */
    public function setLimits(\Acyclic\Actors\V1\ActorLimits|null $var)
    {
        $this->limits = $var;

        return $this;
    }

    /**
     * Subscriptions associated with the actor.
     *
     * Generated from protobuf field <code>repeated .acyclic.actors.v1.SubscriptionSpec subscriptions = 5;</code>
     * @return RepeatedField<\Acyclic\Actors\V1\SubscriptionSpec>
     */
    public function getSubscriptions()
    {
        return $this->subscriptions;
    }

    /**
     * Subscriptions associated with the actor.
     *
     * Generated from protobuf field <code>repeated .acyclic.actors.v1.SubscriptionSpec subscriptions = 5;</code>
     * @param \Acyclic\Actors\V1\SubscriptionSpec[] $var
     * @return $this
     */
    public function setSubscriptions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Acyclic\Actors\V1\SubscriptionSpec::class);
        $this->subscriptions = $arr;

        return $this;
    }

    /**
     * Client key used to make a mutation idempotent.
     *
     * Generated from protobuf field <code>string idempotency_key = 6;</code>
     * @return string
     */
    public function getIdempotencyKey()
    {
        return $this->idempotency_key;
    }

    /**
     * Client key used to make a mutation idempotent.
     *
     * Generated from protobuf field <code>string idempotency_key = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setIdempotencyKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->idempotency_key = $var;

        return $this;
    }

}

