<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actors/v1/actors.proto

namespace Acyclic\Actors\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * An HTTP-style invocation header.
 *
 * Generated from protobuf message <code>acyclic.actors.v1.Header</code>
 */
class Header extends \Google\Protobuf\Internal\Message
{
    /**
     * The stable name of the binding or header.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * A field in the Actors v1 wire contract.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The stable name of the binding or header.
     *     @type string $value
     *           A field in the Actors v1 wire contract.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Actors\V1\Actors::initOnce();
        parent::__construct($data);
    }

    /**
     * The stable name of the binding or header.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The stable name of the binding or header.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * A field in the Actors v1 wire contract.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * A field in the Actors v1 wire contract.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->value = $var;

        return $this;
    }

}

