// Generated by acyclic-sdk-contract-wire; do not edit.
// rust_policy_source_binding: E47ED4BFA56F81A2E3B8EA51C0E67E1AD4909C47F06B30EE11F6D3EDA573F649

package acyclicsdk

import (
    "context"
    "crypto/tls"
    "crypto/x509"
    "fmt"
    "net/url"
    "strings"

    actorsv1 "github.com/acyclic-labs/sdk/go/gen/actors/v1"
    filesystemv2 "github.com/acyclic-labs/sdk/go/gen/filesystem/v2"
    harnessv2 "github.com/acyclic-labs/sdk/go/gen/harness/v2"
    inferencev1 "github.com/acyclic-labs/sdk/go/gen/inference/v1"
    machinesv1 "github.com/acyclic-labs/sdk/go/gen/machines/v1"
    objectsv2 "github.com/acyclic-labs/sdk/go/gen/objects/v2"
    streamv2 "github.com/acyclic-labs/sdk/go/gen/stream/v2"
    workersv1 "github.com/acyclic-labs/sdk/go/gen/workers/v1"
    "google.golang.org/grpc"
    "google.golang.org/grpc/credentials"
    "google.golang.org/grpc/credentials/insecure"
    "google.golang.org/grpc/metadata"
    "unicode/utf8"
)

// Rust-owned semantic type projection; generated from type_policy.rs.

var SemanticTypeRules = map[string][]string{
	"actor_id": {"non_empty", "utf8"},
	"method": {"non_empty", "utf8"},
	"path": {"non_empty", "utf8"},
	"source": {"non_empty", "utf8"},
	"destination": {"non_empty", "utf8"},
	"bucket_name": {"non_empty", "utf8"},
	"object_key": {"non_empty", "utf8"},
	"alias": {"non_empty", "utf8"},
	"job_id": {"non_empty", "utf8"},
	"machine_id": {"non_empty", "utf8"},
	"operation_id": {"non_empty", "utf8"},
	"checkpoint_id": {"non_empty", "utf8"},
	"idempotency_key_bytes": {"non_empty"},
	"idempotency_key_text": {"non_empty", "utf8"},
	"idempotency_key_message": {},
	"opaque_text": {"non_empty", "utf8"},
	"upload_id": {"non_empty", "utf8"},
	"version_sha256": {"fixed_length:32", "sha256_digest"},
	"sha256_digest": {"fixed_length:32", "sha256_digest"},
	"revision_digest": {"fixed_length:32"},
	"immutable_image": {"immutable"},
	"revision": {"non_negative"},
	"run_id": {"fixed_length:16"},
	"evaluation_id": {"fixed_length:16"},
	"page_limit": {"strictly_positive", "max_items:1000"},
	"commit_id": {"non_empty"},
	"enum_value": {"preserve_unknown_enum"},
	"oneof_arm": {"exact_oneof", "preserve_unknown_oneof"},
}

var FieldSemanticTypes = map[string]string{
	"actors.actor_id": "actor_id",
	"actors.method": "method",
	"workers.alias": "alias",
	"workers.version_sha256": "version_sha256",
	"workers.idempotency_key": "idempotency_key_text",
	"workers.job_id": "job_id",
	"workers.method": "method",
	"stream.idempotency_key": "idempotency_key_bytes",
	"stream.path": "path",
	"stream.source": "source",
	"stream.destination": "destination",
	"stream.limit": "page_limit",
	"stream.commit_id": "commit_id",
	"objects.key": "object_key",
	"objects.etag": "opaque_text",
	"objects.idempotency_key": "idempotency_key_text",
	"objects.upload_id": "upload_id",
	"objects.page_size": "page_limit",
	"inference.run_id": "run_id",
	"inference.revision": "revision_digest",
	"inference.commitment": "sha256_digest",
	"inference.evaluation_id": "evaluation_id",
	"inference.spec_digest": "sha256_digest",
	"machines.image": "immutable_image",
	"machines.idempotency_key": "idempotency_key_message",
	"machines.machine_id": "machine_id",
	"machines.checkpoint_id": "checkpoint_id",
	"machines.operation_id": "operation_id",
	"machines.page_limit": "page_limit",
	"filesystem.path": "path",
	"harness.path": "path",
}

type UnknownEnumValue struct { RawValue int32 }

type WireChoice interface { isWireChoice() }

type UnknownOneof struct { RawPayload []byte }

func (UnknownOneof) isWireChoice() {}

type ActorID string

type MethodName string

type ResourcePath string

type SourceName string

type DestinationName string

type BucketName string

type ObjectKey string

type VersionAlias string

type JobID string

type MachineID string

type OperationID string

type CheckpointID string

type IdempotencyKeyBytes []byte

type IdempotencyKeyText string

type IdempotencyKey any

type OpaqueText string

type UploadID string

type Sha256Digest [32]byte

type RevisionDigest [32]byte

type Image any

type Revision uint64

type RunID [16]byte

type EvaluationID [16]byte

type PageLimit uint64

type CommitID []byte

type OpenEnumValue int32

func requireGoText(value, name string) error {
    if value == "" { return fmt.Errorf("%s must not be empty", name) }
    if !utf8.ValidString(value) { return fmt.Errorf("%s must be valid UTF-8", name) }
    return nil
}

func requireGoBytes(value []byte, name string, length int) error {
    if len(value) == 0 { return fmt.Errorf("%s must not be empty", name) }
    if length >= 0 && len(value) != length { return fmt.Errorf("%s must contain exactly %d bytes", name, length) }
    return nil
}

func requireGoUint(value uint64, name string, minimum, maximum uint64) error {
    if value < minimum { return fmt.Errorf("%s must be at least %d", name, minimum) }
    if maximum != 0 && value > maximum { return fmt.Errorf("%s must be at most %d", name, maximum) }
    return nil
}

func NewActorID(value string) (ActorID, error) {
	if err := requireGoText(value, "actor_id"); err != nil { return "", err }
	return ActorID(value), nil
}

func NewMethodName(value string) (MethodName, error) {
	if err := requireGoText(value, "method"); err != nil { return "", err }
	return MethodName(value), nil
}

func NewResourcePath(value string) (ResourcePath, error) {
	if err := requireGoText(value, "path"); err != nil { return "", err }
	return ResourcePath(value), nil
}

func NewSourceName(value string) (SourceName, error) {
	if err := requireGoText(value, "source"); err != nil { return "", err }
	return SourceName(value), nil
}

func NewDestinationName(value string) (DestinationName, error) {
	if err := requireGoText(value, "destination"); err != nil { return "", err }
	return DestinationName(value), nil
}

func NewBucketName(value string) (BucketName, error) {
	if err := requireGoText(value, "bucket_name"); err != nil { return "", err }
	return BucketName(value), nil
}

func NewObjectKey(value string) (ObjectKey, error) {
	if err := requireGoText(value, "object_key"); err != nil { return "", err }
	return ObjectKey(value), nil
}

func NewVersionAlias(value string) (VersionAlias, error) {
	if err := requireGoText(value, "alias"); err != nil { return "", err }
	return VersionAlias(value), nil
}

func NewJobID(value string) (JobID, error) {
	if err := requireGoText(value, "job_id"); err != nil { return "", err }
	return JobID(value), nil
}

func NewMachineID(value string) (MachineID, error) {
	if err := requireGoText(value, "machine_id"); err != nil { return "", err }
	return MachineID(value), nil
}

func NewOperationID(value string) (OperationID, error) {
	if err := requireGoText(value, "operation_id"); err != nil { return "", err }
	return OperationID(value), nil
}

func NewCheckpointID(value string) (CheckpointID, error) {
	if err := requireGoText(value, "checkpoint_id"); err != nil { return "", err }
	return CheckpointID(value), nil
}

func NewIdempotencyKeyBytes(value []byte) (IdempotencyKeyBytes, error) {
	if err := requireGoBytes(value, "idempotency_key_bytes", -1); err != nil { return nil, err }
	return IdempotencyKeyBytes(append([]byte(nil), value...)), nil
}

func NewIdempotencyKeyText(value string) (IdempotencyKeyText, error) {
	if err := requireGoText(value, "idempotency_key_text"); err != nil { return "", err }
	return IdempotencyKeyText(value), nil
}

func NewIdempotencyKey(value any) (IdempotencyKey, error) {
	return IdempotencyKey(value), nil
}

func NewOpaqueText(value string) (OpaqueText, error) {
	if err := requireGoText(value, "opaque_text"); err != nil { return "", err }
	return OpaqueText(value), nil
}

func NewUploadID(value string) (UploadID, error) {
	if err := requireGoText(value, "upload_id"); err != nil { return "", err }
	return UploadID(value), nil
}

func NewVersionSha256(value []byte) (Sha256Digest, error) {
	if err := requireGoBytes(value, "version_sha256", 32); err != nil { return [32]byte{}, err }
	var result Sha256Digest
	copy(result[:], value)
	return result, nil
}

func NewSha256Digest(value []byte) (Sha256Digest, error) {
	if err := requireGoBytes(value, "sha256_digest", 32); err != nil { return [32]byte{}, err }
	var result Sha256Digest
	copy(result[:], value)
	return result, nil
}

func NewRevisionDigest(value []byte) (RevisionDigest, error) {
	if err := requireGoBytes(value, "revision_digest", 32); err != nil { return [32]byte{}, err }
	var result RevisionDigest
	copy(result[:], value)
	return result, nil
}

func NewImage(value any) (Image, error) {
	return Image(value), nil
}

func NewRevision(value uint64) (Revision, error) {
	if err := requireGoUint(value, "revision", 0, 0); err != nil { return 0, err }
	return Revision(value), nil
}

func NewRunID(value []byte) (RunID, error) {
	if err := requireGoBytes(value, "run_id", 16); err != nil { return [16]byte{}, err }
	var result RunID
	copy(result[:], value)
	return result, nil
}

func NewEvaluationID(value []byte) (EvaluationID, error) {
	if err := requireGoBytes(value, "evaluation_id", 16); err != nil { return [16]byte{}, err }
	var result EvaluationID
	copy(result[:], value)
	return result, nil
}

func NewPageLimit(value uint64) (PageLimit, error) {
	if err := requireGoUint(value, "page_limit", 1, 1000); err != nil { return 0, err }
	return PageLimit(value), nil
}

func NewCommitID(value []byte) (CommitID, error) {
	if err := requireGoBytes(value, "commit_id", -1); err != nil { return nil, err }
	return CommitID(append([]byte(nil), value...)), nil
}

func NewOpenEnumValue(value int32) (OpenEnumValue, error) {
	return OpenEnumValue(value), nil
}

func NewWireChoice(value WireChoice) (WireChoice, error) {
	if value == nil { return nil, fmt.Errorf("wire_choice must be present") }
	return value, nil
}



const SourceBinding = "E47ED4BFA56F81A2E3B8EA51C0E67E1AD4909C47F06B30EE11F6D3EDA573F649"
const BestTransport = "grpc+tls"
const SelectionProbe = "none"
const PostFailureFallback = "none"
const Replay = "none"

// Credentials configures the public facade. The zero value uses the platform
// trust store. A client certificate enables mTLS without changing the client
// constructor or generated service APIs.
type Credentials struct {
    BearerToken string
    RootCAs *x509.CertPool
    ClientCertificate *tls.Certificate
    ServerName string
}

type InferenceServices struct {
    Models inferencev1.ModelsServiceClient
    Contexts inferencev1.ContextsServiceClient
    WarmContexts inferencev1.WarmContextsServiceClient
    Runs inferencev1.RunsServiceClient
    Evaluations inferencev1.EvaluationsServiceClient
}

type Client struct {
    conn *grpc.ClientConn
    Actors actorsv1.ActorsServiceClient
    Stream streamv2.StreamServiceClient
    Buckets objectsv2.BucketsServiceClient
    Objects objectsv2.ObjectsServiceClient
    Multipart objectsv2.MultipartServiceClient
    Workers workersv1.WorkersServiceClient
    Filesystem filesystemv2.FilesystemServiceClient
    Harness harnessv2.HarnessServiceClient
    Inference InferenceServices
    Machines machinesv1.MachinesServiceClient
}

func normalizeEndpoint(endpoint string) (string, bool, error) {
    value := strings.TrimSpace(endpoint)
    if value == "" { return "", false, fmt.Errorf("endpoint must not be empty") }
    if !strings.Contains(value, "://") { value = "https://" + value }
    parsed, err := url.Parse(value)
    if err != nil { return "", false, fmt.Errorf("invalid endpoint: %w", err) }
    secure := parsed.Scheme == "https" || parsed.Scheme == "grpcs"
    if !secure && parsed.Scheme != "http" && parsed.Scheme != "grpc" {
        return "", false, fmt.Errorf("unsupported endpoint scheme: %s", parsed.Scheme)
    }
    if parsed.Host == "" || parsed.Path != "" && parsed.Path != "/" {
        return "", false, fmt.Errorf("endpoint must contain only an authority")
    }
    return parsed.Host, secure, nil
}

func validateCredentials(c Credentials, secure bool) error {
    if strings.TrimSpace(c.BearerToken) == "" && c.BearerToken != "" || strings.ContainsAny(c.BearerToken, "\r\n") {
        return fmt.Errorf("invalid bearer credential")
    }
    if c.BearerToken != "" && !secure { return fmt.Errorf("bearer credentials require a secure endpoint") }
    return nil
}

func unaryAuth(token string) grpc.UnaryClientInterceptor {
    return func(ctx context.Context, method string, req, reply any, cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption) error {
        if token != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+token) }
        return invoker(ctx, method, req, reply, cc, opts...)
    }
}

func streamAuth(token string) grpc.StreamClientInterceptor {
    return func(ctx context.Context, desc *grpc.StreamDesc, cc *grpc.ClientConn, method string, streamer grpc.Streamer, opts ...grpc.CallOption) (grpc.ClientStream, error) {
        if token != "" { ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+token) }
        return streamer(ctx, desc, cc, method, opts...)
    }
}

// NewClient selects secure gRPC by default. Use an explicit grpc:// endpoint
// only for a local plaintext server; callers never select build tags or
// platform feature flags.
func NewClient(ctx context.Context, endpoint string, c Credentials) (*Client, error) {
    target, secure, err := normalizeEndpoint(endpoint)
    if err != nil { return nil, err }
    if err := validateCredentials(c, secure); err != nil { return nil, err }
    var transportCredentials credentials.TransportCredentials
    if secure {
        config := &tls.Config{RootCAs: c.RootCAs, Certificates: nil, ServerName: c.ServerName, MinVersion: tls.VersionTLS13}
        if c.ClientCertificate != nil { config.Certificates = []tls.Certificate{*c.ClientCertificate} }
        transportCredentials = credentials.NewTLS(config)
    } else {
        transportCredentials = insecure.NewCredentials()
    }
    conn, err := grpc.DialContext(ctx, target,
        grpc.WithTransportCredentials(transportCredentials),
        grpc.WithUnaryInterceptor(unaryAuth(c.BearerToken)),
        grpc.WithStreamInterceptor(streamAuth(c.BearerToken)),
    )
    if err != nil { return nil, err }
    return &Client{
        conn: conn,
        Actors: actorsv1.NewActorsServiceClient(conn),
        Stream: streamv2.NewStreamServiceClient(conn),
        Buckets: objectsv2.NewBucketsServiceClient(conn),
        Objects: objectsv2.NewObjectsServiceClient(conn),
        Multipart: objectsv2.NewMultipartServiceClient(conn),
        Workers: workersv1.NewWorkersServiceClient(conn),
        Filesystem: filesystemv2.NewFilesystemServiceClient(conn),
        Harness: harnessv2.NewHarnessServiceClient(conn),
        Inference: InferenceServices{
            Models: inferencev1.NewModelsServiceClient(conn),
            Contexts: inferencev1.NewContextsServiceClient(conn),
            WarmContexts: inferencev1.NewWarmContextsServiceClient(conn),
            Runs: inferencev1.NewRunsServiceClient(conn),
            Evaluations: inferencev1.NewEvaluationsServiceClient(conn),
        },
        Machines: machinesv1.NewMachinesServiceClient(conn),
    }, nil
}

func (c *Client) Close() error { return c.conn.Close() }

type OperationPolicy struct {
    ClientStreaming, ServerStreaming, BearerAuth bool
    Cancellation string
    Capabilities, Errors, Validations []string
}
var Operations = map[string]OperationPolicy{
    "acyclic.actors.v1.ActorsService/CreateActor": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"actors.write", "actors.idempotent_mutation"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_CAPABILITY_DENIED", "ERROR_CODE_CAPABILITY_EXPIRED", "ERROR_CODE_ACTOR_NOT_FOUND", "ERROR_CODE_SUBSCRIPTION_NOT_FOUND", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_CONFLICT", "ERROR_CODE_ADMISSION_DENIED", "ERROR_CODE_CHECKPOINT_FAILED", "ERROR_CODE_DEPENDENCY_UNAVAILABLE"}, Validations: []string{"idempotency_key.non_empty_utf8"}},
    "acyclic.actors.v1.ActorsService/UpdateActor": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"actors.write", "actors.idempotent_mutation"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_CAPABILITY_DENIED", "ERROR_CODE_CAPABILITY_EXPIRED", "ERROR_CODE_ACTOR_NOT_FOUND", "ERROR_CODE_SUBSCRIPTION_NOT_FOUND", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_CONFLICT", "ERROR_CODE_ADMISSION_DENIED", "ERROR_CODE_CHECKPOINT_FAILED", "ERROR_CODE_DEPENDENCY_UNAVAILABLE"}, Validations: []string{"actor_id.non_empty_utf8", "expected_configuration_revision.non_negative"}},
    "acyclic.actors.v1.ActorsService/InspectActor": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"actors.read"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_CAPABILITY_DENIED", "ERROR_CODE_CAPABILITY_EXPIRED", "ERROR_CODE_ACTOR_NOT_FOUND", "ERROR_CODE_SUBSCRIPTION_NOT_FOUND", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_CONFLICT", "ERROR_CODE_ADMISSION_DENIED", "ERROR_CODE_CHECKPOINT_FAILED", "ERROR_CODE_DEPENDENCY_UNAVAILABLE"}, Validations: []string{"actor_id.non_empty_utf8"}},
    "acyclic.actors.v1.ActorsService/AddSubscription": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"actors.write", "actors.idempotent_mutation"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_CAPABILITY_DENIED", "ERROR_CODE_CAPABILITY_EXPIRED", "ERROR_CODE_ACTOR_NOT_FOUND", "ERROR_CODE_SUBSCRIPTION_NOT_FOUND", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_CONFLICT", "ERROR_CODE_ADMISSION_DENIED", "ERROR_CODE_CHECKPOINT_FAILED", "ERROR_CODE_DEPENDENCY_UNAVAILABLE"}, Validations: []string{"idempotency_key.non_empty_utf8"}},
    "acyclic.actors.v1.ActorsService/RemoveSubscription": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"actors.write", "actors.idempotent_mutation"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_CAPABILITY_DENIED", "ERROR_CODE_CAPABILITY_EXPIRED", "ERROR_CODE_ACTOR_NOT_FOUND", "ERROR_CODE_SUBSCRIPTION_NOT_FOUND", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_CONFLICT", "ERROR_CODE_ADMISSION_DENIED", "ERROR_CODE_CHECKPOINT_FAILED", "ERROR_CODE_DEPENDENCY_UNAVAILABLE"}, Validations: []string{"idempotency_key.non_empty_utf8"}},
    "acyclic.actors.v1.ActorsService/ResumeSubscription": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"actors.write", "actors.idempotent_mutation"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_CAPABILITY_DENIED", "ERROR_CODE_CAPABILITY_EXPIRED", "ERROR_CODE_ACTOR_NOT_FOUND", "ERROR_CODE_SUBSCRIPTION_NOT_FOUND", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_CONFLICT", "ERROR_CODE_ADMISSION_DENIED", "ERROR_CODE_CHECKPOINT_FAILED", "ERROR_CODE_DEPENDENCY_UNAVAILABLE"}, Validations: []string{"idempotency_key.non_empty_utf8"}},
    "acyclic.actors.v1.ActorsService/CheckpointActor": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"actors.write", "actors.idempotent_mutation"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_CAPABILITY_DENIED", "ERROR_CODE_CAPABILITY_EXPIRED", "ERROR_CODE_ACTOR_NOT_FOUND", "ERROR_CODE_SUBSCRIPTION_NOT_FOUND", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_CONFLICT", "ERROR_CODE_ADMISSION_DENIED", "ERROR_CODE_CHECKPOINT_FAILED", "ERROR_CODE_DEPENDENCY_UNAVAILABLE"}, Validations: []string{"actor_id.non_empty_utf8"}},
    "acyclic.actors.v1.ActorsService/InvokeActor": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"actors.invoke"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_CAPABILITY_DENIED", "ERROR_CODE_CAPABILITY_EXPIRED", "ERROR_CODE_ACTOR_NOT_FOUND", "ERROR_CODE_SUBSCRIPTION_NOT_FOUND", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_CONFLICT", "ERROR_CODE_ADMISSION_DENIED", "ERROR_CODE_CHECKPOINT_FAILED", "ERROR_CODE_DEPENDENCY_UNAVAILABLE"}, Validations: []string{"actor_id.non_empty_utf8", "method.non_empty_utf8"}},
    "acyclic.workers.v1.WorkersService/PublishVersion": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"workers.write", "workers.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "VERSION_NOT_FOUND", "DEPLOYMENT_NOT_FOUND", "JOB_NOT_FOUND", "REVISION_CONFLICT", "TERMINAL_JOB_FAILURE"}, Validations: []string{"javascript_module.non_empty_bytes", "expected_sha256.length_32"}},
    "acyclic.workers.v1.WorkersService/SelectDeployment": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"workers.write", "workers.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "VERSION_NOT_FOUND", "DEPLOYMENT_NOT_FOUND", "JOB_NOT_FOUND", "REVISION_CONFLICT", "TERMINAL_JOB_FAILURE"}, Validations: []string{"alias.non_empty_utf8", "version_sha256.length_32"}},
    "acyclic.workers.v1.WorkersService/SubmitJob": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"workers.write", "workers.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "VERSION_NOT_FOUND", "DEPLOYMENT_NOT_FOUND", "JOB_NOT_FOUND", "REVISION_CONFLICT", "TERMINAL_JOB_FAILURE"}, Validations: []string{"idempotency_key.non_empty_utf8"}},
    "acyclic.workers.v1.WorkersService/InspectJob": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"workers.read"}, Errors: []string{"INVALID_ARGUMENT", "VERSION_NOT_FOUND", "DEPLOYMENT_NOT_FOUND", "JOB_NOT_FOUND", "REVISION_CONFLICT", "TERMINAL_JOB_FAILURE"}, Validations: []string{"job_id.non_empty_utf8"}},
    "acyclic.workers.v1.WorkersService/CancelJob": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"workers.write", "workers.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "VERSION_NOT_FOUND", "DEPLOYMENT_NOT_FOUND", "JOB_NOT_FOUND", "REVISION_CONFLICT", "TERMINAL_JOB_FAILURE"}, Validations: []string{"job_id.non_empty_utf8"}},
    "acyclic.workers.v1.WorkersService/InvokeVersion": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"workers.invoke"}, Errors: []string{"INVALID_ARGUMENT", "VERSION_NOT_FOUND", "DEPLOYMENT_NOT_FOUND", "JOB_NOT_FOUND", "REVISION_CONFLICT", "TERMINAL_JOB_FAILURE"}, Validations: []string{"version_sha256.length_32", "method.non_empty_utf8"}},
    "acyclic.workers.v1.WorkersService/InvokeDeployment": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"workers.invoke"}, Errors: []string{"INVALID_ARGUMENT", "VERSION_NOT_FOUND", "DEPLOYMENT_NOT_FOUND", "JOB_NOT_FOUND", "REVISION_CONFLICT", "TERMINAL_JOB_FAILURE"}, Validations: []string{"alias.non_empty_utf8", "method.non_empty_utf8"}},
    "acyclic.objects.v2.BucketsService/CreateBucket": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"objects.bucket.write", "objects.idempotent_mutation"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"bucket.name.non_empty", "idempotency_key.non_empty"}},
    "acyclic.objects.v2.BucketsService/HeadBucket": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"objects.bucket.read"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"bucket.name.non_empty"}},
    "acyclic.objects.v2.BucketsService/DeleteBucket": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"objects.bucket.write", "objects.idempotent_mutation"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"bucket.name.non_empty", "bucket.empty", "idempotency_key.non_empty"}},
    "acyclic.objects.v2.ObjectsService/PutObject": {ClientStreaming: true, ServerStreaming: false, BearerAuth: true, Cancellation: "call", Capabilities: []string{"objects.object.write", "objects.idempotent_mutation"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"bucket.name.non_empty", "object.key.non_empty", "preconditions.atomic", "idempotency_key.non_empty", "upload.completion_frame"}},
    "acyclic.objects.v2.ObjectsService/GetObject": {ClientStreaming: false, ServerStreaming: true, BearerAuth: true, Cancellation: "call", Capabilities: []string{"objects.object.read"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"bucket.name.non_empty", "object.key.non_empty", "range.valid", "response.bounded"}},
    "acyclic.objects.v2.ObjectsService/HeadObject": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"objects.object.read"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"bucket.name.non_empty", "object.key.non_empty"}},
    "acyclic.objects.v2.ObjectsService/DeleteObject": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"objects.object.write", "objects.idempotent_mutation"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"bucket.name.non_empty", "object.key.non_empty", "preconditions.atomic", "idempotency_key.non_empty"}},
    "acyclic.objects.v2.ObjectsService/ListObjects": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"objects.object.read"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"bucket.name.non_empty", "pagination.bounded"}},
    "acyclic.objects.v2.MultipartService/CreateMultipart": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"objects.multipart.write", "objects.idempotent_mutation"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"bucket.name.non_empty", "object.key.non_empty", "idempotency_key.non_empty"}},
    "acyclic.objects.v2.MultipartService/UploadPart": {ClientStreaming: true, ServerStreaming: false, BearerAuth: true, Cancellation: "call", Capabilities: []string{"objects.multipart.write", "objects.idempotent_mutation"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"upload_id.non_empty", "part_number.positive", "upload.completion_frame"}},
    "acyclic.objects.v2.MultipartService/ListParts": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"objects.multipart.read"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"upload_id.non_empty", "pagination.bounded"}},
    "acyclic.objects.v2.MultipartService/CompleteMultipart": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"objects.multipart.write", "objects.idempotent_mutation"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"upload_id.non_empty", "parts.ordered_exact", "idempotency_key.non_empty"}},
    "acyclic.objects.v2.MultipartService/AbortMultipart": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"objects.multipart.write", "objects.idempotent_mutation"}, Errors: []string{"ERROR_CODE_INVALID_ARGUMENT", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_ALREADY_EXISTS", "ERROR_CODE_PRECONDITION_FAILED", "ERROR_CODE_IDEMPOTENCY_MISMATCH", "ERROR_CODE_QUOTA_EXCEEDED", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_UNAVAILABLE", "ERROR_CODE_ACCESS_DENIED", "ERROR_CODE_RANGE_NOT_SATISFIABLE", "ERROR_CODE_NOT_MODIFIED"}, Validations: []string{"upload_id.non_empty", "idempotency_key.non_empty"}},
    "acyclic.stream.v2.StreamService/InspectIdempotency": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"stream.read"}, Errors: []string{"INVALID_ARGUMENT", "TAIL_CONFLICT", "COMMIT_CONFLICT", "IDEMPOTENCY_MISMATCH"}, Validations: []string{"idempotency_key.non_empty_bytes"}},
    "acyclic.stream.v2.StreamService/Append": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"stream.write"}, Errors: []string{"INVALID_ARGUMENT", "TAIL_CONFLICT", "COMMIT_CONFLICT", "IDEMPOTENCY_MISMATCH"}, Validations: []string{"path.non_empty_utf8", "records.max_bytes"}},
    "acyclic.stream.v2.StreamService/Tail": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"stream.read"}, Errors: []string{"INVALID_ARGUMENT", "TAIL_CONFLICT", "COMMIT_CONFLICT", "IDEMPOTENCY_MISMATCH"}, Validations: []string{"path.non_empty_utf8"}},
    "acyclic.stream.v2.StreamService/Fork": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"stream.write"}, Errors: []string{"INVALID_ARGUMENT", "TAIL_CONFLICT", "COMMIT_CONFLICT", "IDEMPOTENCY_MISMATCH"}, Validations: []string{"source.non_empty_utf8", "destination.non_empty_utf8"}},
    "acyclic.stream.v2.StreamService/Read": {ClientStreaming: false, ServerStreaming: true, BearerAuth: true, Cancellation: "call", Capabilities: []string{"stream.read"}, Errors: []string{"INVALID_ARGUMENT", "TAIL_CONFLICT", "COMMIT_CONFLICT", "IDEMPOTENCY_MISMATCH"}, Validations: []string{"path.non_empty_utf8", "limit.max_stream_items"}},
    "acyclic.stream.v2.StreamService/Follow": {ClientStreaming: false, ServerStreaming: true, BearerAuth: true, Cancellation: "call", Capabilities: []string{"stream.read"}, Errors: []string{"INVALID_ARGUMENT", "TAIL_CONFLICT", "COMMIT_CONFLICT", "IDEMPOTENCY_MISMATCH"}, Validations: []string{"path.non_empty_utf8"}},
    "acyclic.stream.v2.StreamService/Children": {ClientStreaming: false, ServerStreaming: true, BearerAuth: true, Cancellation: "call", Capabilities: []string{"stream.read"}, Errors: []string{"INVALID_ARGUMENT", "TAIL_CONFLICT", "COMMIT_CONFLICT", "IDEMPOTENCY_MISMATCH"}, Validations: []string{"limit.max_stream_items"}},
    "acyclic.stream.v2.StreamService/ChildrenPage": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"stream.read"}, Errors: []string{"INVALID_ARGUMENT", "TAIL_CONFLICT", "COMMIT_CONFLICT", "IDEMPOTENCY_MISMATCH"}, Validations: []string{"limit.max_stream_items"}},
    "acyclic.stream.v2.StreamService/Commit": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"stream.write"}, Errors: []string{"INVALID_ARGUMENT", "TAIL_CONFLICT", "COMMIT_CONFLICT", "IDEMPOTENCY_MISMATCH"}, Validations: []string{"mutations.max_command_bytes"}},
    "acyclic.stream.v2.StreamService/ReadCommit": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"stream.read"}, Errors: []string{"INVALID_ARGUMENT", "TAIL_CONFLICT", "COMMIT_CONFLICT", "IDEMPOTENCY_MISMATCH"}, Validations: []string{"commit_id.non_empty_bytes"}},
    "inference.customer.v1.ModelsService/List": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"inference.models.read"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"model_capabilities.bounded", "retention_profiles.valid"}},
    "inference.customer.v1.ContextsService/Create": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"inference.context.write", "inference.idempotent_mutation"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"request_identity.nonzero", "model.non_empty", "items.bounded", "message.bounded"}},
    "inference.customer.v1.ContextsService/Inspect": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"inference.context.read"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"revision.length_32"}},
    "inference.customer.v1.ContextsService/Mutate": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"inference.context.write", "inference.idempotent_mutation"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"request_identity.nonzero", "source.present", "action.present", "message.bounded"}},
    "inference.customer.v1.WarmContextsService/Retain": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"inference.warm.write", "inference.idempotent_mutation"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"request_identity.nonzero", "context.length_32", "policy.valid"}},
    "inference.customer.v1.WarmContextsService/Inspect": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"inference.warm.read"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"commitment.length_32"}},
    "inference.customer.v1.WarmContextsService/Renew": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"inference.warm.write", "inference.idempotent_mutation"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"request_identity.nonzero", "commitment.length_32", "policy.valid"}},
    "inference.customer.v1.WarmContextsService/Release": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"inference.warm.write", "inference.idempotent_mutation"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"request_identity.nonzero", "commitment.length_32"}},
    "inference.customer.v1.RunsService/Generate": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"inference.runs.write", "inference.idempotent_mutation"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"request_identity.nonzero", "context.length_32", "maximum_output.positive", "message.bounded"}},
    "inference.customer.v1.RunsService/Inspect": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"inference.runs.read"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"run_id.length_16"}},
    "inference.customer.v1.RunsService/Watch": {ClientStreaming: false, ServerStreaming: true, BearerAuth: true, Cancellation: "call", Capabilities: []string{"inference.runs.read"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"run_id.length_16", "cursor.monotonic", "terminal.required"}},
    "inference.customer.v1.RunsService/Cancel": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "operation", Capabilities: []string{"inference.runs.write", "inference.idempotent_mutation"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"run_id.length_16"}},
    "inference.customer.v1.EvaluationsService/Create": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"inference.evaluations.write", "inference.idempotent_mutation"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"request_identity.nonzero", "candidates.bounded", "cases.bounded", "metrics.bounded", "spec_digest.length_32", "message.bounded"}},
    "inference.customer.v1.EvaluationsService/Inspect": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"inference.evaluations.read"}, Errors: []string{"inference.invalid", "inference.transport", "inference.observation"}, Validations: []string{"evaluation_id.length_16"}},
    "acyclic.machines.v1.MachinesService/QualifyImage": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.qualify"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"image.immutable_digest", "capabilities.proven"}},
    "acyclic.machines.v1.MachinesService/Create": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.write", "machines.idempotent_mutation"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"idempotency_key.nonzero", "contract.valid", "limits.valid"}},
    "acyclic.machines.v1.MachinesService/Checkpoint": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.write", "machines.idempotent_mutation"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"machine_id.nonzero", "idempotency_key.nonzero"}},
    "acyclic.machines.v1.MachinesService/Fork": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.fork", "machines.idempotent_mutation"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"checkpoint_id.nonzero", "count.bounded", "idempotency_key.nonzero"}},
    "acyclic.machines.v1.MachinesService/ForkMachine": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.fork", "machines.idempotent_mutation"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"machine_id.nonzero", "fidelity.declared", "count.bounded"}},
    "acyclic.machines.v1.MachinesService/Suspend": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.write", "machines.idempotent_mutation"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"machine_id.nonzero", "idempotency_key.nonzero"}},
    "acyclic.machines.v1.MachinesService/Wake": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.write", "machines.idempotent_mutation"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"machine_id.nonzero", "idempotency_key.nonzero"}},
    "acyclic.machines.v1.MachinesService/SetSuspensionPolicy": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.write", "machines.idempotent_mutation"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"machine_id.nonzero", "policy.valid", "idempotency_key.nonzero"}},
    "acyclic.machines.v1.MachinesService/DestroyMachine": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.write", "machines.idempotent_mutation"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"machine_id.nonzero", "idempotency_key.nonzero"}},
    "acyclic.machines.v1.MachinesService/DestroyCheckpoint": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.write", "machines.idempotent_mutation"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"checkpoint_id.nonzero", "idempotency_key.nonzero"}},
    "acyclic.machines.v1.MachinesService/Recover": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.operations"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"idempotency_key.nonzero"}},
    "acyclic.machines.v1.MachinesService/InspectMachine": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.read"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"machine_id.nonzero"}},
    "acyclic.machines.v1.MachinesService/InspectCheckpoint": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.read"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"checkpoint_id.nonzero"}},
    "acyclic.machines.v1.MachinesService/ListMachines": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.read"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"page_limit.bounded", "cursor.valid"}},
    "acyclic.machines.v1.MachinesService/Events": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.read"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"machine_id.nonzero", "page_limit.bounded", "cursor.valid"}},
    "acyclic.machines.v1.MachinesService/Usage": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.read"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"machine_id.nonzero", "time_range.valid"}},
    "acyclic.machines.v1.MachinesService/Cancel": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "operation", Capabilities: []string{"machines.operations"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"operation_id.nonzero"}},
    "acyclic.machines.v1.MachinesService/InspectOperation": {ClientStreaming: false, ServerStreaming: false, BearerAuth: false, Cancellation: "none", Capabilities: []string{"machines.operations"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"operation_id.nonzero"}},
    "acyclic.machines.v1.MachinesService/WatchOperation": {ClientStreaming: false, ServerStreaming: true, BearerAuth: false, Cancellation: "call", Capabilities: []string{"machines.operations"}, Errors: []string{"invalid", "not_found", "conflict", "unsupported", "rejected", "unavailable", "operation_indeterminate", "operation_observation_indeterminate", "operation_failed", "operation_cancelled"}, Validations: []string{"operation_id.nonzero", "cursor.monotonic", "terminal.required"}},
    "acyclic.filesystem.v2.FilesystemService/Handshake": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"protocol.version.exact", "descriptor_digest.matches", "request.bounded"}},
    "acyclic.filesystem.v2.FilesystemService/CreateWorkspace": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.write", "filesystem.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"operation.idempotency_key.16_bytes", "workspace_name.valid", "profile.supported"}},
    "acyclic.filesystem.v2.FilesystemService/OpenWorkspace": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.read"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"workspace.selector.required", "workspace.identity.matches"}},
    "acyclic.filesystem.v2.FilesystemService/DeleteWorkspace": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.write", "filesystem.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"workspace.reference.required", "operation.idempotency_key.16_bytes"}},
    "acyclic.filesystem.v2.FilesystemService/GetHead": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.read"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"workspace.reference.required", "workspace.identity.matches"}},
    "acyclic.filesystem.v2.FilesystemService/GetGeneration": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.read"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.reference.required", "generation_id.32_bytes"}},
    "acyclic.filesystem.v2.FilesystemService/Read": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.read"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.reference.required", "path.valid", "maximum_bytes.bounded", "range.bounded"}},
    "acyclic.filesystem.v2.FilesystemService/Stat": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.read"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.reference.required", "path.valid"}},
    "acyclic.filesystem.v2.FilesystemService/ListDirectory": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.read"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.reference.required", "page.maximum_items.bounded", "cursor.valid"}},
    "acyclic.filesystem.v2.FilesystemService/ReadLink": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.read"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.reference.required", "path.valid", "maximum_bytes.bounded"}},
    "acyclic.filesystem.v2.FilesystemService/PlanExtents": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.read"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.reference.required", "path.valid", "range.valid"}},
    "acyclic.filesystem.v2.FilesystemService/ApplyTransaction": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.write", "filesystem.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.reference.required", "operation.idempotency_key.16_bytes", "mutation.oneof", "transaction.bounded"}},
    "acyclic.filesystem.v2.FilesystemService/RebaseTransaction": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.write", "filesystem.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.reference.required", "operation.idempotency_key.16_bytes", "transaction.bounded"}},
    "acyclic.filesystem.v2.FilesystemService/ForkWorkspace": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.write", "filesystem.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"workspace.reference.required", "generation.reference.required", "operation.idempotency_key.16_bytes"}},
    "acyclic.filesystem.v2.FilesystemService/Diff": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.read"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.references.required", "diff.bounds.bounded"}},
    "acyclic.filesystem.v2.FilesystemService/Rebase": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.write", "filesystem.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"workspace.reference.required", "generation.reference.required", "rebase.bounds.bounded"}},
    "acyclic.filesystem.v2.FilesystemService/PlanJoin": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.read"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.references.required", "join.history.valid", "join.bounds.bounded"}},
    "acyclic.filesystem.v2.FilesystemService/ApplyJoin": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.write", "filesystem.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"join.plan_identity.matches", "operation.idempotency_key.16_bytes"}},
    "acyclic.filesystem.v2.FilesystemService/Checkpoint": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.write", "filesystem.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.reference.required", "operation.idempotency_key.16_bytes"}},
    "acyclic.filesystem.v2.FilesystemService/Pin": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.write", "filesystem.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.reference.required", "operation.idempotency_key.16_bytes"}},
    "acyclic.filesystem.v2.FilesystemService/Export": {ClientStreaming: false, ServerStreaming: true, BearerAuth: true, Cancellation: "call", Capabilities: []string{"filesystem.read"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"generation.reference.required", "export.bounds.bounded", "cursor.valid"}},
    "acyclic.filesystem.v2.FilesystemService/Import": {ClientStreaming: true, ServerStreaming: false, BearerAuth: true, Cancellation: "call", Capabilities: []string{"filesystem.write", "filesystem.idempotent_mutation"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"import.stream.nonempty", "object.order.exact", "cursor.valid", "operation.idempotency_key.16_bytes"}},
    "acyclic.filesystem.v2.FilesystemService/IssueMountCredential": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.credentials.mount"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"workspace.reference.required", "generation.reference.required", "credential.expiry.bounded", "operation.idempotency_key.16_bytes"}},
    "acyclic.filesystem.v2.FilesystemService/IssueS3Credential": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.credentials.s3"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"workspace.reference.required", "generation.reference.required", "credential.expiry.bounded", "operation.idempotency_key.16_bytes"}},
    "acyclic.filesystem.v2.FilesystemService/GetSourceState": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.source"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"workspace.reference.required"}},
    "acyclic.filesystem.v2.FilesystemService/ReconcileSource": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.source"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"workspace.reference.required", "operation.idempotency_key.16_bytes"}},
    "acyclic.filesystem.v2.FilesystemService/RescanSource": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.source"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"workspace.reference.required", "operation.idempotency_key.16_bytes"}},
    "acyclic.filesystem.v2.FilesystemService/SealSource": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.source"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"workspace.reference.required", "operation.idempotency_key.16_bytes"}},
    "acyclic.filesystem.v2.FilesystemService/Observe": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"filesystem.operation"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"operation_id.16_bytes", "response.identity.matches"}},
    "acyclic.filesystem.v2.FilesystemService/Cancel": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "operation", Capabilities: []string{"filesystem.operation"}, Errors: []string{"INVALID_ARGUMENT", "NOT_FOUND", "FAILED_PRECONDITION", "CANCELLED", "RESOURCE_EXHAUSTED", "UNAVAILABLE", "UNIMPLEMENTED", "DATA_LOSS"}, Validations: []string{"operation_id.16_bytes", "operation.idempotency_key.16_bytes", "response.identity.matches"}},
    "acyclic.harness.v2.HarnessService/Handshake": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"harness"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_CONFLICT", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_INVALID", "ERROR_CODE_UNAUTHORIZED", "ERROR_CODE_STORAGE", "ERROR_CODE_INDETERMINATE", "ERROR_CODE_INTERACTION_DECLINED", "ERROR_CODE_INTERACTION_CANCELLED", "ERROR_CODE_INTERACTION_EXPIRED", "ERROR_CODE_INTERACTION_DENIED"}, Validations: []string{"protocol.identity.exact", "required_capability.nonempty", "required_capability.supported"}},
    "acyclic.harness.v2.HarnessService/Submit": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"operation:declare"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_CONFLICT", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_INVALID", "ERROR_CODE_UNAUTHORIZED", "ERROR_CODE_STORAGE", "ERROR_CODE_INDETERMINATE", "ERROR_CODE_INTERACTION_DECLINED", "ERROR_CODE_INTERACTION_CANCELLED", "ERROR_CODE_INTERACTION_EXPIRED", "ERROR_CODE_INTERACTION_DENIED"}, Validations: []string{"protocol.identity.exact", "operation_id.nonempty", "idempotency_key.nonempty", "admission.identity.matches"}},
    "acyclic.harness.v2.HarnessService/Replay": {ClientStreaming: false, ServerStreaming: true, BearerAuth: true, Cancellation: "call", Capabilities: []string{"harness.replay"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_CONFLICT", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_INVALID", "ERROR_CODE_UNAUTHORIZED", "ERROR_CODE_STORAGE", "ERROR_CODE_INDETERMINATE", "ERROR_CODE_INTERACTION_DECLINED", "ERROR_CODE_INTERACTION_CANCELLED", "ERROR_CODE_INTERACTION_EXPIRED", "ERROR_CODE_INTERACTION_DENIED"}, Validations: []string{"protocol.identity.exact", "resume_cursor.contiguous", "delivery.identity.preserving"}},
    "acyclic.harness.v2.HarnessService/Observe": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "none", Capabilities: []string{"operation:observe"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_CONFLICT", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_INVALID", "ERROR_CODE_UNAUTHORIZED", "ERROR_CODE_STORAGE", "ERROR_CODE_INDETERMINATE", "ERROR_CODE_INTERACTION_DECLINED", "ERROR_CODE_INTERACTION_CANCELLED", "ERROR_CODE_INTERACTION_EXPIRED", "ERROR_CODE_INTERACTION_DENIED"}, Validations: []string{"protocol.identity.exact", "owner.required", "operation_id.nonempty", "scope.required", "scope.capability.operation_observe", "status.identity.matches"}},
    "acyclic.harness.v2.HarnessService/Cancel": {ClientStreaming: false, ServerStreaming: false, BearerAuth: true, Cancellation: "operation", Capabilities: []string{"operation:cancel"}, Errors: []string{"ERROR_CODE_UNSPECIFIED", "ERROR_CODE_NOT_FOUND", "ERROR_CODE_CONFLICT", "ERROR_CODE_UNSUPPORTED", "ERROR_CODE_INVALID", "ERROR_CODE_UNAUTHORIZED", "ERROR_CODE_STORAGE", "ERROR_CODE_INDETERMINATE", "ERROR_CODE_INTERACTION_DECLINED", "ERROR_CODE_INTERACTION_CANCELLED", "ERROR_CODE_INTERACTION_EXPIRED", "ERROR_CODE_INTERACTION_DENIED"}, Validations: []string{"protocol.identity.exact", "owner.required", "operation_id.nonempty", "idempotency_key.nonempty", "scope.required", "scope.capability.operation_cancel", "status.identity.matches"}},

}

var Transports = map[string][]string{
    "actors": []string{"grpc", "http_json"},
    "workers": []string{"grpc", "http_json"},
    "objects": []string{"grpc", "http_json"},
    "stream": []string{"grpc", "http_json"},
    "inference": []string{"grpc", "http_json"},
    "machines": []string{"grpc"},
    "filesystem": []string{"grpc"},
    "harness": []string{"grpc"},

}

var TransportsByRuntime = map[string]map[string][]string{
    "native": Transports,
    "browser": {
        "actors": []string{"http_json"},
        "workers": []string{"http_json"},
        "objects": []string{"http_json"},
        "stream": []string{"http_json"},
        "inference": []string{"http_json"},
        "machines": []string{},
        "filesystem": []string{"grpc_web"},
        "harness": []string{},

    },
}
