<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: objects/v2/objects.proto

namespace Acyclic\Objects\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A byte range or suffix selection for an object read.
 *
 * Generated from protobuf message <code>acyclic.objects.v2.ByteRange</code>
 */
class ByteRange extends \Google\Protobuf\Internal\Message
{
    protected $selection;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Objects\V2\InclusiveRange $bytes
     *           An inclusive byte range selection.
     *     @type int|string $suffix_length
     *           The number of bytes selected from the end.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Objects\V2\Objects::initOnce();
        parent::__construct($data);
    }

    /**
     * An inclusive byte range selection.
     *
     * Generated from protobuf field <code>.acyclic.objects.v2.InclusiveRange bytes = 1;</code>
     * @return \Acyclic\Objects\V2\InclusiveRange|null
     */
    public function getBytes()
    {
        return $this->readOneof(1);
    }

    public function hasBytes()
    {
        return $this->hasOneof(1);
    }

    /**
     * An inclusive byte range selection.
     *
     * Generated from protobuf field <code>.acyclic.objects.v2.InclusiveRange bytes = 1;</code>
     * @param \Acyclic\Objects\V2\InclusiveRange $var
     * @return $this
     */
    public function setBytes(\Acyclic\Objects\V2\InclusiveRange|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * The number of bytes selected from the end.
     *
     * Generated from protobuf field <code>uint64 suffix_length = 2;</code>
     * @return int|string
     */
    public function getSuffixLength()
    {
        return $this->readOneof(2);
    }

    public function hasSuffixLength()
    {
        return $this->hasOneof(2);
    }

    /**
     * The number of bytes selected from the end.
     *
     * Generated from protobuf field <code>uint64 suffix_length = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSuffixLength(int|string $var)
    {
        $var = \Acyclic\Runtime\UInt64::validateGeneratedScalar($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getSelection()
    {
        return $this->whichOneof("selection");
    }

}

