<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: objects/v2/objects.proto

namespace Acyclic\Objects\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * One page of uploaded multipart parts.
 *
 * Generated from protobuf message <code>acyclic.objects.v2.ListPartsResponse</code>
 */
class ListPartsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Exact ordered multipart part receipts.
     *
     * Generated from protobuf field <code>repeated .acyclic.objects.v2.UploadedPart parts = 1;</code>
     */
    private $parts;
    /**
     * The next part number after this page.
     *
     * Generated from protobuf field <code>uint32 next_part_number = 2;</code>
     */
    protected $next_part_number = 0;
    /**
     * Whether more entries remain after this page.
     *
     * Generated from protobuf field <code>bool is_truncated = 3;</code>
     */
    protected $is_truncated = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Acyclic\Objects\V2\UploadedPart[] $parts
     *           Exact ordered multipart part receipts.
     *     @type int $next_part_number
     *           The next part number after this page.
     *     @type bool $is_truncated
     *           Whether more entries remain after this page.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Objects\V2\Objects::initOnce();
        parent::__construct($data);
    }

    /**
     * Exact ordered multipart part receipts.
     *
     * Generated from protobuf field <code>repeated .acyclic.objects.v2.UploadedPart parts = 1;</code>
     * @return RepeatedField<\Acyclic\Objects\V2\UploadedPart>
     */
    public function getParts()
    {
        return $this->parts;
    }

    /**
     * Exact ordered multipart part receipts.
     *
     * Generated from protobuf field <code>repeated .acyclic.objects.v2.UploadedPart parts = 1;</code>
     * @param \Acyclic\Objects\V2\UploadedPart[] $var
     * @return $this
     */
    public function setParts(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Acyclic\Objects\V2\UploadedPart::class);
        $this->parts = $arr;

        return $this;
    }

    /**
     * The next part number after this page.
     *
     * Generated from protobuf field <code>uint32 next_part_number = 2;</code>
     * @return int
     */
    public function getNextPartNumber()
    {
        return $this->next_part_number;
    }

    /**
     * The next part number after this page.
     *
     * Generated from protobuf field <code>uint32 next_part_number = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNextPartNumber(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->next_part_number = $var;

        return $this;
    }

    /**
     * Whether more entries remain after this page.
     *
     * Generated from protobuf field <code>bool is_truncated = 3;</code>
     * @return bool
     */
    public function getIsTruncated()
    {
        return $this->is_truncated;
    }

    /**
     * Whether more entries remain after this page.
     *
     * Generated from protobuf field <code>bool is_truncated = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTruncated(bool $var)
    {
        $this->is_truncated = $var;

        return $this;
    }

}

