cmake_minimum_required(VERSION 3.24)
foreach(SOURCE_ROOT GRPC_SOURCE ABSL_ROOT_DIR PROTOBUF_ROOT_DIR BORINGSSL_ROOT_DIR CARES_ROOT_DIR RE2_ROOT_DIR ZLIB_ROOT_DIR)
  if(NOT IS_DIRECTORY "${${SOURCE_ROOT}}")
    message(FATAL_ERROR "Pass an admitted ${SOURCE_ROOT} directory")
  endif()
endforeach()
foreach(OUTPUT_ROOT RUNTIME_BUILD RUNTIME_INSTALL)
  if(NOT DEFINED ${OUTPUT_ROOT} OR "${${OUTPUT_ROOT}}" STREQUAL "")
    message(FATAL_ERROR "Pass an owned ${OUTPUT_ROOT} directory")
  endif()
endforeach()
# Configure unchanged upstream sources with only pre-admitted dependencies.
set(OPTIONS
  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17
  -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL -DBUILD_SHARED_LIBS=OFF
  -Dprotobuf_MSVC_STATIC_RUNTIME=OFF -DABSL_MSVC_STATIC_RUNTIME=OFF
  -DgRPC_MSVC_STATIC_RUNTIME=OFF -DCARES_MSVC_STATIC_RUNTIME=OFF
  -Dprotobuf_BUILD_TESTS=OFF -DgRPC_BUILD_TESTS=OFF
  -DgRPC_DOWNLOAD_ARCHIVES=OFF -DgRPC_INSTALL=ON
  "-DCMAKE_INSTALL_PREFIX=${RUNTIME_INSTALL}")
foreach(SOURCE_ROOT ABSL_ROOT_DIR PROTOBUF_ROOT_DIR BORINGSSL_ROOT_DIR CARES_ROOT_DIR RE2_ROOT_DIR ZLIB_ROOT_DIR)
  list(APPEND OPTIONS "-D${SOURCE_ROOT}=${${SOURCE_ROOT}}")
endforeach()
file(STRINGS "${GRPC_SOURCE}/CMakeLists.txt" PLUGIN_OPTIONS
  REGEX "^option\\(gRPC_BUILD_GRPC_[A-Z_]+_PLUGIN ")
foreach(OPTION_LINE IN LISTS PLUGIN_OPTIONS)
  string(REGEX MATCH "gRPC_BUILD_GRPC_[A-Z_]+_PLUGIN" PLUGIN_OPTION "${OPTION_LINE}")
  if(NOT PLUGIN_OPTION STREQUAL "gRPC_BUILD_GRPC_CPP_PLUGIN")
    list(APPEND OPTIONS "-D${PLUGIN_OPTION}=OFF")
  endif()
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${GRPC_SOURCE}" -B "${RUNTIME_BUILD}" -G Ninja ${OPTIONS}
  COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${RUNTIME_BUILD}" --parallel 1
  COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${RUNTIME_BUILD}"
  COMMAND_ERROR_IS_FATAL ANY)
