[package]
name = "acyclic-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
acyclic-contracts = { version = "0.1.0-rc.1", path = "../contracts" }
acyclic-harness = { version = "0.1.0-rc.1", path = "../harness" }
tokio.workspace = true

[lints]
workspace = true
