{-# LANGUAGE DeriveGeneric #-}
module Acyclic.Semantics
  ( WireChoice(..)
  , ActorId, mkActorId, actorIdValue
  , MethodName, mkMethodName, methodNameValue
  , ResourcePath, mkResourcePath, resourcePathValue
  , SourceName, mkSourceName, sourceNameValue
  , DestinationName, mkDestinationName, destinationNameValue
  , BucketName, mkBucketName, bucketNameValue
  , ObjectKey, mkObjectKey, objectKeyValue
  , VersionAlias, mkVersionAlias, versionAliasValue
  , JobId, mkJobId, jobIdValue
  , MachineId, mkMachineId, machineIdValue
  , OperationId, mkOperationId, operationIdValue
  , WorkspaceId, mkWorkspaceId, workspaceIdValue
  , CheckpointId, mkCheckpointId, checkpointIdValue
  , IdempotencyKeyBytes, mkIdempotencyKeyBytes, idempotencyKeyBytesValue
  , IdempotencyKeyText, mkIdempotencyKeyText, idempotencyKeyTextValue
  , IdempotencyKey, mkIdempotencyKey, idempotencyKeyValue
  , OpaqueText, mkOpaqueText, opaqueTextValue
  , UploadId, mkUploadId, uploadIdValue
  , Sha256Digest, mkSha256Digest, sha256DigestValue
  , RevisionDigest, mkRevisionDigest, revisionDigestValue
  , Image, mkImage, imageValue
  , Revision, mkRevision, revisionValue
  , RunId, mkRunId, runIdValue
  , EvaluationId, mkEvaluationId, evaluationIdValue
  , PageLimit, mkPageLimit, pageLimitValue
  , StreamPageLimit, mkStreamPageLimit, streamPageLimitValue
  , MachinePageLimit, mkMachinePageLimit, machinePageLimitValue
  , MachineEventPageLimit, mkMachineEventPageLimit, machineEventPageLimitValue
  , CommitId, mkCommitId, commitIdValue
  , OpenEnumValue, mkOpenEnumValue, openEnumValueValue
  , OpaqueBytes, mkOpaqueBytes, opaqueBytesValue
  , SequenceNumber, mkSequenceNumber, sequenceNumberValue
  , NonNegativeCount, mkNonNegativeCount, nonNegativeCountValue
  , PositiveCount, mkPositiveCount, positiveCountValue
  , UnixTimestampMillis, mkUnixTimestampMillis, unixTimestampMillisValue
  ) where

-- Generated by the Rust semantic type policy; do not edit.
import qualified Data.ByteString as BS

data WireChoice payload
  = KnownOneof payload
  | UnknownOneof BS.ByteString
  deriving (Eq, Ord, Show)

newtype ActorId = ActorId { unActorId :: String } deriving (Eq, Ord, Show)
mkActorId :: String -> Either String ActorId
mkActorId value | null value = Left "ActorId failed Rust validation" | otherwise = Right (ActorId value)
actorIdValue :: ActorId -> String
actorIdValue = unActorId

newtype MethodName = MethodName { unMethodName :: String } deriving (Eq, Ord, Show)
mkMethodName :: String -> Either String MethodName
mkMethodName value | null value = Left "MethodName failed Rust validation" | otherwise = Right (MethodName value)
methodNameValue :: MethodName -> String
methodNameValue = unMethodName

newtype ResourcePath = ResourcePath { unResourcePath :: String } deriving (Eq, Ord, Show)
mkResourcePath :: String -> Either String ResourcePath
mkResourcePath value | null value = Left "ResourcePath failed Rust validation" | otherwise = Right (ResourcePath value)
resourcePathValue :: ResourcePath -> String
resourcePathValue = unResourcePath

newtype SourceName = SourceName { unSourceName :: String } deriving (Eq, Ord, Show)
mkSourceName :: String -> Either String SourceName
mkSourceName value | null value = Left "SourceName failed Rust validation" | otherwise = Right (SourceName value)
sourceNameValue :: SourceName -> String
sourceNameValue = unSourceName

newtype DestinationName = DestinationName { unDestinationName :: String } deriving (Eq, Ord, Show)
mkDestinationName :: String -> Either String DestinationName
mkDestinationName value | null value = Left "DestinationName failed Rust validation" | otherwise = Right (DestinationName value)
destinationNameValue :: DestinationName -> String
destinationNameValue = unDestinationName

newtype BucketName = BucketName { unBucketName :: String } deriving (Eq, Ord, Show)
mkBucketName :: String -> Either String BucketName
mkBucketName value | null value = Left "BucketName failed Rust validation" | otherwise = Right (BucketName value)
bucketNameValue :: BucketName -> String
bucketNameValue = unBucketName

newtype ObjectKey = ObjectKey { unObjectKey :: String } deriving (Eq, Ord, Show)
mkObjectKey :: String -> Either String ObjectKey
mkObjectKey value | null value = Left "ObjectKey failed Rust validation" | otherwise = Right (ObjectKey value)
objectKeyValue :: ObjectKey -> String
objectKeyValue = unObjectKey

newtype VersionAlias = VersionAlias { unVersionAlias :: String } deriving (Eq, Ord, Show)
mkVersionAlias :: String -> Either String VersionAlias
mkVersionAlias value | null value = Left "VersionAlias failed Rust validation" | otherwise = Right (VersionAlias value)
versionAliasValue :: VersionAlias -> String
versionAliasValue = unVersionAlias

newtype JobId = JobId { unJobId :: String } deriving (Eq, Ord, Show)
mkJobId :: String -> Either String JobId
mkJobId value | null value = Left "JobId failed Rust validation" | otherwise = Right (JobId value)
jobIdValue :: JobId -> String
jobIdValue = unJobId

newtype MachineId = MachineId { unMachineId :: BS.ByteString } deriving (Eq, Ord, Show)
mkMachineId :: BS.ByteString -> Either String MachineId
mkMachineId value | BS.null value || BS.length value /= 16 = Left "MachineId failed Rust validation" | otherwise = Right (MachineId value)
machineIdValue :: MachineId -> BS.ByteString
machineIdValue = unMachineId

newtype OperationId = OperationId { unOperationId :: BS.ByteString } deriving (Eq, Ord, Show)
mkOperationId :: BS.ByteString -> Either String OperationId
mkOperationId value | BS.null value || BS.length value /= 16 = Left "OperationId failed Rust validation" | otherwise = Right (OperationId value)
operationIdValue :: OperationId -> BS.ByteString
operationIdValue = unOperationId

newtype WorkspaceId = WorkspaceId { unWorkspaceId :: BS.ByteString } deriving (Eq, Ord, Show)
mkWorkspaceId :: BS.ByteString -> Either String WorkspaceId
mkWorkspaceId value | BS.null value || BS.length value /= 16 = Left "WorkspaceId failed Rust validation" | otherwise = Right (WorkspaceId value)
workspaceIdValue :: WorkspaceId -> BS.ByteString
workspaceIdValue = unWorkspaceId

newtype CheckpointId = CheckpointId { unCheckpointId :: BS.ByteString } deriving (Eq, Ord, Show)
mkCheckpointId :: BS.ByteString -> Either String CheckpointId
mkCheckpointId value | BS.null value || BS.length value /= 16 = Left "CheckpointId failed Rust validation" | otherwise = Right (CheckpointId value)
checkpointIdValue :: CheckpointId -> BS.ByteString
checkpointIdValue = unCheckpointId

newtype IdempotencyKeyBytes = IdempotencyKeyBytes { unIdempotencyKeyBytes :: BS.ByteString } deriving (Eq, Ord, Show)
mkIdempotencyKeyBytes :: BS.ByteString -> Either String IdempotencyKeyBytes
mkIdempotencyKeyBytes value | BS.null value = Left "IdempotencyKeyBytes failed Rust validation" | otherwise = Right (IdempotencyKeyBytes value)
idempotencyKeyBytesValue :: IdempotencyKeyBytes -> BS.ByteString
idempotencyKeyBytesValue = unIdempotencyKeyBytes

newtype IdempotencyKeyText = IdempotencyKeyText { unIdempotencyKeyText :: String } deriving (Eq, Ord, Show)
mkIdempotencyKeyText :: String -> Either String IdempotencyKeyText
mkIdempotencyKeyText value | null value = Left "IdempotencyKeyText failed Rust validation" | otherwise = Right (IdempotencyKeyText value)
idempotencyKeyTextValue :: IdempotencyKeyText -> String
idempotencyKeyTextValue = unIdempotencyKeyText

newtype IdempotencyKey = IdempotencyKey { unIdempotencyKey :: BS.ByteString } deriving (Eq, Ord, Show)
mkIdempotencyKey :: BS.ByteString -> Either String IdempotencyKey
mkIdempotencyKey value | BS.null value || BS.length value /= 16 = Left "IdempotencyKey failed Rust validation" | otherwise = Right (IdempotencyKey value)
idempotencyKeyValue :: IdempotencyKey -> BS.ByteString
idempotencyKeyValue = unIdempotencyKey

newtype OpaqueText = OpaqueText { unOpaqueText :: String } deriving (Eq, Ord, Show)
mkOpaqueText :: String -> Either String OpaqueText
mkOpaqueText value | null value = Left "OpaqueText failed Rust validation" | otherwise = Right (OpaqueText value)
opaqueTextValue :: OpaqueText -> String
opaqueTextValue = unOpaqueText

newtype UploadId = UploadId { unUploadId :: String } deriving (Eq, Ord, Show)
mkUploadId :: String -> Either String UploadId
mkUploadId value | null value = Left "UploadId failed Rust validation" | otherwise = Right (UploadId value)
uploadIdValue :: UploadId -> String
uploadIdValue = unUploadId

newtype Sha256Digest = Sha256Digest { unSha256Digest :: BS.ByteString } deriving (Eq, Ord, Show)
mkSha256Digest :: BS.ByteString -> Either String Sha256Digest
mkSha256Digest value | BS.length value /= 32 = Left "Sha256Digest failed Rust validation" | otherwise = Right (Sha256Digest value)
sha256DigestValue :: Sha256Digest -> BS.ByteString
sha256DigestValue = unSha256Digest

newtype RevisionDigest = RevisionDigest { unRevisionDigest :: BS.ByteString } deriving (Eq, Ord, Show)
mkRevisionDigest :: BS.ByteString -> Either String RevisionDigest
mkRevisionDigest value | BS.length value /= 32 = Left "RevisionDigest failed Rust validation" | otherwise = Right (RevisionDigest value)
revisionDigestValue :: RevisionDigest -> BS.ByteString
revisionDigestValue = unRevisionDigest

newtype Image = Image { unImage :: BS.ByteString } deriving (Eq, Ord, Show)
mkImage :: BS.ByteString -> Either String Image
mkImage value = Right (Image value)
imageValue :: Image -> BS.ByteString
imageValue = unImage

newtype Revision = Revision { unRevision :: Integer } deriving (Eq, Ord, Show)
mkRevision :: Integer -> Either String Revision
mkRevision value | value < 0 = Left "Revision failed Rust validation" | otherwise = Right (Revision value)
revisionValue :: Revision -> Integer
revisionValue = unRevision

newtype RunId = RunId { unRunId :: BS.ByteString } deriving (Eq, Ord, Show)
mkRunId :: BS.ByteString -> Either String RunId
mkRunId value | BS.length value /= 16 = Left "RunId failed Rust validation" | otherwise = Right (RunId value)
runIdValue :: RunId -> BS.ByteString
runIdValue = unRunId

newtype EvaluationId = EvaluationId { unEvaluationId :: BS.ByteString } deriving (Eq, Ord, Show)
mkEvaluationId :: BS.ByteString -> Either String EvaluationId
mkEvaluationId value | BS.length value /= 16 = Left "EvaluationId failed Rust validation" | otherwise = Right (EvaluationId value)
evaluationIdValue :: EvaluationId -> BS.ByteString
evaluationIdValue = unEvaluationId

newtype PageLimit = PageLimit { unPageLimit :: Integer } deriving (Eq, Ord, Show)
mkPageLimit :: Integer -> Either String PageLimit
mkPageLimit value | value <= 0 || value > 1000 = Left "PageLimit failed Rust validation" | otherwise = Right (PageLimit value)
pageLimitValue :: PageLimit -> Integer
pageLimitValue = unPageLimit

newtype StreamPageLimit = StreamPageLimit { unStreamPageLimit :: Integer } deriving (Eq, Ord, Show)
mkStreamPageLimit :: Integer -> Either String StreamPageLimit
mkStreamPageLimit value | value <= 0 || value > 1024 = Left "StreamPageLimit failed Rust validation" | otherwise = Right (StreamPageLimit value)
streamPageLimitValue :: StreamPageLimit -> Integer
streamPageLimitValue = unStreamPageLimit

newtype MachinePageLimit = MachinePageLimit { unMachinePageLimit :: Integer } deriving (Eq, Ord, Show)
mkMachinePageLimit :: Integer -> Either String MachinePageLimit
mkMachinePageLimit value | value <= 0 || value > 256 = Left "MachinePageLimit failed Rust validation" | otherwise = Right (MachinePageLimit value)
machinePageLimitValue :: MachinePageLimit -> Integer
machinePageLimitValue = unMachinePageLimit

newtype MachineEventPageLimit = MachineEventPageLimit { unMachineEventPageLimit :: Integer } deriving (Eq, Ord, Show)
mkMachineEventPageLimit :: Integer -> Either String MachineEventPageLimit
mkMachineEventPageLimit value | value <= 0 || value > 1024 = Left "MachineEventPageLimit failed Rust validation" | otherwise = Right (MachineEventPageLimit value)
machineEventPageLimitValue :: MachineEventPageLimit -> Integer
machineEventPageLimitValue = unMachineEventPageLimit

newtype CommitId = CommitId { unCommitId :: BS.ByteString } deriving (Eq, Ord, Show)
mkCommitId :: BS.ByteString -> Either String CommitId
mkCommitId value | BS.null value = Left "CommitId failed Rust validation" | otherwise = Right (CommitId value)
commitIdValue :: CommitId -> BS.ByteString
commitIdValue = unCommitId

newtype OpenEnumValue = OpenEnumValue { unOpenEnumValue :: Int } deriving (Eq, Ord, Show)
mkOpenEnumValue :: Int -> Either String OpenEnumValue
mkOpenEnumValue value = Right (OpenEnumValue value)
openEnumValueValue :: OpenEnumValue -> Int
openEnumValueValue = unOpenEnumValue

newtype OpaqueBytes = OpaqueBytes { unOpaqueBytes :: BS.ByteString } deriving (Eq, Ord, Show)
mkOpaqueBytes :: BS.ByteString -> Either String OpaqueBytes
mkOpaqueBytes value = Right (OpaqueBytes value)
opaqueBytesValue :: OpaqueBytes -> BS.ByteString
opaqueBytesValue = unOpaqueBytes

newtype SequenceNumber = SequenceNumber { unSequenceNumber :: Integer } deriving (Eq, Ord, Show)
mkSequenceNumber :: Integer -> Either String SequenceNumber
mkSequenceNumber value | value < 0 = Left "SequenceNumber failed Rust validation" | otherwise = Right (SequenceNumber value)
sequenceNumberValue :: SequenceNumber -> Integer
sequenceNumberValue = unSequenceNumber

newtype NonNegativeCount = NonNegativeCount { unNonNegativeCount :: Integer } deriving (Eq, Ord, Show)
mkNonNegativeCount :: Integer -> Either String NonNegativeCount
mkNonNegativeCount value | value < 0 = Left "NonNegativeCount failed Rust validation" | otherwise = Right (NonNegativeCount value)
nonNegativeCountValue :: NonNegativeCount -> Integer
nonNegativeCountValue = unNonNegativeCount

newtype PositiveCount = PositiveCount { unPositiveCount :: Integer } deriving (Eq, Ord, Show)
mkPositiveCount :: Integer -> Either String PositiveCount
mkPositiveCount value | value <= 0 = Left "PositiveCount failed Rust validation" | otherwise = Right (PositiveCount value)
positiveCountValue :: PositiveCount -> Integer
positiveCountValue = unPositiveCount

newtype UnixTimestampMillis = UnixTimestampMillis { unUnixTimestampMillis :: Integer } deriving (Eq, Ord, Show)
mkUnixTimestampMillis :: Integer -> Either String UnixTimestampMillis
mkUnixTimestampMillis value | value < 0 = Left "UnixTimestampMillis failed Rust validation" | otherwise = Right (UnixTimestampMillis value)
unixTimestampMillisValue :: UnixTimestampMillis -> Integer
unixTimestampMillisValue = unUnixTimestampMillis
