// Generated by acyclic-sdk-contract-wire; do not edit.
// rust_policy_source_binding: C3EB0FB2EC4A1E44476E73FDBFF3FCE33616AE7DB6A819763FDD2711CFC1A199

package dev.acyclic.transport;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class GeneratedRemotePolicy {
  private GeneratedRemotePolicy() {}

  public enum Runtime { NATIVE, BROWSER }
  public enum Transport { GRPC, GRPC_WEB, HTTP_JSON }
  public record Option(Transport transport, boolean streaming, boolean bearerAuth) {}
  public record Operation(boolean clientStreaming, boolean serverStreaming, boolean bearerAuth, String cancellation) {}
  public record Availability(boolean grpc, boolean grpcWeb, boolean httpJson) {
    public static final Availability ALL = new Availability(true, true, true);
    public static final Availability GRPC_ONLY = new Availability(true, false, false);
    boolean supports(Transport transport) {
      return switch (transport) {
        case GRPC -> grpc;
        case GRPC_WEB -> grpcWeb;
        case HTTP_JSON -> httpJson;
      };
    }
  }
  public record Defaults(String endpoint, String bearerToken) {
    public static Defaults fromEnvironment() {
      return new Defaults(firstNonBlank(System.getProperty("acyclic.endpoint"),
          System.getenv("ACYCLIC_ENDPOINT"), "http://127.0.0.1:8080"),
          firstNonBlank(System.getProperty("acyclic.bearerToken"),
          System.getenv("ACYCLIC_BEARER_TOKEN"), ""));
    }
  }

  public static final String SOURCE_BINDING = "C3EB0FB2EC4A1E44476E73FDBFF3FCE33616AE7DB6A819763FDD2711CFC1A199";
  public static final String PROBE = "none";
  public static final String POST_FAILURE_FALLBACK = "none";
  public static final String REPLAY = "none";
  public static final Map<Runtime, Map<String, List<Option>>> OPTIONS = Map.of(
      Runtime.NATIVE, buildOptions(ClientRuntime.NATIVE),
      Runtime.BROWSER, buildOptions(ClientRuntime.BROWSER));
  public static final Map<String, Map<String, Operation>> OPERATIONS = buildOperations();

  private enum ClientRuntime { NATIVE, BROWSER }

  private static Map<String, List<Option>> buildOptions(ClientRuntime runtime) {
    Map<String, List<Option>> result = new LinkedHashMap<>();
    switch (runtime) {
      case NATIVE -> {
        result.put("actors", List.of(new Option(Transport.GRPC, false, true), new Option(Transport.HTTP_JSON, false, true)));
        result.put("workers", List.of(new Option(Transport.GRPC, false, true), new Option(Transport.HTTP_JSON, false, true)));
        result.put("objects", List.of(new Option(Transport.GRPC, true, true), new Option(Transport.HTTP_JSON, true, true)));
        result.put("stream", List.of(new Option(Transport.GRPC, true, true), new Option(Transport.HTTP_JSON, true, true)));
        result.put("inference", List.of(new Option(Transport.GRPC, true, true), new Option(Transport.HTTP_JSON, true, true)));
        result.put("machines", List.of(new Option(Transport.GRPC, true, false)));
        result.put("filesystem", List.of(new Option(Transport.GRPC, true, true)));
        result.put("harness", List.of(new Option(Transport.GRPC, true, true)));
      }
      case BROWSER -> {
        result.put("actors", List.of(new Option(Transport.HTTP_JSON, false, true)));
        result.put("workers", List.of(new Option(Transport.HTTP_JSON, false, true)));
        result.put("objects", List.of(new Option(Transport.HTTP_JSON, true, true)));
        result.put("stream", List.of(new Option(Transport.HTTP_JSON, true, true)));
        result.put("inference", List.of(new Option(Transport.HTTP_JSON, true, true)));
        result.put("machines", List.of());
        result.put("filesystem", List.of(new Option(Transport.GRPC_WEB, true, true)));
        result.put("harness", List.of());
      }
    }
    return Collections.unmodifiableMap(result);
  }

  private static Map<String, Map<String, Operation>> buildOperations() {
    Map<String, Map<String, Operation>> result = new LinkedHashMap<>();
    Map<String, Operation> actors = new LinkedHashMap<>();
    actors.put("acyclic.actors.v1.ActorsService/CreateActor", new Operation(false, false, true, "none"));
    actors.put("acyclic.actors.v1.ActorsService/UpdateActor", new Operation(false, false, true, "none"));
    actors.put("acyclic.actors.v1.ActorsService/InspectActor", new Operation(false, false, true, "none"));
    actors.put("acyclic.actors.v1.ActorsService/AddSubscription", new Operation(false, false, true, "none"));
    actors.put("acyclic.actors.v1.ActorsService/RemoveSubscription", new Operation(false, false, true, "none"));
    actors.put("acyclic.actors.v1.ActorsService/ResumeSubscription", new Operation(false, false, true, "none"));
    actors.put("acyclic.actors.v1.ActorsService/CheckpointActor", new Operation(false, false, true, "none"));
    actors.put("acyclic.actors.v1.ActorsService/InvokeActor", new Operation(false, false, true, "none"));
    result.put("actors", Collections.unmodifiableMap(actors));
    Map<String, Operation> workers = new LinkedHashMap<>();
    workers.put("acyclic.workers.v1.WorkersService/PublishVersion", new Operation(false, false, true, "none"));
    workers.put("acyclic.workers.v1.WorkersService/SelectDeployment", new Operation(false, false, true, "none"));
    workers.put("acyclic.workers.v1.WorkersService/SubmitJob", new Operation(false, false, true, "none"));
    workers.put("acyclic.workers.v1.WorkersService/InspectJob", new Operation(false, false, true, "none"));
    workers.put("acyclic.workers.v1.WorkersService/CancelJob", new Operation(false, false, true, "none"));
    workers.put("acyclic.workers.v1.WorkersService/InvokeVersion", new Operation(false, false, true, "none"));
    workers.put("acyclic.workers.v1.WorkersService/InvokeDeployment", new Operation(false, false, true, "none"));
    result.put("workers", Collections.unmodifiableMap(workers));
    Map<String, Operation> objects = new LinkedHashMap<>();
    objects.put("acyclic.objects.v2.BucketsService/CreateBucket", new Operation(false, false, true, "none"));
    objects.put("acyclic.objects.v2.BucketsService/HeadBucket", new Operation(false, false, true, "none"));
    objects.put("acyclic.objects.v2.BucketsService/DeleteBucket", new Operation(false, false, true, "none"));
    objects.put("acyclic.objects.v2.ObjectsService/PutObject", new Operation(true, false, true, "call"));
    objects.put("acyclic.objects.v2.ObjectsService/GetObject", new Operation(false, true, true, "call"));
    objects.put("acyclic.objects.v2.ObjectsService/HeadObject", new Operation(false, false, true, "none"));
    objects.put("acyclic.objects.v2.ObjectsService/DeleteObject", new Operation(false, false, true, "none"));
    objects.put("acyclic.objects.v2.ObjectsService/ListObjects", new Operation(false, false, true, "none"));
    objects.put("acyclic.objects.v2.MultipartService/CreateMultipart", new Operation(false, false, true, "none"));
    objects.put("acyclic.objects.v2.MultipartService/UploadPart", new Operation(true, false, true, "call"));
    objects.put("acyclic.objects.v2.MultipartService/ListParts", new Operation(false, false, true, "none"));
    objects.put("acyclic.objects.v2.MultipartService/CompleteMultipart", new Operation(false, false, true, "none"));
    objects.put("acyclic.objects.v2.MultipartService/AbortMultipart", new Operation(false, false, true, "none"));
    result.put("objects", Collections.unmodifiableMap(objects));
    Map<String, Operation> stream = new LinkedHashMap<>();
    stream.put("acyclic.stream.v2.StreamService/InspectIdempotency", new Operation(false, false, true, "none"));
    stream.put("acyclic.stream.v2.StreamService/Append", new Operation(false, false, true, "none"));
    stream.put("acyclic.stream.v2.StreamService/Tail", new Operation(false, false, true, "none"));
    stream.put("acyclic.stream.v2.StreamService/Fork", new Operation(false, false, true, "none"));
    stream.put("acyclic.stream.v2.StreamService/Read", new Operation(false, true, true, "call"));
    stream.put("acyclic.stream.v2.StreamService/Follow", new Operation(false, true, true, "call"));
    stream.put("acyclic.stream.v2.StreamService/Children", new Operation(false, true, true, "call"));
    stream.put("acyclic.stream.v2.StreamService/ChildrenPage", new Operation(false, false, true, "none"));
    stream.put("acyclic.stream.v2.StreamService/Commit", new Operation(false, false, true, "none"));
    stream.put("acyclic.stream.v2.StreamService/ReadCommit", new Operation(false, false, true, "none"));
    result.put("stream", Collections.unmodifiableMap(stream));
    Map<String, Operation> inference = new LinkedHashMap<>();
    inference.put("inference.customer.v1.ModelsService/List", new Operation(false, false, true, "none"));
    inference.put("inference.customer.v1.ContextsService/Create", new Operation(false, false, true, "none"));
    inference.put("inference.customer.v1.ContextsService/Inspect", new Operation(false, false, true, "none"));
    inference.put("inference.customer.v1.ContextsService/Mutate", new Operation(false, false, true, "none"));
    inference.put("inference.customer.v1.WarmContextsService/Retain", new Operation(false, false, true, "none"));
    inference.put("inference.customer.v1.WarmContextsService/Inspect", new Operation(false, false, true, "none"));
    inference.put("inference.customer.v1.WarmContextsService/Renew", new Operation(false, false, true, "none"));
    inference.put("inference.customer.v1.WarmContextsService/Release", new Operation(false, false, true, "none"));
    inference.put("inference.customer.v1.RunsService/Generate", new Operation(false, false, true, "none"));
    inference.put("inference.customer.v1.RunsService/Inspect", new Operation(false, false, true, "none"));
    inference.put("inference.customer.v1.RunsService/Watch", new Operation(false, true, true, "call"));
    inference.put("inference.customer.v1.RunsService/Cancel", new Operation(false, false, true, "operation"));
    inference.put("inference.customer.v1.EvaluationsService/Create", new Operation(false, false, true, "none"));
    inference.put("inference.customer.v1.EvaluationsService/Inspect", new Operation(false, false, true, "none"));
    result.put("inference", Collections.unmodifiableMap(inference));
    Map<String, Operation> machines = new LinkedHashMap<>();
    machines.put("acyclic.machines.v1.MachinesService/QualifyImage", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/Create", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/Checkpoint", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/Fork", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/ForkMachine", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/Suspend", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/Wake", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/SetSuspensionPolicy", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/DestroyMachine", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/DestroyCheckpoint", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/Recover", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/InspectMachine", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/InspectCheckpoint", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/ListMachines", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/Events", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/Usage", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/Cancel", new Operation(false, false, false, "operation"));
    machines.put("acyclic.machines.v1.MachinesService/InspectOperation", new Operation(false, false, false, "none"));
    machines.put("acyclic.machines.v1.MachinesService/WatchOperation", new Operation(false, true, false, "call"));
    result.put("machines", Collections.unmodifiableMap(machines));
    Map<String, Operation> filesystem = new LinkedHashMap<>();
    filesystem.put("acyclic.filesystem.v2.FilesystemService/Handshake", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/CreateWorkspace", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/OpenWorkspace", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/DeleteWorkspace", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/GetHead", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/GetGeneration", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/Read", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/Stat", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/ListDirectory", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/ReadLink", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/PlanExtents", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/ApplyTransaction", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/RebaseTransaction", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/ForkWorkspace", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/Diff", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/Rebase", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/PlanJoin", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/ApplyJoin", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/Checkpoint", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/Pin", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/Export", new Operation(false, true, true, "call"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/Import", new Operation(true, false, true, "call"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/IssueMountCredential", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/IssueS3Credential", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/GetSourceState", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/ReconcileSource", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/RescanSource", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/SealSource", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/Observe", new Operation(false, false, true, "none"));
    filesystem.put("acyclic.filesystem.v2.FilesystemService/Cancel", new Operation(false, false, true, "operation"));
    result.put("filesystem", Collections.unmodifiableMap(filesystem));
    Map<String, Operation> harness = new LinkedHashMap<>();
    harness.put("acyclic.harness.v2.HarnessService/Handshake", new Operation(false, false, true, "none"));
    harness.put("acyclic.harness.v2.HarnessService/Submit", new Operation(false, false, true, "none"));
    harness.put("acyclic.harness.v2.HarnessService/Replay", new Operation(false, true, true, "call"));
    harness.put("acyclic.harness.v2.HarnessService/Observe", new Operation(false, false, true, "none"));
    harness.put("acyclic.harness.v2.HarnessService/Cancel", new Operation(false, false, true, "operation"));
    result.put("harness", Collections.unmodifiableMap(harness));
    return Collections.unmodifiableMap(result);
  }

  public static Transport select(
      String family,
      Runtime runtime,
      boolean streaming,
      boolean bearerAuth,
      Availability installed,
      Availability endpoint,
      Transport override) {
    List<Option> familyOptions = OPTIONS.get(runtime).get(family);
    if (familyOptions == null) throw new IllegalArgumentException("unknown transport family or runtime: " + family + "/" + runtime);
    for (Option option : familyOptions) {
      if (option.transport() == override && compatible(option, streaming, bearerAuth, installed, endpoint)) return option.transport();
    }
    if (override != null) throw new IllegalArgumentException("unsupported transport override for " + family + "/" + runtime);
    for (Option option : familyOptions) {
      if (compatible(option, streaming, bearerAuth, installed, endpoint)) return option.transport();
    }
    throw new IllegalArgumentException("no compatible transport for " + family + "/" + runtime);
  }

  private static boolean compatible(Option option, boolean streaming, boolean bearerAuth,
                                    Availability installed, Availability endpoint) {
    return installed.supports(option.transport()) && endpoint.supports(option.transport())
        && (!streaming || option.streaming()) && (!bearerAuth || option.bearerAuth());
  }

  public static boolean requiresBearer(String family, Runtime runtime) {
    List<Option> familyOptions = OPTIONS.get(runtime).get(family);
    if (familyOptions == null || familyOptions.isEmpty()) {
      throw new IllegalArgumentException("unknown transport family or runtime: " + family + "/" + runtime);
    }
    return familyOptions.get(0).bearerAuth();
  }

  public static String validateBearer(String token) {
    if (token == null || token.isBlank() || token.indexOf('\r') >= 0 || token.indexOf('\n') >= 0) {
      throw new IllegalArgumentException("invalid bearer credential");
    }
    return token;
  }

  private static String firstNonBlank(String first, String second, String fallback) {
    if (first != null && !first.isBlank()) return first;
    if (second != null && !second.isBlank()) return second;
    return fallback;
  }
}
